### ISSUE TITLE
Does this project support reading remote attachment storage for audio and video transcription?

### ISSUE THREAD

**Issue by B1gM8c** [guillaumekln/faster-whisper#104]
I have a few questions for you. Can faster-whisper support receiving remote attachments stored in services like OSS buckets or AWS S3, and then transcribe the files? This would be preferable for providing an online page since uploading files to a server could take up too much bandwidth and storage space. If remote attachments are supported, I'll know how to modify the relevant code. However, it seems that even OpenAI's official API requires users to upload files to their server for transcription, so I'm skeptical of its feasibility. Thank you for taking the time to respond, I really appreciate it!

**Comment by guillaumekln** [comment]
No, this project cannot do that.

You should use a separate library to first download the remote file on the server, and then transcribe the file with faster-whisper.
