### ISSUE TITLE
Having problem installing master branch

### ISSUE THREAD

**Issue by Hannes1** [guillaumekln/faster-whisper#105]
Since you made the official PyPI package, I've been struggling to install the latest branch when I try to install it says install done but none of the dependencies, etc.. get installed🤔 
It's worth mentioning I use poetry, but it did work before the official PyPI

Is there something I'm missing, because on the other hand, it does work when I clone the repo and install it from the repo😂 maybe it's just poetry

**Comment by guillaumekln** [comment]
I'm not familiar with poetry and I don't know why the PyPI release would make a difference.

How do you declare the dependency in poetry? Does it look like one of the following?
* https://python-poetry.org/docs/dependency-specification/#git-dependencies
* https://python-poetry.org/docs/dependency-specification/#url-dependencies?
