### ISSUE TITLE
Docker image for run 

### ISSUE THREAD

**Issue by marco-ramirezpp** [guillaumekln/faster-whisper#109]
I'm trying to implement in a docker installing from docker Ctranslate2 image, however, I get a cuBLAS error to initialized. 

Maybe someone have a list of requirements to run in ubuntu 20.04, I installed cuda toolkit, cuDNN 8, but the error continue.

**Comment by guillaumekln** [comment]
Can you post your `Dockerfile` and how you run it?

**Comment by hobodrifterdavid** [comment]
I'm getting it to run ok with this Dockerfile:

> FROM nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04
> 
> # Install necessary dependencies
> RUN apt-get update && apt-get install -y python3-pip
> 
> # Set the working directory
> WORKDIR /app
> 
> # Copy the app code and requirements filed
> COPY . /app
> 
> # Install the app dependencies
> RUN pip3 install --no-cache-dir -r requirements.txt

Build with:
docker build -t asr .
Run in interactive mode with:
docker run -it --rm --gpus '"device=0,1"' -v $(pwd):/app asr

**Comment by marco-ramirezpp** [comment]
Solved Thank you!
