### ISSUE TITLE
segment timestamp problem

### ISSUE THREAD

**Issue by johnchienbronci** [guillaumekln/faster-whisper#110]
Version: 2f266eb8442a651b8b9a30f499aded609eb31f47 (master)
Issue: 
I compared the segment timestamp with the word timestamp, 
and found that there is a gap under the word timestamp, 
but the time seen under the segment is continuous.  
Adjusting the vad parameter only changes the word times.

test 1: min silence duration=20, 
error cause: segment end timestamp error
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/27708347/229684743-04f8af7a-1d59-4529-8629-9e206a37447c.png">

test2:  min silence duration=20 or 500, 
error cause: 
 a. only a segment, but I think  should be 3 segments timestamp, 
 b. word timestamp is not accurate, Words are not aligned on waves

<img width="755" alt="image" src="https://user-images.githubusercontent.com/27708347/229691770-ae3d8452-9a64-4c80-93c3-51eaedbfa383.png">

<img width="842" alt="image" src="https://user-images.githubusercontent.com/27708347/229689274-16998369-a5a4-48ae-9265-f80f2889358f.png">

**Comment by guillaumekln** [comment]
> segment end timestamp error

This is expected if you transcribed without word timestamps. Even if you only output segments, you can enable the word timestamps to refine the segment start and end.

> only a segment, but I think should be 3 segments timestamp,

Does it make a difference if you disable VAD or use the default VAD parameters?

**Comment by johnchienbronci** [comment]
> > segment end timestamp error
> 
> This is expected if you transcribed without word timestamps. Even if you only output segments, you can enable the word timestamps to refine the segment start and end.

I think so too, but this issue occurs when word timestamp is enabled.

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/27708347/229717844-5b6f2ffa-f05d-41dc-a199-2224694c69f9.png">


> 
> > only a segment, but I think should be 3 segments timestamp,
> 
> Does it make a difference if you disable VAD or use the default VAD parameters?

Here are the differences between enable or disable vad.

1. disable vad
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/27708347/229715720-a957f474-9984-43ba-951f-213c5bd4c013.png">

<img width="860" alt="image" src="https://user-images.githubusercontent.com/27708347/229715575-a8800171-15b3-4a61-a89d-6c584d01fca9.png">

2. enable vad: min silence duration = 500 , speech_pad_ms=30
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/27708347/229714006-d4422941-4035-4d0a-9041-4b73b69cd557.png">

<img width="852" alt="image" src="https://user-images.githubusercontent.com/27708347/229716170-3046e205-6774-4432-8e71-5d6352d9149f.png">

3. enable vad:  min silence duration = 500 , speech_pad_ms=200
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/27708347/229718792-ffce584e-d0be-4e3f-9e6f-d05a3f9c3caa.png">

<img width="845" alt="image" src="https://user-images.githubusercontent.com/27708347/229718530-2f40d643-92dd-42c0-90d9-93b23b7a3b0b.png">

4. enable vad:  min silence duration = 2000, speech_pad_ms=30
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/27708347/229714408-55587963-454d-4b9a-a170-52a026edf24b.png">

<img width="850" alt="image" src="https://user-images.githubusercontent.com/27708347/229714908-c078881a-ecd3-4268-8d44-45b0c7e1a099.png">

5. enable vad:  min silence duration = 2000, speech_pad_ms=200
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/27708347/229719076-dd92bb45-3bd8-4b7e-bbd0-8a741cd52366.png"> 

<img width="850" alt="image" src="https://user-images.githubusercontent.com/27708347/229719316-ee68687e-3722-4a37-9021-faf801167e18.png">

**Comment by guillaumekln** [comment]
Thanks, I understand what's going on. The linked PR should fix this issue.

**Comment by phliulei** [comment]
> Version: [2f266eb](https://github.com/guillaumekln/faster-whisper/commit/2f266eb8442a651b8b9a30f499aded609eb31f47) (master) Issue: I compared the segment timestamp with the word timestamp, and found that there is a gap under the word timestamp, but the time seen under the segment is continuous. Adjusting the vad parameter only changes the word times.
> 
> test 1: min silence duration=20, error cause: segment end timestamp error <img alt="image" width="1055" src="https://user-images.githubusercontent.com/27708347/229684743-04f8af7a-1d59-4529-8629-9e206a37447c.png">
> 
> test2: min silence duration=20 or 500, error cause: a. only a segment, but I think should be 3 segments timestamp, b. word timestamp is not accurate, Words are not aligned on waves
> 
> <img alt="image" width="755" src="https://user-images.githubusercontent.com/27708347/229691770-ae3d8452-9a64-4c80-93c3-51eaedbfa383.png">
> 
> <img alt="image" width="842" src="https://user-images.githubusercontent.com/27708347/229689274-16998369-a5a4-48ae-9265-f80f2889358f.png">

Thank you,and where was such GUI implemented?

**Comment by johnchienbronci** [comment]
> Thank you,and where was such GUI implemented?

https://editor.subtitlevideo.com or install Audacity
