### ISSUE TITLE
Is it possible to add some kind of verbose logging to see when the VAD is activated and drops "chunks"?

### ISSUE THREAD

**Issue by FlippFuzz** [guillaumekln/faster-whisper#112]
Would be really nice to have some feedback to know that it's working well!

Maybe something like "VAD: Dropping AA:BB to XX:YY"

**Comment by guillaumekln** [comment]
Yes, the library could use some logs.

The linked PR is adding some info and debug logs. Details about VAD chunks is logged at the debug level.

```python
import logging

logging.basicConfig()
logging.getLogger("faster_whisper").setLevel(logging.DEBUG)
```
