### ISSUE TITLE
Error on HF finetuned converted model: Floating point exception (core dumped)

### ISSUE THREAD

**Issue by funboarder13920** [guillaumekln/faster-whisper#115]
Hello Guillaume,

I'm trying to run inference on a finetuned with huggingface model.
When running model.transcribe I get a "Floating point exception (core dumped)". I've tried setting CT2_VERBOSE=3 but I don't get more info about the error.

- I'm using in the ghcr.io/opennmt/ctranslate2:latest-ubuntu20.04-cuda11.2 image.
- I get the error on CPU device an CUDA device
- Model loading doesn't trigger any error.
- There is no error when using the small/large/etc base models.

Do you know how I could get more debug info to trace back what triggered the error ?

Best,
Valentin

**Comment by funboarder13920** [comment]
It appears that the FLoating point exception is in the model.detect_language but I get another error later on the line https://github.com/guillaumekln/faster-whisper/blob/746f2698dbd49cd3ad85504f72d945b85415831d/faster_whisper/transcribe.py#L515: "ValueError: cannot create std::vector larger than max_size()"

I guess the model obtained after finetuning is not compatible anymore / has something different from the original model.

**Comment by guillaumekln** [comment]
Hi,

To convert the model, I suppose you used the same command line that is used in the README? https://github.com/guillaumekln/faster-whisper#model-conversion

Can you post the content of `config.json` in the converted model and also report the vocabulary size (`wc -l vocabulary.txt`)?

**Comment by funboarder13920** [comment]
I used the command in the read me except that I replaced the hf repo openai/whisper-large-v2 with a local path.

vocab size: 51865

```
{
  "alignment_heads": [
    [6,0],[6,1],[6,2],[6,3],[6,4],[6,5],[6,6],[6,7],[6,8],[6,9],[6,1],
    [6,1],
    [7,0],[7,1],[7,2],[7,3],[7,4],[7,5],[7,6],[7,7],[7,8],[7,9],[7,1],
    [7,1],
    [8,0],[8,1],[8,2],[8,3],[8,4],[8,5],[8,6],[8,7],[8,8],[8,9],[8,1],
    [8,1],
    [9,0],[9,1],[9,2],[9,3],[9,4],[9,5],[9,6],[9,7],[9,8],[9,9],[9,1],
    [9,1],
    [10,0],[10,1],[10,2],[10,3],[10,4],[10,5],[10,6],[10,7],[10,8],[10,9],[10,1],
    [10,1],
    [11,0],[11,1],[11,2],[11,3],[11,4],[11,5],[11,6],[11,7],[11,8],[11,9],[11,1],
    [11,1
 ]
  ],
  "lang_ids": [],
  "suppress_ids": [],
  "suppress_ids_begin": [
    220,
    50257
  ]
}
```

**Comment by guillaumekln** [comment]
This explains the issue. See if you can keep the special tokens in the vocabulary and have non empty `lang_ids` and `suppress_ids` in the configuration.

**Comment by funboarder13920** [comment]
I added the special_tokens_map.json and I can get through the errors
