### ISSUE TITLE
word-level timestamps

### ISSUE THREAD

**Issue by eschmidbauer** [guillaumekln/faster-whisper#12]
Hi, I really appreciate you sharing this implementation. 
I found it to be very fast with accurate results.
I do not see word-level timestamps in the result. Are word level timestamps possible?

**Comment by guillaumekln** [comment]
Hi,

Word-level timestamps are currently not possible. They usually require extensions to the model that are not implemented at this time.

**Comment by tohe91** [comment]
Thank you for the amazing work on this!
It would be amazing if world level timestamps could be implemented in faster-whisper, once the world-level-timestamps branch is merged to main in whisper

**Comment by lucasbr15** [comment]
Crazy about it

**Comment by collynce** [comment]
> 

Just checked out the whisper repo and world-level timestamp PR has been merged. I would be great indeed to have the same on faster-whiper. 

Great work!

**Comment by eschmidbauer** [comment]
just tested this with the tiny model and it worked!
going to do more tests but this is great, thanks so much for sharing!

**Comment by eschmidbauer** [comment]
large-v2 seems to work too. Thanks again

**Comment by Jeronymous** [comment]
When I tested word timestamps on a bunch of file, I saw this error happening on some corner case:
```
  File "/usr/local/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 531, in add_word_timestamps
    alignment = self.find_alignment(tokenizer, text_tokens, mel, num_frames)
  File "/usr/local/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 598, in find_alignment
    start_times = jump_times[word_boundaries[:-1]]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by guillaumekln** [comment]
Thank you for testing!

Do you confirm the same file works without issue in openai/whisper? If yes, is it possible for you to share this input file?

**Comment by JulianKropp** [comment]
@guillaumekln
First of all, this is very nice!

I have a quick question about the probabilities. Does it indicate how likely it is that this word was spoken, or how likely it is that this word was spoken at the this time in the segment?
