### ISSUE TITLE
Can faster-whisper run on apple silicon

### ISSUE THREAD

**Issue by ILG2021** [guillaumekln/faster-whisper#131]
I have see that ctranslate2 support apple silicon, so can faster-whisper run on apple silicon? And how to run the command. I have kown that whisper.cpp support apple silicon, but I want to use ctranslate2 as it can compatible windows.

**Comment by phineas-pta** [comment]
yes but with `float32` only, see #8

**Comment by guillaumekln** [comment]
Since version `ctranslate2>=3.11`, we also support int8 computation on Apple Silicon.

**Comment by ILG2021** [comment]
> Since version `ctranslate2>=3.11`, we also support int8 computation on Apple Silicon.
Ok I will have a try.
