### ISSUE TITLE
CUBLAS_STATUS_INVALID_VALUE on nvidia t4 when running behind gunicorn

### ISSUE THREAD

**Issue by daxaxelrod** [guillaumekln/faster-whisper#132]
When I run a normal python script that loads the model onto the gpu and runs it, everything works normally. Once I put it behind gunicorn I always get CUBLAS_STATUS_INVALID_VALUE not matter what compute_type I choose. Running on a T4 with cuda 11.6

```python
faster_whisper/transcribe.py", line 483, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_INVALID_VALUE
```

**Comment by daxaxelrod** [comment]
Upgraded to cuda 12.1, still same error. Using the same audio file as a one off script that works on the same machine.

**Comment by daxaxelrod** [comment]
Bit more information. After setting CT_VERBOSE=3 I saw it was trying to reference cuda 11.3. I removed all cuda 11.3 and 11.6 on my system just leaving 12.1 and now I'm hitting this. I see in [cublas_stub.cc](https://github.com/OpenNMT/CTranslate2/blob/c84a826bec6278c36a776f9a32da4fdc3f76f421/src/cuda/cublas_stub.cc) that CUBLAS_VER_MAJOR is being used which seems to be resolving to 11 but I have no idea where that's being set.

`RuntimeError: Library libcublas.so.11 is not found or cannot be loaded`

**Comment by guillaumekln** [comment]
You should install CUDA 11.x and cuDNN 8 for CUDA 11.x.

Regarding the error in the server, it’s probably because it is using multiple worker processes. The underlying CTranslate2 library does not work after the process is forked.

You should either import `faster_whisper` after the process is forked, or use worker threads instead of worker processes.

**Comment by daxaxelrod** [comment]
Huh very interesting. Any idea as to the reason why CTranslate2 doesnt work with worker processes? What would you recommend for a inference server setup?

**Comment by guillaumekln** [comment]
In general the CUDA runtime in not fork-safe. That’s why there could be issues when CTranslate2 is already initialized before the fork to create the child processes happen.

I recommend configuring your server to use multiple threads (not processes!).

**Comment by daxaxelrod** [comment]
I looked around and non of the django recommended production serving applications dont use. I was able to actually get it work by using importing faster whisper before the fork by using the gunicorn config. Thanks so much for this awesome lib! Already seeing a lower memory footprint on the gpu AND faster inference times!
