### ISSUE TITLE
language detected is different, with vad_filter on and off

### ISSUE THREAD

**Issue by junchen6072** [guillaumekln/faster-whisper#136]
It's probably due to features are extracted after vad_filter is applied.
Can we extract features before that?

**Comment by guillaumekln** [comment]
> Can we extract features before that?

You could do that by calling `transcribe` first just to detect the language:

```python
from faster_whisper import decode_audio

audio = decode_audio(audio_path)
language = model.transcribe(audio)[1].language

segments, _ = model.transcribe(audio, language=language, vad_filter=True)
```
