### ISSUE TITLE
Issue with condition_on_previous_text param ?

### ISSUE THREAD

**Issue by funboarder13920** [guillaumekln/faster-whisper#138]
Hello Guillaume,

Either I misunderstood the condition_on_previous_text option or there is a small error in the implementation. I thought with this option no previous decoded text would be used but it appears text from the previous segment is used.
https://github.com/guillaumekln/faster-whisper/blob/2b53dee6b697ba1364d7ba1b1c1ce3a6a2dc05df/faster_whisper/transcribe.py#L191-L194

If it is a mistake it is triggered by this line that should be at the end of the for loop / after extending all_tokens:
https://github.com/guillaumekln/faster-whisper/blob/2b53dee6b697ba1364d7ba1b1c1ce3a6a2dc05df/faster_whisper/transcribe.py#L470-L471

Best,
Valentin

**Comment by funboarder13920** [comment]
Let's see if it's accepted:
https://github.com/openai/whisper/pull/1224

**Comment by guillaumekln** [comment]
@funboarder13920 Can you also open the pull request here? I’m pretty sure the fix is correct so it be will great to include it in the next version.
