### ISSUE TITLE
Hi, can we make a new release? --force-reinstall will uninstall some existing packages

### ISSUE THREAD

**Issue by junchen6072** [guillaumekln/faster-whisper#139]
We have fixes after the current version. Can we make a new release? Thanks!

**Comment by junchen6072** [comment]
The issue is it somehow introduced unwanted dependencies, I don't know why it would install so many when run force-install when run `sudo pip install --force-reinstall "faster-whisper @ https://github.com/guillaumekln/faster-whisper/archive/e9a082dcf27647eb52585cda6f115454c0ac6856.tar.gz":`
`Successfully installed av-10.0.0 certifi-2022.12.7 charset-normalizer-3.1.0 coloredlogs-15.0.1 ctranslate2-3.11.0 faster-whisper-0.4.1 filelock-3.11.0 flatbuffers-23.3.3 huggingface_hub-0.13.4 humanfriendly-10.0 idna-3.4 mpmath-1.3.0 numpy-1.24.2 onnxruntime-1.14.1 packaging-23.0 protobuf-4.22.1 pyyaml-6.0 requests-2.28.2 sympy-1.11.1 tokenizers-0.13.3 tqdm-4.65.0 typing-extensions-4.5.0 urllib3-1.26.15
`

**Comment by junchen6072** [comment]
it also removes some packages

**Comment by junchen6072** [comment]
ok, probably do this:

`pip install "faster-whisper @ https://github.com/guillaumekln/faster-whisper/archive/refs/heads/master.tar.gz"`

**Comment by phineas-pta** [comment]
> unwanted dependencies
> removes some packages

i think it upgraded those packages to new version. did you compare the removed vs installed packages ?

**Comment by junchen6072** [comment]
I didn't explicitly compare, but pip reports some errors:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
neuralprophet 0.3.2 requires dataclasses>=0.6, which is not installed.
chromadb 0.3.18 requires posthog>=2.4.0, which is not installed.
autogluon-timeseries 0.7.0 requires statsforecast<1.5,>=1.4.0, which is not installed.
autogluon-multimodal 0.7.0 requires evaluate<0.4.0,>=0.2.2, which is not installed.

```

**Comment by junchen6072** [comment]
I'll look into conda, thanks for taking a look
