### ISSUE TITLE
Support float32?

### ISSUE THREAD

**Issue by hippylover** [guillaumekln/faster-whisper#14]
`16:52:07 kris ~/faster-whisper $ python test_transcription.py 
Traceback (most recent call last):
  File "/home/kris/faster-whisper/test_transcription.py", line 8, in <module>
    model = WhisperModel(model_path, device="cpu", compute_type="float16") # compute_type="float16"
  File "/home/kris/faster-whisper/faster_whisper/transcribe.py", line 71, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.`

I get somewhat of the same error with whisper however it automatically changes to float32. Is there a possible fix for this?

**Comment by guillaumekln** [comment]
Simply remove the `compute_type` argument and it will automatically convert the model to float32.

**Comment by hippylover** [comment]
that was easier than expected :D
