### ISSUE TITLE
segment generation is slow

### ISSUE THREAD

**Issue by SinanAkkoyun** [guillaumekln/faster-whisper#141]
Hey! I'm simply amazed by the crazy fast inference time!!!

I have the following code snippet:

```py
start = time.time()
print("Transcribing audio file...") 
segments, _ = model.transcribe("samples/sinan_speech_30s_16.wav", word_timestamps=True, beam_size=1)

# print("Detected language '%s' with probability %f" % (info.language, info.language_probability))

print("Transcription took %.2fs" % (time.time() - start))
print('\n')

for segment in segments:
    for word in segment.words:
        # print("[%.2fs -> %.2fs] %s" % (word.start, word.end, word.word))
        print(word.word, end='', flush=True) # same 'speed' with flush=False
```

For some reason, the loop takes forever... The transcription speed is about 1.39s for a 30s audio clip (just AMAZING?!?!) but the loop takes around 10s

I really appreciate any help!

**Comment by raulqf** [comment]
I am experiencing the same issue. I think it is because segments are generators and you must wait up to finish their processing, isn't it?

**Comment by SinanAkkoyun** [comment]
Really, is it like that? Is there a way around that? And does that mean that transcription times are incorrect?

**Comment by SinanAkkoyun** [comment]
When transcribing a 2s audio file with word_timestamps, I get a performance of about 0.4s which is only slightly faster than the openai/whisper model (0.5s). Is that expected

**Comment by guillaumekln** [comment]
This was already discussed several times. See #67 or #117.
