### ISSUE TITLE
Webservice

### ISSUE THREAD

**Issue by fflorent** [guillaumekln/faster-whisper#145]
First of all, thanks for your work!

I don't think there exists a HTTP API, just like this one: https://github.com/ahmetoner/whisper-asr-webservice

I intend to implement it, as a separate project. Are you interested?

**Comment by guillaumekln** [comment]
Hello,

It looks like the project you shared is trying to integrate fatser-whisper: https://github.com/ahmetoner/whisper-asr-webservice/pull/81

In any case, this type of development should indeed be done in a separate project. When it's ready we could add a link to it in the README.
