### ISSUE TITLE
Floating point exception (core dumped), but can't find core dump in /var/lib/systemd/coredump/

### ISSUE THREAD

**Issue by junchen6072** [guillaumekln/faster-whisper#148]
Where can I find the core dump?

**Comment by guillaumekln** [comment]
How did you get this error?

Can you share the steps to reproduce? (model size, transcription options, input file if possible)

**Comment by junchen6072** [comment]
> How did you get this error?
> 
> Can you share the steps to reproduce? (model size, transcription options, input file if possible)

Hi, sorry I can't share the input file. This is annoying that prevents interactive debug with you awesome guys =.=

But the model is:
`model = WhisperModel('/home/whisper-large-v2-ct2/', device="cuda", compute_type="float16", cpu_threads=4, num_workers=2)`

called with:
`segments, _ = model.transcribe(audio=audiof, word_timestamps=True)`

**Comment by junchen6072** [comment]
I basically tried the notebook here: https://github.com/Majdoddin/nlp/blob/main/Pyannote_plays_and_Whisper_rhymes_v_2_0.ipynb

It's not happening on every of my input file though

**Comment by guillaumekln** [comment]
I found a case where this error happens and fixed it in this PR https://github.com/OpenNMT/CTranslate2/pull/1170.

I will update this issue when the fix is released and you will be able to test again.

**Comment by guillaumekln** [comment]
Can you update to `ctranslate2>=3.12` and see if you still get the error?

**Comment by junchen6072** [comment]
thanks, I'll try today or tomorrow

**Comment by junchen6072** [comment]
sorry was busy with some deadlines.
I wasn't able to run that library to repro today after tried for 10+mins, but since I'll not use it, I assume this is fixed. Thanks!
