### ISSUE TITLE
Multi-GPU failing with "Cannot use multiple GPUs with different Compute Capabilities for the same model"

### ISSUE THREAD

**Issue by Jeronymous** [guillaumekln/faster-whisper#149]
I have 2 old GPUs: one `NVIDIA GeForce GTX TITAN X` and one `NVIDIA GeForce GTX 1080 Ti` (Driver Version: 470.161.03, CUDA Version: 11.4).
It's OK to run faster_whisper separately on both GPUs, with `compute_type="float32"` (lower precision is not supported for those GPUs).
But when I try to instantiate
```
faster_whisper.WhisperModel(
      "tiny",
      device="cuda",
      device_index=[0,1],
      compute_type="float32",
)
```
it fails with the following error:
```
  File "/usr/local/lib/python3.8/dist-packages/faster_whisper/transcribe.py", line 101, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: Cannot use multiple GPUs with different Compute Capabilities for the same model
```
Is it because I have two different GPUs?

**Comment by guillaumekln** [comment]
Yes, we currently disallow using different GPU types for the same model instance. In general it could work but it also comes with possible issues and inconsistencies so we just raise an error for the moment.

Note that the 1080 Ti can run int8 models with `compute_type="int8"`.

**Comment by Jeronymous** [comment]
OK thanks a lot for the clarification!
