### ISSUE TITLE
How to specify the right GPU index, with an order that corresponds to nvidia-smi ("export CUDA_DEVICE_ORDER=PCI_BUS_ID" does not have any effect)

### ISSUE THREAD

**Issue by Jeronymous** [guillaumekln/faster-whisper#150]
I have two GPUs, and when I use the `device_index` of `faster_whisper.WhisperModel` to specify the device, the chosen GPU is not the one that corresponds to this index, if I look at the order in which GPUs appear with `nvidia-smi`.

When I use torch, I work around this problem by setting the environment variable:
```
export CUDA_DEVICE_ORDER=PCI_BUS_ID
```
but somehow with faster_whisper, this does not have any effect.

Is there a solution to that with faster_whisper?

**Comment by guillaumekln** [comment]
Can you set the environment variable `CT2_VERBOSE=1` and check if the GPU order is also incorrect in the info logs?

**Comment by Jeronymous** [comment]
Indeed the GPU order is "incorrect" in the info log.
from nvidia-smi:
```
$ nvidia-smi -L
GPU 0: NVIDIA GeForce GTX TITAN X (UUID: GPU-165f30e1-48b3-48b0-f417-416ee6f0a23c)
GPU 1: NVIDIA GeForce GTX 1080 Ti (UUID: GPU-d6f19808-0123-208c-e952-74149e3f615a)
```
CT2_VERBOSE info logs:
```
[2023-04-16 17:09:35.497] [ctranslate2] [thread 7] [info] GPU #0: NVIDIA GeForce GTX 1080 Ti (CC=6.1)
[2023-04-16 17:09:35.497] [ctranslate2] [thread 7] [info]  - Allow INT8: true
[2023-04-16 17:09:35.497] [ctranslate2] [thread 7] [info]  - Allow FP16: false (with Tensor Cores: false)
[2023-04-16 17:09:35.497] [ctranslate2] [thread 7] [info] GPU #1: NVIDIA GeForce GTX TITAN X (CC=5.2)
[2023-04-16 17:09:35.497] [ctranslate2] [thread 7] [info]  - Allow INT8: false
[2023-04-16 17:09:35.497] [ctranslate2] [thread 7] [info]  - Allow FP16: false (with Tensor Cores: false)
```

**Comment by guillaumekln** [comment]
I don't see why this variable would not work. If variables such as `CUDA_VISIBLE_DEVICES` work, `CUDA_DEVICE_ORDER` should also work directly.

Can you double-check the environment variable was correctly exported? Can you try this command and see if it makes a difference:

```
CUDA_DEVICE_ORDER=PCI_BUS_ID CT2_VERBOSE=1 python3 -c 'import faster_whisper; faster_whisper.WhisperModel("tiny")'
```

**Comment by Jeronymous** [comment]
okay, indeed I was setting the environment variable before launching the script, it works.
My error was to set the environment variable in the python script after having loaded faster_whisper/ctranslate2.

Thanks and sorry for the inconvenience
