### ISSUE TITLE
fine-tune

### ISSUE THREAD

**Issue by ILG2021** [guillaumekln/faster-whisper#152]
Can I fine-tune the model with CTranslate2 directly or I should fine-tune with openai whisper and then convert it by ctranslate2?

**Comment by guillaumekln** [comment]
You can fine tune with Hugging Face Transformers:

https://huggingface.co/blog/fine-tune-whisper

 and then convert the fine-tuned model to CTranslate2 as shown in the README:

https://github.com/guillaumekln/faster-whisper#model-conversion

**Comment by ILG2021** [comment]
Ok.
