### ISSUE TITLE
Expose some newly added parameters in Whisper

### ISSUE THREAD

**Issue by old9** [guillaumekln/faster-whisper#156]
Recently whisper added some new parameters `--highlight_words`, `--max_line_width` and `--max_line_count`, openai/whisper@43940fc9780cb91c4f94899755b4648e19d7b977 , these could be quite useful. Would it be possible to expose these parameters as well?

**Comment by guillaumekln** [comment]
These new parameters are used when saving the segments to file, which is currently not in the scope of the faster-whisper library. 

Maybe you can request these parameters in this CLI interface [whisper-ctranslate2](https://github.com/jordimas/whisper-ctranslate2) which is built on top of faster-whisper?

**Comment by sdugoten** [comment]
> These new parameters are used when saving the segments to file, which is currently not in the scope of the faster-whisper library.
> 
> Maybe you can request these parameters in this CLI interface [whisper-ctranslate2](https://github.com/jordimas/whisper-ctranslate2) which is built on top of faster-whisper?

I saw this is completed on their end, is this something that can be added here?

[https://github.com/Softcatala/whisper-ctranslate2/issues/24](url)
