### ISSUE TITLE
no output files.

### ISSUE THREAD

**Issue by tariq0101** [guillaumekln/faster-whisper#157]
Hi,
I've been using [whisper-ctranslate2 ](https://github.com/jordimas/whisper-ctranslate2/), it's a very great software and much faster than whisper but I'm experiencing a problem that other people have reported too.
faster-whiper isn't creating output files after successfully transcribing audio on GPU (CUDA), but it does create files when using CPU.
it sometimes create those files on GPU, it depends on the input files. but in my experience, more input files are failing that succeeding.

I'm on windows, python3.9, and have all the required dlls.

**Comment by tariq0101** [comment]
#https://github.com/jordimas/whisper-ctranslate2/issues/11

**Comment by guillaumekln** [comment]
Hi,

faster-whisper does not output file in any case, so it sounds more like an issue with the command line client your are using.
