### ISSUE TITLE
Can faster-whisper return the left/right mono channel?

### ISSUE THREAD

**Issue by junchen6072** [guillaumekln/faster-whisper#159]
Since faster-whisper seems always separate segments if not same channel, also can decode stereo to mono channels, I'm wondering if it's easy for faster-whisper to return which channel is for the segment?

**Comment by guillaumekln** [comment]
This Whisper model only works with mono audio and so it cannot return information about audio channels.

The different audio channels can only be split or merged before using the model.

**Comment by tkrafael** [comment]
I suppose you already have information of channel position (left, right). I does not make sense to delegate this to openai.
