### ISSUE TITLE
Can I use my amd gpu to run it? althougn the official pytorch does not support it on windows however

### ISSUE THREAD

**Issue by USR5** [guillaumekln/faster-whisper#162]
i saw a program like whisperer or whisper desktop, these two can use my amd gpu 5700xt, i  am new to programming, i wonder how they do this.
https://github.com/Const-me/Whisper
https://github.com/tigros/Whisperer

**Comment by guillaumekln** [comment]
No you cannot use an AMD GPU at this time. The backend library CTranslate2 only supports NVIDIA GPUs.

**Comment by USR5** [comment]
> No you cannot use an AMD GPU at this time. The backend library CTranslate2 only supports NVIDIA GPUs.不可以，您目前不能使用 AMD GPU。后端库 CTranslate2 仅支持 NVIDIA GPU。

can you see this two programs, amd gpu can work well by their programs.i can use my amd gpu 5700xt.
![WeChat Screenshot_20230419071530](https://user-images.githubusercontent.com/78246364/233095619-4874ccbc-8ff9-48b7-abcc-ee7bff2085a9.png)

**Comment by guillaumekln** [comment]
I know, but these programs only work on Windows.

You can refer to this issue to track AMD GPU support here: https://github.com/OpenNMT/CTranslate2/issues/1072. But honestly it will not happen in the near future.

**Comment by unclemusclez** [comment]
https://github.com/arlo-phoenix/CTranslate2-rocm

is this helpful for us plebs?
