### ISSUE TITLE
Transcription requires to be always with Internet connection

### ISSUE THREAD

**Issue by jordimas** [guillaumekln/faster-whisper#165]
Hello!

When you execute the first time the inference:

` model = WhisperModel("base")
`

It downloads the model size base and stores in the cache.

However, any call done later with the same method call requires an Internet connection working. If not, an exception is thrown:

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/guillaumekln/faster-whisper-base/revision/main (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f317b79bd30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))`

This happens because HuggingFace by default checks you local model against the remote.

This is not ideal in many scenarios. For example, if you are running a subtitles on-line service and for every inference it does an internet connection.

**Comment by palladium123** [comment]
See : [#116 ](https://github.com/guillaumekln/faster-whisper/issues/116). 

But I like your modification..
