### ISSUE TITLE
Integrate HF PeFT adapter models in cTranslate or faster-whisper

### ISSUE THREAD

**Issue by Jiltseb** [guillaumekln/faster-whisper#167]
@guillaumekln I am not sure if it is more apt for ctranslate2 but since the HF [Parameter efficient finetuning](https://github.com/openai/whisper/discussions/988) is also done for whisper for specific languages, I am posting it here.

HF whisper models are converted to ctranslate format. Is there a way of doing it with Peft-adapted models as well? They are also in a similar format and we should be able to combine them optionally at inference time. It is fine to alternatively first convert it into a single model in ctranslate and disable adapter to get the baseline whisper performance at the inference time. 

This will be really useful for those who want to use whisper+add performance improvements for specific languages.

**Comment by guillaumekln** [comment]
> It is fine to alternatively first convert it into a single model

I’m not a PEFT expert but it seems to me that you can already do this before running the conversion to CTranslate2.

See for example https://github.com/huggingface/peft/issues/308

**Comment by Jiltseb** [comment]
That is great! How should one disable the adapters after converting them into CTranslate2? In Peft models, you can do this by `with model.disable_adapter():`

**Comment by Jiltseb** [comment]
@guillaumekln Is there a way we can disable the finetuned weight matrices (or make it identity) in the final converted model at the run time in ctranslate? It is definitely an interesting way forward.
