### ISSUE TITLE
Is it possible to add audio context length parameter like in whisper.cpp

### ISSUE THREAD

**Issue by fquirin** [guillaumekln/faster-whisper#171]
I'm working mostly with very small files like 2-6s and what I noticed many times in Whisper is that transcription time is not linear. What I mean is that 3s and 6s files will be processed in almost the same time. I don't know the inner parts of Whisper well enough but I think this is related to the 30s window used to process chunks.

In whisper.cpp there is a parameter called `audio_ctx` that has been described here: https://github.com/ggerganov/whisper.cpp/issues/137

Do you think it might be possible to implement something similar in faster-whisper so that we can experiment with it and see if it reduces processing time for small files?

**Comment by guillaumekln** [comment]
The Whisper model requires a fixed 30-second window as input. It was trained like that so we have to do the same during inference. For now I don't plan on making this size configurable as it would probably degrade the transcription accuracy.

**Comment by guillaumekln** [comment]
> If I remember correctly for smaller files the rest is filled up with zeros.

The audio is filled with zero, but the log-Mel spectrogram and ultimately the encoder outputs are non-zero for these padding positions.

Maybe you can experiment with whisper.cpp and report here the impact on speed and accuracy (e.g. WER)?

**Comment by fquirin** [comment]
Unfortunately whisper.cpp has the audio_ctx only for streaming mode, so I can't test it on my reference WAV files, but here are some insights and experiences I could gain:
- Georgi himself said that ac `768` (ms) is probably the lower limit before accuracy starts to degrade considerably.
- In streaming mode, 768 is a mix of good results and lost words for me, probably because the context transfer from one window to the next isn't happening properly or data simply gets lost. For example counting from 1 to 10 will likely result in something like "1, 2, 3, 4, 6, 7, 8, 9". Some users claim that they don't have the same issue but I could never verify this.
- In the whisper.cpp community the 'ac' parameter is considered to increase speed considerably, but it is hard to test without being able to use it on WAV files and get some reproducible numbers. To me it "feels" faster as well.

Another quote by Georgi: `I reduced the audio context by half and the performance doubled. jfk.wav transcribed correctly!`

**Comment by juanmc2005** [comment]
Hello, I'm facing a similar issue. I'm willing to sacrifice a bit of accuracy for faster inference for streaming but this is currently not possible to configure.

From my experience there are no significant transcription differences when it comes to short segments (e.g. 3s-8s), although more noticeable at lower sizes than 768 if done without care. I actually found that adding a small padding of 50 typically improves accuracy without going to full 30s, probably related to what @guillaumekln said about non-zero mels for some padding positions.

In my case this is currently preventing me from using faster-whisper, although it is indeed much faster under the same conditions:

For a 5s audio chunk in French (CPU, Whisper small):

| library | audio_ctx | time |
| ------------- | ------------- | ------------- |
| faster-whisper (float32) | max | 1.7s |
| faster-whisper (int8) | max | 1.2s |
| whispercpp (pybind11, float32) | max | 3.8s |
| whispercpp (pybind11, float32) | 768 | 1.6s |
| whispercpp (pybind11, float32) | actual chunk size + 50 (= 300) | **0.7s** |

CPU: Intel Core i7 13700H

All the transcriptions from the table were pretty much equivalent, with a slight advantage to the last one (it got a few more words from the end and even corrected a substituted word).

It looks like inference time could be accelerated by 5x in these short segments with very similar performance!

**Comment by ammaraldirawi** [comment]
Hi Guillaume, 
great work you done here. could you please give some insights about the steps to be done to adjust the n_audio_ctx  in faster-whisper/ ctranslate2 to experiment with smaller audio chunks.

I managed to compile ctranslate2 and rewrite faster whisper in Rust to be ran on android aarch64.
now my challenge is to lower the competition usage and time to an acceptable measure.
Currently I am using a custom trained small whisper 8bit model as it is the smaller size with acceptable results for Arabic language.

currently it needs about 5 minutes to transcribe 1 minute so it is a long way from being  acceptable from user experience.
As it is mentioned here and in whisper.cpp there is some promising results from lowering the chunk size, so  I am thinking of lowering it to sizes smaller than 30 secs and start returning the data before completion already so the user can already work on it and let the process continue the background. 

I tried to find the equivalent places that you mentioned above in Ctranslate2 /faster-whisper but it seems much harder to achieve.
the only Thing that I could find which i think is relevant is 
 chunk_length=30,
https://github.com/guillaumekln/faster-whisper/blob/master/faster_whisper/feature_extractor.py#L11
which should be the length of the clip,  but I couldn't find any place in ctranslate2 where n_audio_ctx is used.
so I was hopping that you could direct me to the places where this should be changes.
thanks a lot

**Comment by guillaumekln** [comment]
Here's the value corresponding to `n_audio_ctx` in CTranslate2:

https://github.com/OpenNMT/CTranslate2/blob/61d34502325bfa3c5ef8a11cd2e391d0efed1bf9/include/ctranslate2/layers/whisper.h#L23

The current value is 1500.

In faster-whisper you should also change the following values which assume a default `n_audio_ctx`:

https://github.com/guillaumekln/faster-whisper/blob/1562b02345c8587eff1c6694b28c7f91f5c20ec2/faster_whisper/transcribe.py#L151-L152

See the actual formula in openai/whisper:

https://github.com/openai/whisper/blob/e8622f9afc4eba139bf796c210f5c01081000472/whisper/transcribe.py#L188-L193

**Comment by ammaraldirawi** [comment]
Thank you for your response and giving me the solution. I was able to split the values in half i.e chunk size 15 sec, input_stride 1, time_precision 0.01  and managed to make it work.
I tested transcribing on some different scenarios and there are some promising results.
it seems when the clips are short clips(I tried 10sec, 6sec) there is almost no noticeable difference in the resulted text.
when I use longer clips ( I tried 2 clips with 1 min) I start to get some hallucination in the end off each segment.
I think this should be solved by introducing some padding to the end of each segment which as far as my understanding should give some space for the The log Mel-spectrograms. if that didn't work maybe I try to split the clip into chunks less than 15 secs and feed the prompt to the next transcribe.
Finally, to make a compression, I gathered one result for transcribing a 10 secs clip with beam size 1  on whisper small 8bit
30 secs chunk size: 46 secs to transcribe
15 secs chunk size: 22 secs to transcribe
so it indeed took half of the time to process.
so for the case when we need a more responsive processing on low resources devices, I think lower the chunk size could make sense.

**Comment by Lorenzoncina** [comment]
@ammaraldirawi Hello Ammaral
I'm in a similar situation, after having finetuned whisper with a dataset made by 10-15 seconds long audio file, the fine tuned model can transcribe well only with chunk lenght 10-15 sec. If  I leave 30 seconds the output is full of deletion errors.
I managed tto reduce the chunk size to 15 second on Huggin face API, but I'm struggeling to fo the same on faster whisper. Could you please highlight the modifications you did to achive this result both on faster whisper and ctraslate 2?

**Comment by ammaraldirawi** [comment]
> @ammaraldirawi Hello Ammaral I'm in a similar situation, after having finetuned whisper with a dataset made by 10-15 seconds long audio file, the fine tuned model can transcribe well only with chunk lenght 10-15 sec. If I leave 30 seconds the output is full of deletion errors. I managed tto reduce the chunk size to 15 second on Huggin face API, but I'm struggeling to fo the same on faster whisper. Could you please highlight the modifications you did to achive this result both on faster whisper and ctraslate 2?

What worked for me is to divide the suggested values by 2 to i.e. 
https://github.com/OpenNMT/CTranslate2/blob/61d34502325bfa3c5ef8a11cd2e391d0efed1bf9/include/ctranslate2/layers/whisper.h#L23
    dim_t output_time() const {
        return _position_embedding.num_positions()/2;
      }
https://github.com/guillaumekln/faster-whisper/blob/1562b02345c8587eff1c6694b28c7f91f5c20ec2/faster_whisper/transcribe.py#L151-L152
        self.input_stride = 1
        self.time_precision = 0.01
https://github.com/guillaumekln/faster-whisper/blob/1562b02345c8587eff1c6694b28c7f91f5c20ec2/faster_whisper/feature_extractor.py#L11
        chunk_length=15,
only these changes were enough to make it work, but I still have the issue that it start hallucinate with clips almost 15secs  or longer. 
what I will try next is to cut the clips into something less than 15sec chunks and check if that solves the issue.
what is also worth mention is that I had to convert the python code to rust. but it is 1 on 1 conversion

**Comment by Lorenzoncina** [comment]
Thanks, I managed to modify the chunck lenght to 15 seconds with these modifications!

**Comment by guillaumekln** [comment]
The latest version of CTranslate2 (3.19.0) relaxed the shape requirements for Whisper inputs which can now be shorter than 30 seconds. It should no longer be needed to change and recompile the CTranslate2 code to make it work.

I also mentioned above to update `input_stride` and `time_precision`, but these values are actually unchanged when reducing the audio context: the input stride is always 2 because the Whisper encoder always divides the audio context length by 2.

So now you only need to change `chunk_length` in `feature_extractor.py`.

**Comment by Lorenzoncina** [comment]
Thank you very much Guillaume for ths upgrade! I can now run inference with my finetuned model with chunk_lenght =15 altough I still see some imperfectios expecially at segments boundaries.

**Comment by ammaraldirawi** [comment]
thanks Guillaume for the change. it made experimenting much faster.
In my case the minimum value I could set for chunk_length and still getting decent result is 7  and then splitting the audio file in max 5 secs and lowering the beam into 2.
any values lower than that will produce a lot of hallucination and deletion.

**Comment by thiswillbeyourgithub** [comment]
Hi, for your information [FUTO.org](https://www.futo.org/about/what-is-futo/) did a finetuning of whisper that can work with [arbitrarily less audio than 30s](https://github.com/futo-org/whisper-acft) and made it handy to use on smartphones via [their android keyboard app](https://github.com/futo-org/android-keyboard/releases). I [don't think it is yet using quantization NOR faster-whisper NOR v3 turbo models so I opened this issue to ask if it's planned](https://github.com/futo-org/whisper-acft/issues/9).

They put their code in a notebook on their repo so if anyone is interested in contributing I think it might be a high value contribution as the current models are already awesome on smartphones, even medium powered one! But of course they could benefit from faster inference or more compact size.

I **think** that the main dev doing this at futo has more expertise on keyboard apps and android developpments in general than ML / sound processing so this could be a real help (although I might be wrong about his skills!)


Related: #456 and #428
