### ISSUE TITLE
Same model configuration produces relatively consistent transcripts across runs, but different across 2 different ways of running

### ISSUE THREAD

**Issue by mlfetan** [guillaumekln/faster-whisper#177]
While using large-v2 model, the following situation arises:

1. Transcribing an input audio file from a script that only contains the model initialization, transcribe call and print produces a certain transcript A
2. Using the same model and the same parameter configuration from another,more complex script that only launches Whisper transcription corresponding script as a subprocess using os.system, the result is transcript B, quite different from transcript A.
3. Repeated runs of approach 1 produce transcript A consistently (similarly for approach 2, where transcript B is repeated).
4. The parameters are set to the default values

I understand that the decoding that happens by default introduces a certain degree of uncertainty but I would have expected different outputs across runs of the same approach,not between 1. and 2.

**Comment by guillaumekln** [comment]
Based on your information, it seems we can exclude the "temperature fallback" which would always produce different results.

> The parameters are set to the default values

Does it include the parameters of the `WhisperModel` constructor?

Note that the constructor has a default parameter `device="auto"` to automatically load on GPU if a GPU is visible to the process. Is it possible that the model is running on GPU in one approach and on CPU in the other? This could happen if the complex script changes the GPU visibility.

**Comment by mlfetan** [comment]
Yes, including the constructor parameters. It is 100% the same device

**Comment by guillaumekln** [comment]
Can you try to provide a way to reproduce the issue?

**Comment by mlfetan** [comment]
The issue is solved. I cannot fully explain what was happening but, after removing an import statement and a function that was using language detection capability before the main transcription flow, the 2 approaches now have matching results
