### ISSUE TITLE
same audio file meets different results

### ISSUE THREAD

**Issue by apoca909** [guillaumekln/faster-whisper#178]
test wav:[test.wav.zip](https://github.com/guillaumekln/faster-whisper/files/11322096/test.wav.zip)

```
from faster_whisper import WhisperModel
model=WhisperModel('small', device='cuda', device_index=0, compute_type="int8_float16")
segs, info = model.transcribe('test.wav', language='th')
text = ''.join([ s.text for s in segs])
```
run the transcribe with same input args repeatedly, the result maybe different, the issue happens when using  large-v2 model too.

**Comment by guillaumekln** [comment]
See #76.
