### ISSUE TITLE
Segmentation fault on Mac M1 during conversion

### ISSUE THREAD

**Issue by deusdeorum0** [guillaumekln/faster-whisper#18]
I have been unable to convert the model
Regardless of whether I have tried with or without quantization, or different models - unfortunately, I have had no success.

`192:faster-whisper$ ct2-transformers-converter --model openai/whisper-small --output_dir output`
`Segmentation fault: 11`

`192:faster-whisper$ ct2-transformers-converter --model openai/whisper-tiny --output_dir output`
`Segmentation fault: 11`

`192:faster-whisper$ ct2-transformers-converter --model openai/whisper-tiny.en --output_dir output
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.92k/1.92k [00:00<00:00, 486kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 151M/151M [00:04<00:00, 37.2MB/s]
Segmentation fault: 11
192:faster-whisper$ /usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '`
^^ this one just freezes

`192:faster-whisper$ ct2-transformers-converter --model openai/whisper-tiny --output_dir output --quantization float16`
`Segmentation fault: 11`

`192:faster-whisper$ ct2-transformers-converter --model openai/whisper-small --output_dir output --quantization float16`
`Segmentation fault: 11`

`192:faster-whisper$ ct2-transformers-converter --model openai/whisper-tiny.en --output_dir output --quantization float16`
`Segmentation fault: 11`

**Comment by guillaumekln** [comment]
How did you install the library? Can you try clearing your Python environment and reinstalling again?

**Comment by deusdeorum0** [comment]
Oops.
I installed with venv and everything worked just fine.
Sorry to have bothered you!

**Comment by shahzebali42** [comment]
Working in a new venv is not working fine for me 

I am getting the following error while converting my local huggingface whisper model

`zsh: segmentation fault  ct2-transformers-converter --model  --output_dir  --copy_files tokenizer.json``
