### ISSUE TITLE
Lower the host memory footprint?

### ISSUE THREAD

**Issue by daxaxelrod** [guillaumekln/faster-whisper#189]
Running a the small model only takes up about 1.32gb on my GPU but 2.7gb on my host machines's normal memory. Any thoughts on how to reduce normal memory footprint?

Thanks!

**Comment by guillaumekln** [comment]
As far as I know most of the host memory is reserved by the cuDNN and cuBLAS libraries. At least that's what I observed in the past.

So there is no easy way to reduce the memory usage at this time.
