### ISSUE TITLE
Where to put the model.bin and related files if I don't wanna them into C: disk?

### ISSUE THREAD

**Issue by pendave** [guillaumekln/faster-whisper#196]
https://huggingface.co/guillaumekln/faster-whisper-large-v2/tree/main

How should I set up these files if I don't want to put them on disk C? Who knows? 
faster-whisper-large-v2

![$EI}9FNQZCA_LRB~AEQ}3QT](https://user-images.githubusercontent.com/1331881/235278187-dba47c83-3bba-4d5f-bead-8bb2e9a0498e.png)

![V2Y 260VA)J7P_9QNVM2@)M](https://user-images.githubusercontent.com/1331881/235278186-2b80d8eb-69b9-4f7e-9938-4d290b92b8d3.png)

**Comment by junchen6072** [comment]
transcribe has option download_root
