### ISSUE TITLE
help! I run fast-whisper more times and get much different result

### ISSUE THREAD

**Issue by wjc1989** [guillaumekln/faster-whisper#202]
I run one same video with fast-whisper more times get much different results, sometimes it give me no result.
my code:

import uvicorn
import wget
import uuid
import os
from fastapi import FastAPI
from faster_whisper import WhisperModel
import whisper

app = FastAPI()

model_size = "large-v2"
model = WhisperModel(model_size, device="cuda", compute_type="float16")

@app.get("/stt")
async def stt(wavpath: str, language: str):
    file_name =str(uuid.uuid1()) + '.wav'
    wget.download(wavpath,file_name)
    print('\nwavfile:',file_name)
    taskStr='translate'
    segments, info = model.transcribe(file_name,vad_filter=True,language=language,task=taskStr,condition_on_previous_text=False, vad_parameters=dict(min_silence_duration_ms=5000))
    print("Detected language '%s' with probability %f" % (info.language, info.language_probability))
    segments = [segment._asdict() for segment in segments]
    print(segments)
    os.remove(file_name)

    return segments

**Comment by guillaumekln** [comment]
See #76.
