### ISSUE TITLE
Run on Google Coral Accelerator

### ISSUE THREAD

**Issue by jhbruhn** [guillaumekln/faster-whisper#203]
To improve the performance on devices like a Raspberry Pi, would it be possible to run the model on an accelerator like the Google Coral device?

**Comment by guillaumekln** [comment]
No, it is not possible and I’m pretty sure it will not happen in the future for this project.

You can checkout this TensorFlow Lite implementation which is probably the best candidate to run on Coral:

https://github.com/usefulsensors/openai-whisper
