### ISSUE TITLE
Transcription Issue: Numpy Array Returns Blank Output while WAV File Works Correctly

### ISSUE THREAD

**Issue by harshkumarchourasia** [guillaumekln/faster-whisper#204]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/58362904/236295178-459d1bdd-1910-4d44-be06-4e124b52ff62.png">
I recently encountered an issue with the faster_whisper repository where using a Numpy array for transcription results in a blank output, whereas using a WAV file provides the correct transcription.

Am I using the function as intended?

**Comment by SBFallout** [comment]
I got trouble for this for latest version. Colab crash for out of RAM even 10 seconds audio clips. How do you solve this problem?
