### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by wwfcnu** [guillaumekln/faster-whisper#206]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/guillaumekln/faster-whisper-large-v2/revision/main (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e915670a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by Riiicc** [comment]
I have this problem too, it doesn't work on the gpu server, then I get the same error on my local computer

**Comment by Riiicc** [comment]
I solved the problem by downloading the model locally, then specifying the model file location
`model = WhisperModel('/home/momo1/faster-model/', device="cpu", compute_type="int8")`

**Comment by wwfcnu** [comment]
it work，thanks



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 05/08/2023 11:47 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [guillaumekln/faster-whisper] requests.exceptions.ConnectionError (Issue #206) |

I solved the problem by downloading the model locally, then specifying the model file location
model = WhisperModel('/home/momo1/faster-model/', device="cpu", compute_type="int8")

**Comment by guillaumekln** [comment]
See also #116.
