### ISSUE TITLE
Can I convert a model to ctranslate2 which is using PEFT-Lora + BNB INT8 training?

### ISSUE THREAD

**Issue by ILG2021** [guillaumekln/faster-whisper#208]
The train method is as below:
https://github.com/huggingface/peft/blob/main/examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb

**Comment by etlweather** [comment]
@ILG2021 You closed this - how did you do the conversion?

**Comment by ILG2021** [comment]
> @ILG2021 You closed this - how did you do the conversion?
https://github.com/yeyupiaoling/Whisper-Finetune/blob/master/README_en.md

**Comment by etlweather** [comment]
Thanks a million @ILG2021 - while I have to do more tests, your code helped me sort this out.
