### ISSUE TITLE
CUDA out of memory error when iterating on segments

### ISSUE THREAD

**Issue by tusharagarwal25** [guillaumekln/faster-whisper#211]
Hi @guillaumekln ,

I am trying out the code that you have shared and facing some trouble when iterating over the segments.

Getting a cuda out of memory error after a few iterations.

May I know what is the cause of this and how it can be fixed?

Since it is able to iterate over a few segments, are those segments occupying GPU memory? Can that be cleared?
<img width="804" alt="Screenshot 2023-05-08 at 5 22 51 PM" src="https://user-images.githubusercontent.com/12660586/236816977-7f86f62f-dc2f-4c93-87e0-83716467fa65.png">

**Comment by guillaumekln** [comment]
> Since it is able to iterate over a few segments, are those segments occupying GPU memory?

In some ways, yes. The previous text segments are used to condition the generation of the current segment, which does increase the memory usage.

> Can that be cleared?

You can try setting `condition_on_previous_text=False`.

**Comment by ILG2021** [comment]
compute_type = int8 will only cost 2-3G memory for large-v2. then float32 will cost 6 -7G

**Comment by sye98** [comment]
Hey, may I ask if there is a way to solve this problem once for all? Is there a way to start where it left off (exited with error)? Assuming condition_on_previous_text=True. Thank you!
