### ISSUE TITLE
504 when trying to download the model

### ISSUE THREAD

**Issue by vsmaxim** [guillaumekln/faster-whisper#212]
Hello everyone, I'm pretty sure that the issue is not on your side, but just to confirm because I see some other models downloading from hf-hub with no issues.

This is what I have on my local instance:
```
504 Server Error: Gateway Time-out for url: https://huggingface.co/api/models/guillaumekln/faster-whisper-medium/revision/main
```

This is what I have in a GPU cluster:
```
504 Server Error: Gateway Time-out for url: https://huggingface.co/api/models/guillaumekln/faster-whisper-large-v2/revision/main
```

I have checked the [hf status page](https://status.huggingface.co/) (along with twitter) and there's no sign they have downtime right now. Any clarifications (or workarounds) are highly appreciated!

**Comment by guillaumekln** [comment]
I think HF is down or in maintenance. Their main website is returning a 502 Bad Gateway: https://huggingface.co/

**Comment by guillaumekln** [comment]
https://twitter.com/huggingface/status/1655885897961811971

**Comment by vsmaxim** [comment]
Okay, so I think it's worth closing this issue (as it's on hf side).
