### ISSUE TITLE
Error in loading model from hugging face

### ISSUE THREAD

**Issue by tusharagarwal25** [guillaumekln/faster-whisper#213]
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/guillaumekln/faster-whisper-large-v2/revision/main

Getting this error repeatedly. Sometimes it works, but getting this very frequently. What is the work around for this?
@guillaumekln

**Comment by guillaumekln** [comment]
There is an on-going issue with the Hugging Face Hub where the models are stored: https://status.huggingface.co/. See also #212.

If the model is already in the cache, you can set `local_files_only=True` to prevent making a request to the HF hub.

```python
model = WhisperModel("large-v2", local_files_only=True)
```

**Comment by yamete0** [comment]
same thing for me

**Comment by guillaumekln** [comment]
@daxaxelrod This change looks useful. Can you send a PR with that? Just put `allow_patterns` and `tqdm_class` in the `kwargs` dictionary to avoid duplication.

**Comment by tonygauderman** [comment]
Does it need to be that particular about which exception is returned before falling back to local?  This fixes the error we were seeing this morning, but it wouldn't fix other issues that might  lead to failure.  Invalid certificate, DNS failure, server doesn't respond at all, etc.

**Comment by guillaumekln** [comment]
We don’t want to catch all exceptions here. For now this change is fine and we can refine it later when we find more related exceptions. It’s likely that some of the possible errors you mentioned are already included in `HfHubHTTPError`.

I’m closing this issue since HF seems to work again.

**Comment by myhd** [comment]
Due to Hugging Face Hub downtime today, my script stopped working.
I added local_files_only=True to the model initialization, like

`model = WhisperModel(model_size, device="cpu", compute_type="int8", local_files_only=True)`

Generally I dislike it does a version on every run. Perhaps just once a week?

**Comment by guillaumekln** [comment]
> Due to Hugging Face Hub downtime today, my script stopped working.

Are you still using an older version of faster-whisper? In recent versions connection errors to Hugging Face are ignored if the model is already downloaded locally.
