### ISSUE TITLE
Output folder and output format from python?

### ISSUE THREAD

**Issue by Strider3000** [guillaumekln/faster-whisper#214]
Is there a way specify an output folder and format from python for faster-whisper?

Whisper could support output format/directory in the following way:

```
from whisper.utils import get_writer

result = model.transcribe(the_file, ... )
srt_writer = get_writer("srt", path)
srt_writer(result, path)
txt_writer = get_writer("txt", path)
txt_writer(result, path)
```

Same question for the command-line - can we specify an output format of .txt or .srt? Thanks

**Comment by guillaumekln** [comment]
Saving the results to a file is currently not in the scope of this library.

You can check out https://github.com/Softcatala/whisper-ctranslate2 which is a command line tool built on top of faster-whisper.

**Comment by Strider3000** [comment]
Wonderful, ctranslate2 is perfect.
