### ISSUE TITLE
horrible speeds on 4090 vs 3090

### ISSUE THREAD

**Issue by Zachary-Hamel** [guillaumekln/faster-whisper#217]
So on a 3090 it takes me 1 minute for a 26 minute video and my gpu is always at 100% usage during that time. But when I switched over to the 4090 I cannot get more than 45% usage (usually just goes up and down from 20%-45%) for no reason and takes over 2 minutes for the same video. Same code, same docker image.... Any idea why its happening? I attached a screenshot of what nvtop shows for the 4090. Any idea why its so crappy on the 4090 vs 3090. Using default settings on everything, and again same docker image, same OS.... 

![image](https://github.com/guillaumekln/faster-whisper/assets/40673690/ffef4619-a923-4fe0-a1ca-faa4d07633ba)

**Comment by guillaumekln** [comment]
Hi,

What CUDA version is installed in the Docker image?

**Comment by Zachary-Hamel** [comment]
Using this image

FROM nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04

**Comment by Zachary-Hamel** [comment]
Just tried it and did 5 warmups. Still get same effects. Super confused. This isn't happening on my 3090 at all. And the 4090 temps are more than perfect.

![image](https://github.com/guillaumekln/faster-whisper/assets/40673690/306c14c1-e023-4518-9301-e6fac721295c)

**Comment by palladium123** [comment]
Looks like it has been reported elsewhere: 

[here](https://discuss.pytorch.org/t/4090-25-slower-than-3090-for-pytorch-transformers/168278)

and

[here](https://forums.developer.nvidia.com/t/tensorrt-inference-runs-slower-in-rtx4090-than-rtx-3090-ti/238486)

The first link seem to suggest a potential power bottleneck in some platforms under very specific circumstances. May be worth checking if that is the cause in your case.

**Comment by Zachary-Hamel** [comment]
That shouldn't be the issue, any other inferencing works just fine.. Its only happening with this library for some reason

**Comment by guillaumekln** [comment]
Did you just swap the GPU in the same machine or is it a different machine? What's the CPU?

I'm not sure what's happening. Hopefully other 4090 users can share their experience here.

**Comment by Zachary-Hamel** [comment]
Different machine, but any other model works fine (GPT-J, NeoX, normal whisper) on all machines. Its threadripper as the cpu

**Comment by msj121** [comment]
@zachNA2 Out of curiosity do you know a general speed difference for transcription for 4090 vs 3090? Like how long did 4090 take after fix?
