### ISSUE TITLE
decode_audio error

### ISSUE THREAD

**Issue by Latrolage** [guillaumekln/faster-whisper#22]
```
❯ python3 transcribe.py
Traceback (most recent call last):
  File "/home/user/git/faster-whisper/transcribe.py", line 13, in <module>
    segments, info = model.transcribe("audio.opus", beam_size=5)
  File "/home/user/git/faster-whisper/faster_whisper/transcribe.py", line 156, in transcribe
    audio = decode_audio(
  File "/home/user/git/faster-whisper/faster_whisper/audio.py", line 27, in decode_audio
    fifo.write(new_frame)
  File "av/audio/fifo.pyx", line 25, in av.audio.fifo.AudioFifo.write
  File "av/audio/fifo.pyx", line 90, in av.audio.fifo.AudioFifo.write
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument
```
target file is an opus file. Is mp3 the only supported filetype? what codecs should the file be?

edit: it seems to work on smaller/shorter files. The one with the error is a ~12 hour video I wanted to test on.

**Comment by guillaumekln** [comment]
We use [PyAV](https://github.com/PyAV-Org/PyAV) for the audio decoding which is based on FFmpeg, so it virtually supports all audio codecs.

I'm not sure this error is related to the file duration. Is it possible for you to share this input file (or any other file that triggers this error)?

There is a similar error reported here https://github.com/PyAV-Org/PyAV/issues/1048 which seems to happen when the audio sampling rate is changing.

**Comment by Latrolage** [comment]
> Is it possible for you to share this input file

I downloaded it from youtube `yt-dlp -x -f bestaudio "https://youtu.be/P4xuSCEjD5Q" -o "audio.%(ext)s"`

just running `ffmpeg -i audio.opus audio.mp3` to re-encode it to `lame` stops the error from happening. using `--format-sort acodec:m4a ` to download the m4a from youtube also works.

I'll close the issue since it seems that it's an issue in PyAV
