### ISSUE TITLE
How to add tokenizer of fine-tune whisper model for converting of ctranslater2

### ISSUE THREAD

**Issue by ILG2021** [guillaumekln/faster-whisper#220]
Hello, everyone, I have fine-tune a whisper model by the methond of this:
https://huggingface.co/blog/fine-tune-whisper

But my model can not be converted to ctranslate2. It seems lacks tokenizer. But the tutorial doesn't reference it. So anyone know how to solve it? This is my model.
![image](https://github.com/guillaumekln/faster-whisper/assets/93691919/45f650e7-6a82-409f-b87e-68225f3bc359)

**Comment by funboarder13920** [comment]
You need to add vocab.json, tokenizer.json, special_token_map.json and merges.txt in the checkpoint folder that you want to convert.

You should be able to find them here : https://huggingface.co/openai/whisper-large/tree/main
