### ISSUE TITLE
token quality score

### ISSUE THREAD

**Issue by slavaGanzin** [guillaumekln/faster-whisper#232]
Hi, @guillaumekln. Thanks for your work.

Ctranslate has a feature of [printing colored output](https://github.com/Softcatala/whisper-ctranslate2#print-colors) describing quality of transcribing separate tokens, which was inspired by whisper.cpp. While your library is more about API, it will be convenient to have this scores in segments next to tokens array.

Do you plan to add this functionality?

Thanks again

**Comment by guillaumekln** [comment]
Hi,

Try using `word_timestamps=True`. The returned words will include a probability value.

https://github.com/guillaumekln/faster-whisper#word-level-timestamps

**Comment by slavaGanzin** [comment]
@guillaumekln Thanks for pointing out, missed this somehow.
