### ISSUE TITLE
Feature Request: Get version at runtime

### ISSUE THREAD

**Issue by natecarlson** [guillaumekln/faster-whisper#236]
I think it's useful to include the version number of the transcription engine with transcription results for future reference.. it would be great to implement __version__ (PEP 8, PEP 396) and/or a .version module.

It would also possibly be useful to expose the imported model name and compute_type - however, that's easy enough to handle in the consumer code!

**Comment by natecarlson** [comment]
If the package was installed properly and you are on a recent version of Python, it is possible to get the version like:
```
>>> from importlib.metadata import version
>>> version('faster-whisper')
'0.5.1'
```

**Comment by guillaumekln** [comment]
Do you want to contribute adding the version number in the module?

We can do the same as the CTranslate2 library:

1. Add a new `version.py` file: https://github.com/OpenNMT/CTranslate2/blob/v3.13.0/python/ctranslate2/version.py
2. Export `__version__` at the module level: https://github.com/OpenNMT/CTranslate2/blob/v3.13.0/python/ctranslate2/__init__.py#L51
3. Read the version file in `setup.py`: https://github.com/OpenNMT/CTranslate2/blob/v3.13.0/python/setup.py#L69

**Comment by natecarlson** [comment]
Oh great, thank you! It was on my to-do list,  but hadn't gotten there yet.
