### ISSUE TITLE
No SGEMM backend on CPU, RUY Backend on Android Termux

### ISSUE THREAD

**Issue by wioneo** [guillaumekln/faster-whisper#237]
When I run faster-whisper via Termux on Android 9.0, I get the following error...

> terminating with uncaught exception of type std::runtime_error: No SGEMM backend on CPU
> terminating with uncaught exception of type std::runtime_error: No SGEMM backend on CPU
> terminating with uncaught exception of type std::runtime_error: No SGEMM backend on CPU
> terminating with uncaught exception of type std::runtime_error: No SGEMM backend on CPU

The number of errors changes based on the number of threads that I run it with.

Notably, I built CTranslate2 with these commands...

```
cmake -DWITH_MKL=OFF -DWITH_CUDA=OFF -DOPENMP_RUNTIME=NONE -DWITH_RUY=ON  -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr ..
make -j$(nproc) && make install
cd .. && cd python
python setup.py bdist_wheel
pip install dist/*.whl
```

I also modified src/thread_pool.cc line 89 by replacing "pthread_setaffinity_np" with "sched_setaffinity".

Any idea what might cause this?

If it's useful, the full test code in Python is below...

```
from faster_whisper import WhisperModel
import time

base_dir = "faster.whisper"
model_size = "tiny.en"
input_file = f"{base_dir}/gb0.wav"
num_threads = 4
quant_str = "auto"

start = time.time()

# run on CPU
model = WhisperModel(model_size, device="cpu", cpu_threads=num_threads, download_root=base_dir, compute_type=quant_str)

segments, info = model.transcribe(input_file, beam_size=5)

for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
    
print(f'\nTime: {(time.time() - start):.2f} seconds\nModel: {model_size}\nThreads: {num_threads}\nQuantization: {quant_str}\n')
```

**Comment by guillaumekln** [comment]
You should also compile with `-DWITH_OPENBLAS=ON` to provide a single precision GEMM implementation (Ruy only implements 8-bit GEMM).

**Comment by wioneo** [comment]
Good to know. I changed it to...

`cmake -DWITH_MKL=OFF -DWITH_CUDA=OFF -DOPENMP_RUNTIME=NONE -DWITH_RUY=ON -DWITH_OPENBLAS=ON -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr ..`

...But then I get the error...

> CMake Error at CMakeLists.txt:380 (message):
>   OpenBLAS include directory not found

...So I tried...

`cmake -DWITH_MKL=OFF -DWITH_CUDA=OFF -DOPENMP_RUNTIME=NONE -DWITH_RUY=ON -DWITH_OPENBLAS=ON -DOpenBLAS_INCLUDE_DIR=/data/data/com.termux/files/usr/include/openblas -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr ..`

... but still get the same error.

_Then_ I tried to modify line 376 of CMakeLists.txt to...

`find_path(OPENBLAS_INCLUDE_DIR NAMES /data/data/com.termux/files/usr/include/openblas/cblas.h)`

... and _still_ get the same error. I'm not sure what the issue is there. I confirmed that cblas.h exists in the expected location with...

`cat /data/data/com.termux/files/usr/include/openblas/cblas.h`

... which printed out the expected file contents. I imagine this has something to do with how the Android/Termux file system works. Any recommendations?

**Comment by guillaumekln** [comment]
Can you try using `-DCMAKE_PREFIX_PATH=/data/data/com.termux/files/usr` instead of `-DOpenBLAS_INCLUDE_DIR`?

**Comment by wioneo** [comment]
Unfortunately that brings back the same error. In all honesty modifying CMakeLists.txt is not too difficulty.

**Comment by guillaumekln** [comment]
Probably there is a way to correctly configure the path from the CMake command line but I have not look into it. I'm closing this issue for now since you managed to compile at the end.
