### ISSUE TITLE
if model path include Chinese characters , load model will report error

### ISSUE THREAD

**Issue by iorilu** [guillaumekln/faster-whisper#238]
model_path = 'data\\测试\\small'

i ran debug , and find it's error from ctranslate2, I think maybe it's because it's writen in c, so not support non-english path
    self.model = ctranslate2.models.Whisper(
RuntimeError: Unable to open file 'model.bin' in model 'data\测试\small'

**Comment by guillaumekln** [comment]
What's the content of the directory "data\测试\small"?

**Comment by iorilu** [comment]
small means a folder with all 4 files
for small model

i  use this example just to show the problem

if whole path has no chinese directory,then all will work

**Comment by iorilu** [comment]
if i put small model folder just under data folder,then no problem

but if model path can't has chinese characters,then i am not able to write applicantion for Chinese language environment，because people often install software under Chinese folder。 

i  am writing an app now

**Comment by iorilu** [comment]
if i put small model folder just under data folder,then no problem

but if model path can't has chinese characters,then i am not able to write applicantion for Chinese language environment，because people often install software under Chinese folder。 

i  am writing an app now****

**Comment by iorilu** [comment]
here is an example

below is the full path to model, small folder contains all files for small model

if path like this , then load model will report error

D:\dev\myapp\data\测试\small

<img width="403" alt="Snipaste_2023-05-15_20-31-47" src="https://github.com/guillaumekln/faster-whisper/assets/2059858/a3fc637b-f2f7-4cc2-bebd-e8de72fbabd4">

**Comment by guillaumekln** [comment]
Yes, it's an issue on Windows. This PR in CTranslate2 should fix this: https://github.com/OpenNMT/CTranslate2/pull/1227

**Comment by iorilu** [comment]
> Yes, it's an issue on Windows. This PR in CTranslate2 should fix this: [OpenNMT/CTranslate2#1227](https://github.com/OpenNMT/CTranslate2/pull/1227)

thanks a lot ,  I will check it out ,and rebuild my code

**Comment by guillaumekln** [comment]
It should be fixed in `ctranslate2>=3.14.0`. Let me know if it's not the case.
