### ISSUE TITLE
Some random cuda error when another ML is being used

### ISSUE THREAD

**Issue by Zachary-Hamel** [guillaumekln/faster-whisper#242]
Hello,
Whenever I try to use TTS (from coqui) and whisper together I get the following error:

`Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory`

They are not being called at the same time, the order is whisper then tts, but if I have the TTS package there or any other model loaded, I get that error when running faster-whisper. Any way to shut down/block other services so whisper can run and then let the other libraries do there thing?

To clarify. If I use faster-whisper by itself, no other libs then it works just fine so its definently installed. And no im not running out of memory.

**Comment by guillaumekln** [comment]
Hi,

How to reproduce this error? I tried running TTS and faster-whisper in the same script but that seemed to work:


```python
from TTS.api import TTS
import faster_whisper

model_name = TTS.list_models()[0]
tts = TTS(model_name, gpu=True)
wav = tts.tts("This is a test! This is also a test!!", speaker=tts.speakers[0], language=tts.languages[0])

model = faster_whisper.WhisperModel("tiny", device="cuda")
segments, _ = model.transcribe("tests/data/jfk.flac")
segments = list(segments)
print(segments)
```

**Comment by guillaumekln** [comment]
Feel free to reopen if you can share a way to reproduce the error.
