### ISSUE TITLE
Support for specifying language and diarization

### ISSUE THREAD

**Issue by gvijqb** [guillaumekln/faster-whisper#245]
Hi Team,

Really impressive project. It is really very good in terms of speed improvements and we have even added it as part of one of the APIs on our platform: https://monsterapi.ai/speech-to-text-api

I wanted to ask if there is support available for these 2 features in the project or how we can incorporate them:

- Diarization for speaker identification
- Language specification (we use whisper large-v2 and would like to specify the language for transcription)

**Comment by junchen6072** [comment]
transcribe api should allow you to specify language?

**Comment by gvijqb** [comment]
@junchen6072 I don't see that option in the transcribe.py file

**Comment by gvijqb** [comment]
@junchen6072 figured out the language for translation. But exploring on diarization as well. Any way we can integrate speaker identification with this project?

**Comment by phineas-pta** [comment]
there're already many threads about diarization on openai whisper, you can inspire from there

**Comment by phineas-pta** [comment]
https://github.com/m-bain/whisperX

**Comment by phineas-pta** [comment]
https://github.com/m-bain/whisperX

https://github.com/MahmoudAshraf97/whisper-diarization

**Comment by guillaumekln** [comment]
> figured out the language for translation.

Note that Whisper can only translate to English. The language argument that you can set in the method `transcribe` is the language of the audio. Then you can set `task="transcribe"` to transcribe in the same language, or `task="translate"` to translate to English.

**Comment by 01Ashish** [comment]
should the language of transcribed speech and speaker diarization output be same ?

I have used task='translate' parameter in faster whisper to translate the hindi english mix speech and I got the transcription output in english language.

Now i want to perform speaker diarization. So the audio i will be sending in speaker diarization functions should the language of it and the transcription be same. As my transcription is in english and my original audio is in hindi english mix.

I am trying with nvidia nemo diarizer - https://github.com/MahmoudAshraf97/whisper-diarization
I need to know. would it work.
Ultimately I want diarized text in english language from hindi english mix speech.  

How can i complete this task.
or if you can redirect me to any repo which has same target as mine and will be of my use. It will be very helpful.
