### ISSUE TITLE
Thank you for creating this ,This is very fast

### ISSUE THREAD

**Issue by skillhacker-code** [guillaumekln/faster-whisper#25]
I  can't  thank you enough for creating this faster-whisper . this is faster than whisper cpp . this is awesome . thank you so much

**Comment by guillaumekln** [comment]
Thank you for the message!

whisper.cpp is great but it seems they still have room for improvements in terms of execution speed, especially on x86-64 platforms.

**Comment by guillaumekln** [comment]
FYI, there is an additional discussion about the comparison with whisper.cpp here https://github.com/ggerganov/whisper.cpp/discussions/589.

In short the current beam search implementation in whisper.cpp is not optimal and will probably be improved in the future. When using a beam size of 1 the speed difference is reduced.
