### ISSUE TITLE
"File ended prematurely at pos. "

### ISSUE THREAD

**Issue by billyg88** [guillaumekln/faster-whisper#250]
Hi, this might not be an issue at all but I'm getting this error when I  try to transcribe a file: 

I use:
```
segments, info = model.transcribe("18auyur.webm", beam_size=5)
```

I get: 
```
File ended prematurely at pos. 28066464 (0x1ac42a0)
```

The transcription seems to be working normally though... I'm getting good results when I use:

```
segment in tqdm(segments):
```

So this doesn't seem to be a big issue ?

**Comment by guillaumekln** [comment]
Hi,

The message is coming from the FFmpeg libraries. Probably your input file is truncated or incomplete.

If the transcription looks OK to you, you can ignore this message.

**Comment by billyg88** [comment]
Thanks a lot ! Awesome project btw !
