### ISSUE TITLE
Significantly different results between whisper.cpp and faster-whisper

### ISSUE THREAD

**Issue by re2cc** [guillaumekln/faster-whisper#251]
Hi, thanks for your work, when comparing the transcription results beetwen whisper.cpp and faster-whisper, I noticed that they were noticeably different (does not seem to be related to "temperature fallback" #76 as it doesn't change the result in whisper.cpp or faster-whisper every time I run it):

whisper.cpp (default config, model [ggml-larger.bin](https://huggingface.co/ggerganov/whisper.cpp/blob/main/ggml-large.bin), language ja) (beam size 1 or 5 dont make a difference in the result)
```
[00:00:00.000 --> 00:00:04.000]  あ~みなさ~んお待たせしました~
[00:00:04.000 --> 00:00:05.000]  よいしょ~ん
[00:00:05.000 --> 00:00:07.000]  ということでですね~
[00:00:07.000 --> 00:00:09.000]  本日は!
[00:00:09.000 --> 00:00:11.000]  お集まりいただきまして
[00:00:11.000 --> 00:00:13.000]  ありがとうございます!
```

faster-whisper (model [whisper-large-v2](https://huggingface.co/openai/whisper-large-v2) converted by me to int8 and float16 with `ct2-transformers-converter --model openai/whisper-large-v2 --output_dir src/models/faster-whisper-large-v2- --copy_files tokenizer.json --quantization float16`)
```
[0.48s -> 4.66s] あーみなさーんお待たせしましたー
[4.66s -> 8.16s] ということでですねー
[8.16s -> 11.30s] 本日はお集まりいただきまして
[11.30s -> 12.74s] ありがとうございます
```

The most obvious difference is that faster-whisper puts some of the phrases together, which is not necessarily a bad thing, although in my opinion whisper.cpp separates them more "naturally" from the audio. The problem is actually that the second sentence of whisper.cpp:
```
[00:00:04.000 --> 00:00:05.000] よいしょ~ん
```
It just doesn't show up in faster-whisper.

So far I have tried with:
```
segments, info = model.transcribe("output.wav", beam_size=5)
segments, info = model.transcribe("output.wav", beam_size=1)
segments, info = model.transcribe("output.wav", beam_size=5, best_of=2)
segments, info = model.transcribe("output.wav", beam_size=1, best_of=2, temperature=[0.0, 0.4, 0.8], suppress_tokens=None, language="ja", word_timestamps=True)
```

Is there something I'm doing wrong? Or is this kind of difference expected by the different implementation?

**Comment by guillaumekln** [comment]
Try loading the original model without quantization and see if it makes a difference:

```python
model = WhisperModel("large-v2")
```

Also consider comparing against openai/whisper as well. Typically faster-whisper tries to match the output of openai/whisper which is considered as the reference.

**Comment by re2cc** [comment]
I just compared it and indeed openai/whisper gives the same result as faster-whisper, so I guess this cannot be treated as a bug.
Thanks for the help.
