### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by wizardforcel** [guillaumekln/faster-whisper#252]
```
PS C:\Users\Administrator> ipython
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.34.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import faster_whisper
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-39ce849755c9> in <module>
----> 1 import faster_whisper

D:\Python37\lib\site-packages\faster_whisper-0.5.1-py3.7.egg\faster_whisper\__init__.py in <module>
      1 from faster_whisper.audio import decode_audio
----> 2 from faster_whisper.transcribe import WhisperModel
      3 from faster_whisper.utils import download_model, format_timestamp
      4
      5 __all__ = [

D:\Python37\lib\site-packages\faster_whisper-0.5.1-py3.7.egg\faster_whisper\transcribe.py in <module>
      6 from typing import BinaryIO, Iterable, List, NamedTuple, Optional, Tuple, Union
      7
----> 8 import ctranslate2
      9 import numpy as np
     10 import tokenizers

D:\Python37\lib\site-packages\ctranslate2\__init__.py in <module>
     16
     17     for library in glob.glob(os.path.join(package_dir, "*.dll")):
---> 18         ctypes.CDLL(library)
     19
     20 try:

D:\Python37\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: [WinError 126] The specified module could not be found
```

BUT

```
In [4]: !ls D:\Python37\lib\site-packages\ctranslate2
__init__.py              converters       extensions.py   models
__pycache__              ctranslate2.dll  libiomp5md.dll  specs
_ext.cp37-win_amd64.pyd  cudnn64_8.dll    logging.py      version.py
```

**Comment by guillaumekln** [comment]
You may need to install the Visual C++ runtime: https://www.microsoft.com/en-US/download/details.aspx?id=48145

Can you check that?

**Comment by wizardforcel** [comment]
> You may need to install the Visual C++ runtime: https://www.microsoft.com/en-US/download/details.aspx?id=48145
> 
> Can you check that?

The problem still exists.

**Comment by guillaumekln** [comment]
Did you also try after rebooting your PC?

**Comment by wizardforcel** [comment]
> Did you also try after rebooting your PC?

I reboot it every day.

**Comment by guillaumekln** [comment]
Can you update your Python version? faster-whisper requires Python >= 3.8.

**Comment by guillaumekln** [comment]
Please reopen this issue if you still get the error with Python >= 3.8.

**Comment by MissingTwins** [comment]
I'm having the same problem on fresh installed windows 10.

I think installing the Visual C++ runtime can not resolve this problem.
I have another windows 10 it doesn't have this problem because it has the windows 10 SDK installed .

```
from faster_whisper import WhisperModel

model_size = "large-v3"

# Run on GPU with FP16
# model = WhisperModel(model_size, device="cuda", compute_type="float16")

# or run on GPU with INT8
# model = WhisperModel(model_size, device="cuda", compute_type="int8_float16")
# or run on CPU with INT8
model = WhisperModel(model_size, device="cpu", compute_type="int8")

segments, info = model.transcribe("15_en-us.wav", beam_size=5)

print("Detected language '%s' with probability %f" % (info.language, info.language_probability))

for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))

```

```
(.wh) D:\work\whisper>python3 transcript.py
Traceback (most recent call last):
  File "D:\work\whisper\transcript.py", line 2, in <module>
    from faster_whisper import WhisperModel
  File "D:\work\whisper\.wh\Lib\site-packages\faster_whisper\__init__.py", line 2, in <module>   
    from faster_whisper.transcribe import WhisperModel
  File "D:\work\whisper\.wh\Lib\site-packages\faster_whisper\transcribe.py", line 10, in <module>
    import ctranslate2
  File "D:\work\whisper\.wh\Lib\site-packages\ctranslate2\__init__.py", line 18, in <module>
    ctypes.CDLL(library)
  File "C:\Users\chelsea\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'D:\work\whisper\.wh\Lib\site-packages\ctranslate2\ctranslate2.dll' (or one of its
 dependencies). Try using the full path with constructor syntax.

(.wh) D:\work\whisper>

```

![image](https://github.com/SYSTRAN/faster-whisper/assets/146804746/817e3eaa-3555-48f7-8c74-ab55c3229f88)

**Comment by margs163** [comment]
> I'm having the same problem on fresh installed windows 10.
> 
> I think installing the Visual C++ runtime can not resolve this problem. I have another windows 10 it doesn't have this problem because it has the windows 10 SDK installed . python version: 3.11.8
> Click me
> 
> (.wh) D:\work\whisper>python3 transcript.py
> Traceback (most recent call last):
>   File "D:\work\whisper\transcript.py", line 2, in <module>
>     from faster_whisper import WhisperModel
>   File "D:\work\whisper\.wh\Lib\site-packages\faster_whisper\__init__.py", line 2, in <module>   
>     from faster_whisper.transcribe import WhisperModel
>   File "D:\work\whisper\.wh\Lib\site-packages\faster_whisper\transcribe.py", line 10, in <module>
>     import ctranslate2
>   File "D:\work\whisper\.wh\Lib\site-packages\ctranslate2\__init__.py", line 18, in <module>
>     ctypes.CDLL(library)
>   File "C:\Users\chelsea\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
>     self._handle = _dlopen(self._name, mode)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: Could not find module 'D:\work\whisper\.wh\Lib\site-packages\ctranslate2\ctranslate2.dll' (or one of its
>  dependencies). Try using the full path with constructor syntax.
> 
> (.wh) D:\work\whisper>
> 
> ![image](https://github.com/SYSTRAN/faster-whisper/assets/146804746/817e3eaa-3555-48f7-8c74-ab55c3229f88)
> Click me
> 
> With the above script I can identify a list of dlls that ctranslate2.dll relies on
> 
> ```
> Listing dependencies for D:\work\whisper\.wh\Lib\site-packages\ctranslate2\ctranslate2.dll:
> libiomp5md.dll
> cudnn64_8.dll
> KERNEL32.dll
> MSVCP140.dll
> VCRUNTIME140.dll
> VCRUNTIME140_1.dll
> api-ms-win-crt-runtime-l1-1-0.dll
> api-ms-win-crt-heap-l1-1-0.dll
> api-ms-win-crt-string-l1-1-0.dll
> api-ms-win-crt-math-l1-1-0.dll
> api-ms-win-crt-convert-l1-1-0.dll
> api-ms-win-crt-environment-l1-1-0.dll
> api-ms-win-crt-stdio-l1-1-0.dll
> api-ms-win-crt-filesystem-l1-1-0.dll
> api-ms-win-crt-time-l1-1-0.dll
> api-ms-win-crt-locale-l1-1-0.dll
> ```
> 
> With the following script I found no dll is missing:
> Click me
> 
> This is fresh installed windows 10 **without** SDK and Visual Studio
> 
> ```
> Found: libiomp5md.dll at the following locations:
> D:\work\melo\.melo\Lib\site-packages\ctranslate2\libiomp5md.dll
> D:\work\melo\.melo\Lib\site-packages\torch\lib\libiomp5md.dll
> D:\work\whisper\.wh\Lib\site-packages\ctranslate2\libiomp5md.dll
> 
> Found: cudnn64_8.dll at the following locations:
> D:\work\melo\.melo\Lib\site-packages\ctranslate2\cudnn64_8.dll
> D:\work\whisper\.wh\Lib\site-packages\ctranslate2\cudnn64_8.dll
> 
> Found: KERNEL32.dll at the following locations:
> C:\Windows\System32\kernel32.dll
> 
> Found: MSVCP140.dll at the following locations:
> D:\work\melo\.melo\Lib\site-packages\pyzmq.libs\msvcp140.dll
> D:\work\melo\.melo\Lib\site-packages\sklearn\.libs\msvcp140.dll
> D:\work\whisper\.wh\Lib\site-packages\pyzmq.libs\msvcp140.dll
> C:\Windows\System32\msvcp140.dll
> C:\Windows\System32\DriverStore\FileRepository\esif_manager.inf_amd64_c3e07bc8cdaae606\msvcp140.dll
> C:\Windows\System32\DriverStore\FileRepository\esif_manager.inf_amd64_f0e354ebaaf6b665\msvcp140.dll
> C:\Windows\System32\DriverStore\FileRepository\iclsclient.inf_amd64_76523213b78d9046\lib\msvcp140.dll
> C:\Windows\System32\Intel\DPTF\msvcp140.dll
> 
> Found: VCRUNTIME140.dll at the following locations:
> C:\Windows\System32\vcruntime140.dll
> C:\Windows\System32\DriverStore\FileRepository\esif_manager.inf_amd64_c3e07bc8cdaae606\vcruntime140.dll
> C:\Windows\System32\DriverStore\FileRepository\esif_manager.inf_amd64_f0e354ebaaf6b665\vcruntime140.dll
> C:\Windows\System32\DriverStore\FileRepository\iclsclient.inf_amd64_76523213b78d9046\lib\vcruntime140.dll
> C:\Windows\System32\Intel\DPTF\vcruntime140.dll
> 
> Found: VCRUNTIME140_1.dll at the following locations:
> C:\Windows\System32\DriverStore\FileRepository\iclsclient.inf_amd64_76523213b78d9046\lib\vcruntime140_1.dll
> 
> Found: api-ms-win-crt-runtime-l1-1-0.dll at the following locations:
> C:\Windows\System32\downlevel\api-ms-win-crt-runtime-l1-1-0.dll
> 
> Found: api-ms-win-crt-heap-l1-1-0.dll at the following locations:
> C:\Windows\System32\downlevel\api-ms-win-crt-heap-l1-1-0.dll
> 
> Found: api-ms-win-crt-string-l1-1-0.dll at the following locations:
> C:\Windows\System32\downlevel\api-ms-win-crt-string-l1-1-0.dll
> 
> Found: api-ms-win-crt-math-l1-1-0.dll at the following locations:
> C:\Windows\System32\downlevel\api-ms-win-crt-math-l1-1-0.dll
> 
> Found: api-ms-win-crt-convert-l1-1-0.dll at the following locations:
> C:\Windows\System32\downlevel\api-ms-win-crt-convert-l1-1-0.dll
> 
> Found: api-ms-win-crt-environment-l1-1-0.dll at the following locations:
> C:\Windows\System32\downlevel\api-ms-win-crt-environment-l1-1-0.dll
> 
> Found: api-ms-win-crt-stdio-l1-1-0.dll at the following locations:
> C:\Windows\System32\downlevel\api-ms-win-crt-stdio-l1-1-0.dll
> 
> Found: api-ms-win-crt-filesystem-l1-1-0.dll at the following locations:
> C:\Windows\System32\downlevel\api-ms-win-crt-filesystem-l1-1-0.dll
> 
> Found: api-ms-win-crt-time-l1-1-0.dll at the following locations:
> C:\Windows\System32\downlevel\api-ms-win-crt-time-l1-1-0.dll
> 
> Found: api-ms-win-crt-locale-l1-1-0.dll at the following locations:
> C:\Windows\System32\downlevel\api-ms-win-crt-locale-l1-1-0.dll
> ```
> 
> This is windows 10 **with** SDK and Visual Studio Strange, this one works, but fresh installed one doesn't.
> Click me
> 
> # I fixed it:
> 
> After installing it on 5 different PCs without any problems, I had to download and install Visual Studio from the following link: [Visual Studio C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/). You should click on "Build Tools" and select "Desktop development with C++" (approximately 6.59GB in size).
> 
> Following this installation, the issue with ctranslate2.dll was finally resolved.
> 
> However, I've observed that one of my PCs, which doesn't have Visual Studio installed, did not encounter this problem. Interestingly, it does have the "Microsoft Visual C++ 2015-2022 Redistributable" installed. https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> ![image](https://github.com/SYSTRAN/faster-whisper/assets/146804746/ecd8d4d3-96dd-4c79-995f-6fe13f65aa2e)

Can I install Visual Studio in another path, not in the default one? Do I need to set the environment variables for the installation path?
