### ISSUE TITLE
An error lead my Spyder to restart the kernel

### ISSUE THREAD

**Issue by eric781ctf** [guillaumekln/faster-whisper#253]
I'm attempting to install and utilize the `faster_whisper` package in a new environment on Anaconda.

Before I created a new environment in Anaconda, GPU support had already been installed on the system.

Afterward, I configured the logging and followed the code usage guidelines in README.md. However, my spyder will restart the kernel after an INFO message `INFO:faster_whisper: Processing audio with duration 00:15.372`

I'm not sure if there is a limit to the type of input, so i tried input mp4, mp3 and wav, but none of these worked.

Could it be possible that the specifications of my computer are causing this issue?
The specifications of my computer are as follows:
`CPU`: i7-12700
`GPU`: RTX-3060
`Memory`: Kinston DDR4 128 GB
When running the program, I didn't notice any anomalies such as insufficient memory in the visual chart of the Windows Task Manager.

In my situation, I haven't received any further logs to aid in understanding what's going on.

**Comment by guillaumekln** [comment]
Are you trying to run on the GPU (`device="cuda")`? Does it work when running on CPU?

**Comment by eric781ctf** [comment]
Yes, it's run on the GPU(`device="cuda"`)
It works successfully on CPU.

**Comment by guillaumekln** [comment]
Most likely the program cannot find the cuDNN libraries. This is a common error on Windows and often the actual error message is not even visible. See #85.

**Comment by eric781ctf** [comment]
Thank you very much! I'll follow your advice and work on it.

**Comment by eric781ctf** [comment]
Thank you very much! I encountered the same error as you did because I also missed the "Initializing Zlib" step. Now, after following it, everything works perfectly!
