### ISSUE TITLE
504 Server Error: Gateway Time-out for url

### ISSUE THREAD

**Issue by billyg88** [guillaumekln/faster-whisper#261]
Hi there and thanks a lot again for this wonderful project !

Im getting this weird error while using: ``` segments, info = model.transcribe('whisper_production_input_audio_temp_folder/'+audio_file, language=language, beam_size = 1)```

```
huggingface_hub.utils._errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/models/guillaumekln/faster-whisper-tiny.en/revision/main
```

Can you help me with that ? 
It was working fine before it hit this error....

**Comment by guillaumekln** [comment]
Hi,

It looks there are some issues with the Hugging Face Hub at the moment.

I suggest that you update to the latest version of faster-whisper. We now ignore this error if you have already downloaded the model once.

**Comment by billyg88** [comment]
I see... sorry I've been calling the hub this whole time...  (oh dear...)

Where are the models stored locally ?

**Comment by billyg88** [comment]
Never mind  I found the keyword parameter ! Inside Whisper model initialization! 

````
          local_files_only:  If True, avoid downloading the file and return the path to the
            local cached file if it exists.
```
