### ISSUE TITLE
mp4 audio cannot be transcribed

### ISSUE THREAD

**Issue by alexjean** [guillaumekln/faster-whisper#266]
https://github.com/guillaumekln/faster-whisper/assets/5317569/680f088c-f3fa-4a13-94e2-def7cf44fd6f

audio.mp4 like above that cannot be transcribed
Error:  decode_band_types: Input buffer exhausted before END element found

**Comment by alexjean** [comment]
https://github.com/guillaumekln/faster-whisper/assets/5317569/050e8b1f-5d74-4679-9c2b-c391644cccdc

**Comment by alexjean** [comment]
https://github.com/guillaumekln/faster-whisper/assets/5317569/5f79f492-3dc4-4954-b87b-cf2be135e986

**Comment by guillaumekln** [comment]
The decoded audio returned by PyAV is empty because of this error.

You can try decoding the file with FFmpeg directly:

```
ffmpeg -i audio.mp4 -ar 16000 -ac 1 -c:a pcm_s16le output.wav
```

**Comment by alexjean** [comment]
Thank your reply. I should to find why my Android recording program always lose End_Of_Stream. Because the Openai-whipser program ignore this and work normally for a long time, so I cannot found that

**Comment by guillaumekln** [comment]
Yes, you should look into fixing the audio stream.

Otherwise you can do like openai/whisper and call FFmpeg directly. The FFmpeg CLI raises the same error but it still manages to output a usable file. On the other hand, it does not seem we can handle the error when using PyAV.
