### ISSUE TITLE
How to Host this on server (base model ) what should I do . I am a begginer to hosting 

### ISSUE THREAD

**Issue by skillhacker-code** [guillaumekln/faster-whisper#27]
If I want to host this to a server which type of server I should use , for CPU and GPU .

I researched a little for CPU i came across linode .

I have no experience hosting thinks like this , appreciate if anyone can answer .

**Comment by emhagman** [comment]
> If I want to host this to a server which type of server I should use , for CPU and GPU .
> 
> I researched a little for CPU i came across linode .
> 
> I have no experience hosting thinks like this , appreciate if anyone can answer .

Not the library maintainer but we currently have this deployed on AWS GPUs. Any machine will work honestly. I prefer DigitalOcean (https://www.digitalocean.com/) for my machines, but anything will work. For CPU, you'll probably want a few cores and 8/16GB of memory depending on how big your files are. You can check out the README for examples of memory usage.

Pricing here: https://www.digitalocean.com/pricing/droplets

**Comment by skillhacker-code** [comment]
Thank you for replying . Which aws instance are you using and how much does it cost for 1 month .

**Comment by emhagman** [comment]
> Thank you for replying . Which aws instance are you using and how much does it cost for 1 month .

The cheapest GPU option is `g4dn.xlarge` (there are cheaper ARM options but that is a pain to set up) and it costs roughly $400 a month to run. We don't have this setup to use CPUs. It would be cheaper but take much longer.

**Comment by lukerhansen** [comment]
Hi! I am also trying to figure out how to host faster-whisper. Do you have any advice? Which service did you end up using?
