### ISSUE TITLE
Missing pieces of speech in transcription

### ISSUE THREAD

**Issue by Haxeebraja** [guillaumekln/faster-whisper#270]
I am working with Arabic language transcription for stereo telephone calls at 8000 sample rate. Before calling transcribe, using decode_audio to split stereo to mono. Passing channels separately for transcription and then combining output lists.
To prevent hallucination, I am using condition_on_previous_text=False as in some files transcriptions were not able to come out of hallucination. 

The issue is that sometimes there are missing pieces of speech in transcriptions.

Running the code on Google colab (GPU A100):
model = WhisperModel("large-v2", device="cuda", compute_type="float16")
audio_data = decode_audio(audio_file, split_stereo = True)
left_channel = audio_data[0]
right_channel = audio_data[1]
left_whisper_segments, info_left = model.transcribe(audio=left_channel, beam_size=5, condition_on_previous_text=False)
left_whisper_segments = list(left_whisper_segments)

**Comment by guillaumekln** [comment]
This sounds like a general issue with the Whisper model and not an issue specific to faster-whisper. Did you try transcribing the same audio with the original openai/whisper implementation?

**Comment by toanhn** [comment]
I have same issue with Malay
