### ISSUE TITLE
Privacy and Data Ownership: Exploring Whisper Model's Data Flow and OpenAI's Involvement

### ISSUE THREAD

**Issue by mazahd** [guillaumekln/faster-whisper#276]
if i deployed my own whisper model does the data (the voice coming from my users or the text generated by whisper) go to open ai by any chances?

**Comment by guillaumekln** [comment]
This project does not send any data to OpenAI.

**Comment by HybridZach** [comment]
> This project does not send any data to OpenAI.

Pardon my ignorance but can you clarify something for me? When using this with home assistant all the data is processed locally on the machine running home assistant? It uses language models on the machine itself right?
