### ISSUE TITLE
Docker invalid argument error `what(): Option --model is required to run translation`

### ISSUE THREAD

**Issue by HalukMaestra** [guillaumekln/faster-whisper#277]
I am running a Gunicorn python server on my GKE pod with the `ghcr.io/opennmt/ctranslate2:3.14.0-ubuntu20.04-cuda11.2` as it's docker image. I am currently getting a weird error during initialization `what(): Option --model is required to run translation` `terminate called after throwing an instance of 'std::invalid_argument'`. I couldn't find much info regarding this error message. Any ideas what the problem might be? Here is the full docker file as a reference:

```
# Set the base image
FROM ghcr.io/opennmt/ctranslate2:3.14.0-ubuntu20.04-cuda11.2

# Avoiding user interaction with tzdata
ENV DEBIAN_FRONTEND=noninteractive 

# Update the system and Install necessary packages
RUN apt-get update && apt-get install -y \
    ffmpeg \
    curl \
    git \
    software-properties-common

# Set working directory and copy in project files
WORKDIR /app
COPY . ./

# Make sure pip is updated and install dependencies
RUN pip install --upgrade pip &&\
    pip install -r requirements.txt --no-cache-dir

# Set environment variables
ENV PYTHONUNBUFFERED 1

EXPOSE 8000

CMD ["python", "server.py"]

```

Just to provide more context my actual transcribe funtion is exactly the same as in the document:
`segments, _ = whisper_model.transcribe(whisper_audio, word_timestamps=True, vad_filter=True)`
This is very strange since I am not running this from the command line

**Comment by guillaumekln** [comment]
The base Docker image defines an entrypoint:

https://github.com/OpenNMT/CTranslate2/blob/7b1984c85be3e28457da4cebc5a16614baed4bf9/docker/Dockerfile#L92

So in your Dockerfile you probably need to use `ENTRYPOINT` instead of `CMD`.
