### ISSUE TITLE
The system boots but nothing happens.

### ISSUE THREAD

**Issue by boykan313** [guillaumekln/faster-whisper#285]
![342](https://github.com/guillaumekln/faster-whisper/assets/90963133/55bf10b1-dc99-43f1-b715-b49137350231)

I figured out the installation, but now just nothing happens. There is a load on the video card, but transcription does not occur. What could be the problem?

**Comment by archive-r** [comment]
Why didn't you use the print() function?

**Comment by boykan313** [comment]
> Вы написали и запустили `.py`файл сценария? Вы можете распечатать результаты, используя функцию print(). Если вы новичок в Python, вы можете сначала пройти базовое руководство по Python. Это не займет много времени!
Yes you are right! But I already figured it out, just didn’t understand where the transcription result is saved?

**Comment by archive-r** [comment]
It's hard for me to help because I don't know your code.

```
for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
```

This is how you can see the results of transcribe.

**Comment by boykan313** [comment]
![1](https://github.com/guillaumekln/faster-whisper/assets/90963133/ad69ace9-0e49-4a4c-b666-ae856e3c206a)
Tell me please, I did not find a command how to output the finished text to a separate file without time codes?

**Comment by archive-r** [comment]
> Tell me please, I did not find a command how to output the finished text to a separate file without time codes?

Then you would only need to save `segment.text` separately.

**Comment by boykan313** [comment]
> 



> > Tell me please, I did not find a command how to output the finished text to a separate file without time codes?
> 
> Then you would only need to save `segment.text` separately.

what command can i do it? Please tell me, the truth is near! :)

**Comment by boykan313** [comment]
> ```
> with open('file.txt', 'w') as f:
>     for segment in segments: 
>         f.write(f"{segment.text}\n")
> ```
> 
> Таким образом, вы можете сохранить результаты в текстовый файл.

![222](https://github.com/guillaumekln/faster-whisper/assets/90963133/022a769a-817a-4127-ae3e-6a02c4dd3b84)
What am I doing wrong please tell me.

**Comment by Purfview** [comment]
> I figured out the installation, but now just nothing happens. There is a load on the video card, but transcription does not occur. What could be the problem?

If Python is too complicated you can try: https://github.com/Purfview/whisper-standalone-win
