### ISSUE TITLE
Creating SRT/TXT Files

### ISSUE THREAD

**Issue by joseph2mi** [guillaumekln/faster-whisper#292]
Is there a way to have the code automatically create a .srt and .txt file like the original whisper?

**Comment by guillaumekln** [comment]
This project does not output any files.

You could write you own code that does this (see for example #93) or use another tool based on faster-whisper such as [whisper-ctranslate2](https://github.com/Softcatala/whisper-ctranslate2/).

**Comment by altryne** [comment]
Looks like there's a way with pysubs library as outlined here:

https://github.com/guillaumekln/faster-whisper/discussions/93#discussioncomment-5621833
