### ISSUE TITLE
fast-whisper are not fast 

### ISSUE THREAD

**Issue by hyhmaffia** [guillaumekln/faster-whisper#293]
![faster-whisper](https://github.com/guillaumekln/faster-whisper/assets/9877642/22a1b7a2-5c99-4b9b-8972-b447554b1f91)
![whisper](https://github.com/guillaumekln/faster-whisper/assets/9877642/99bd3116-5123-41fa-bbbc-da3ad47728e0)

In use, fast-whisper did not accelerate as much as stated. The test code was executed under the same environment

**Comment by guillaumekln** [comment]
openai-whisper uses different default value for the argument `beam_size`.

Try adding `"beam_size": 5` in the arguments for the original openai-whisper.

**Comment by hyhmaffia** [comment]
![faster-whisper-2](https://github.com/guillaumekln/faster-whisper/assets/9877642/384918e2-b191-4e05-b071-7ea3fa0e3c62)


thanks for you replay, this method not work for me, and the code of transcribe has a default beam_size is 5.

**Comment by guillaumekln** [comment]
I mentioned the original openai-whisper implementation in my reply, not faster-whisper. Please add `"beam_size": 5` when you are running the original Whisper implementation from OpenAI.

**Comment by hyhmaffia** [comment]
![whisper-2](https://github.com/guillaumekln/faster-whisper/assets/9877642/48fc115e-0f4d-44c0-b3d8-6c407e6737ea)

about 2.5x fast than original Whisper.  is there other params need change?

**Comment by guillaumekln** [comment]
The parameters look good now.

The README reports a 4x performance increase but it is using a longer audio file (13 minutes). Try running the transcription on longer files.
