### ISSUE TITLE
New install and getting weird error

### ISSUE THREAD

**Issue by zachNA2** [guillaumekln/faster-whisper#302]
Hello, just did a new, fresh install of faster whisper and I am getting the following error. This same dockerfile was working maybe a week ago. Is there any reason this is happening?

I load the model the following way
`whisper_model = WhisperModel(whisper_model_path, device="cuda", compute_type="float16")`

and the model_path is achieved by doing 
`git clone https://huggingface.co/guillaumekln/faster-whisper-large-v2`

However, if I do the path as large-v2 it works... 

The error I get is the following.

```
self.model = ctranslate2.models.Whisper(
RuntimeError: Unsupported model binary version. This executable supports models with binary version v6 or below, but the model has binary version v1936876918. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)
```

Any suggestions?

**Comment by guillaumekln** [comment]
Hi,

Can you try downloading the model again? It seems the files are corrupted or incomplete.
