### ISSUE TITLE
Error transcribing audio: This CTranslate2 package was not compiled with CUDA support

### ISSUE THREAD

**Issue by robegamesios** [guillaumekln/faster-whisper#307]
im using pycharm on MacBook Pro, is this supported with device = "cuda"? or I can only use "cpu"? thanks

**Comment by archive-r** [comment]
The Linux and Windows Python wheels support GPU execution. Also, `device = "cuda"` is only supported on NVIDIA GPUs.

**Comment by robegamesios** [comment]
thanks for the quick reply, any support for Intel HD Graphics 630?

**Comment by archive-r** [comment]
There does not appear to be any support for GPUs other than NVIDIA GPUs at this time.

**Comment by robEnriquezVida** [comment]
Ok thanks for the info 🙏

**Comment by robegamesios** [comment]
Ok thanks for the info 🙏
