### ISSUE TITLE
run a local fine tuned model?

### ISSUE THREAD

**Issue by silvacarl2** [guillaumekln/faster-whisper#309]
in order to run a fine tuned local model with whisper, this has to be done:

def hf_to_whisper_states(text):
    text = re.sub('.layers.', '.blocks.', text)
    text = re.sub('.self_attn.', '.attn.', text)
    text = re.sub('.q_proj.', '.query.', text)
    text = re.sub('.k_proj.', '.key.', text)
    text = re.sub('.v_proj.', '.value.', text)
    text = re.sub('.out_proj.', '.out.', text)
    text = re.sub('.fc1.', '.mlp.0.', text)
    text = re.sub('.fc2.', '.mlp.2.', text)
    text = re.sub('.fc3.', '.mlp.3.', text)
    text = re.sub('.fc3.', '.mlp.3.', text)
    text = re.sub('.encoder_attn.', '.cross_attn.', text)
    text = re.sub('.cross_attn.ln.', '.cross_attn_ln.', text)
    text = re.sub('.embed_positions.weight', '.positional_embedding', text)
    text = re.sub('.embed_tokens.', '.token_embedding.', text)
    text = re.sub('model.', '', text)
    text = re.sub('attn.layer_norm.', 'attn_ln.', text)
    text = re.sub('.final_layer_norm.', '.mlp_ln.', text)
    text = re.sub('encoder.layer_norm.', 'encoder.ln_post.', text)
    text = re.sub('decoder.layer_norm.', 'decoder.ln.', text)
    return text

hf_state_dict = torch.load("/home/silvacarl/Desktop/whisper-stt-finetune/op_dir_epoch/checkpoint-540/pytorch_model.bin")    # pytorch_model.bin file

# Rename layers
for key in list(hf_state_dict.keys())[:]:
    new_key = hf_to_whisper_states(key)
    hf_state_dict[new_key] = hf_state_dict.pop(key)

# Init Whisper Model and replace model weights
whisper_model = whisper.load_model('large-v2')
whisper_model.load_state_dict(hf_state_dict)
model = whisper.load_model(model_name).cuda()

so my question is to run a local fine tuned model with faster-whisper, is it the same or similar?

or would i have to do above, then save the model locally, then run it through something else to convert it to faster-whisper model format?

**Comment by guillaumekln** [comment]
See the section "Model conversion" in the README to convert models fine-tuned with HF: https://github.com/guillaumekln/faster-whisper#model-conversion

**Comment by silvacarl2** [comment]
perfect!
