### ISSUE TITLE
Only CPU mode gives correct results

### ISSUE THREAD

**Issue by Mar2ck** [guillaumekln/faster-whisper#310]
I've used the sample code from the readme for usage and on the CPU backend at int8 it gives the correct result:
```
Detected language 'ja' with probability 0.972193
[0.00s -> 4.00s] そのメガネを外せば、線はまた見えてしまう。

Process finished with exit code 0
```
But when using the GPU backend at int8_float16 the language detection is wrong and the text output is blank. When forcing the language to the correct one it still outputs nothing:
```
Detected language 'en' with probability 0.341553

Process finished with exit code 0
```
```
Detected language 'ja' with probability 1.000000

Process finished with exit code 0
```
My 6GB GPU can't run the model at float16 so I can't test that unfortunately. No errors are raised when using the GPU, the GPU's usage and VRAM consumption goes up during inference it definitely seems like it's being used.

Python 3.11.4
faster-whisper 0.6.0
cudatoolkit 11.8
cudnn 8.2.1
libcublas 12.1.3.1
Installed via Conda environment

OS: KDE Neon 5.27 (Ubuntu Jammy)
Kernel: Linux 5.19.0-45
GPU: GTX 1660 Ti 6GB

**Comment by archive-r** [comment]
https://github.com/guillaumekln/faster-whisper/discussions/173#discussioncomment-5707873

Note that int8 and int8_16 are not the same, so you may get different results; also see #76.

**Comment by Mar2ck** [comment]
Thanks, I tried Cuda with int8 and it works perfectly like on CPU. Maybe my GPU has an issue with FP16 or something.
