### ISSUE TITLE
Integration of the new model.

### ISSUE THREAD

**Issue by boykan313** [guillaumekln/faster-whisper#314]
Hello! Tell me, how can I add a third-party model? I want to add this one specifically. I downloaded it, created a folder for it, threw it into the model folder, I try to specify it in the command, but the command accepts the usual large-v2, this one does not want to download the regular version.

**Comment by guillaumekln** [comment]
Hi, what do you mean by a third-party model?

**Comment by boykan313** [comment]
> Привет, что ты имеешь в виду под сторонней моделью?


I want to use this model from the community, but I can't download it.
https://huggingface.co/mitchelldehaven/whisper-large-v2-ru

**Comment by guillaumekln** [comment]
See the section "Model conversion" in the README to convert the model for faster-whisper: https://github.com/guillaumekln/faster-whisper#model-conversion

Once the model is converted, you can load it from its path on disk:

```python
model = WhisperModel("/path/to/converted/model")
```

**Comment by boykan313** [comment]
> См. раздел «Преобразование модели» в README, чтобы преобразовать модель для более быстрого шепота: [https://github.com/guillaumekln/faster-whisper#model-conversion .](https://github.com/guillaumekln/faster-whisper#model-conversion)
> 
> После преобразования модели вы можете загрузить ее из пути на диске:
> 
> ```python
> model = WhisperModel("/path/to/converted/model")
> ```

Sorry for the arrogance, but I'm really bad at this, I'll take longer to figure it out. Barely made it all work, can you help me with the model transformation?

**Comment by boykan313** [comment]
> См. раздел «Преобразование модели» в README, чтобы преобразовать модель для более быстрого шепота: [https://github.com/guillaumekln/faster-whisper#model-conversion .](https://github.com/guillaumekln/faster-whisper#model-conversion)
> 
> После преобразования модели вы можете загрузить ее из пути на диске:
> 
> ```python
> model = WhisperModel("/path/to/converted/model")
> ```

I can convert it, but I didn’t really understand how to load it later.
![3222222](https://github.com/guillaumekln/faster-whisper/assets/90963133/b918f848-5461-4193-9390-7955ff045fa8)

**Comment by boykan313** [comment]
> See the section "Model conversion" in the README to convert the model for faster-whisper: https://github.com/guillaumekln/faster-whisper#model-conversion
> 
> Once the model is converted, you can load it from its path on disk:
> 
> ```python
> model = WhisperModel("/path/to/converted/model")
> ```

![322221](https://github.com/guillaumekln/faster-whisper/assets/90963133/1827df26-0d8f-4d3a-9e90-90ac44181fc3)
правильно я сделал? Меня смутила ошибка в конце.

**Comment by Purfview** [comment]
He got this error:

![321111](https://github.com/Purfview/whisper-standalone-win/assets/90963133/2c95e5a4-1f72-43b9-a688-7bd538164913)

**Comment by boykan313** [comment]
> См. раздел «Преобразование модели» в README, чтобы преобразовать модель для более быстрой загрузки: [https://github.com/guillaumekln/faster-whisper#model-conversion .](https://github.com/guillaumekln/faster-whisper#model-conversion)
> 
> После преобразования модели вы можете загрузить ее из пути на диск:
> 
> ```python
> model = WhisperModel("/path/to/converted/model")
> ```

I can't convert, there is no result when executing my commands...
![11111](https://github.com/guillaumekln/faster-whisper/assets/90963133/0acbf565-9e74-4886-a0d5-e1ba553ea0f5)
![5555](https://github.com/guillaumekln/faster-whisper/assets/90963133/14a1c082-da36-4fbd-af32-b388ad12ad12)

**Comment by boykan313** [comment]
Is it possible that someone will convert this model on their PC and let me download it? And then my mistake can not be solved, I would be very grateful?

> См. раздел «Преобразование модели» в README, чтобы преобразовать модель для более быстрого шепота: [https://github.com/guillaumekln/faster-whisper#model-conversion .](https://github.com/guillaumekln/faster-whisper#model-conversion)
> 
> После преобразования модели вы можете загрузить ее из пути на диске:
> 
> ```python
> model = WhisperModel("/path/to/converted/model")
> ```

**Comment by boykan313** [comment]
> См. раздел «Преобразование модели» в README, чтобы преобразовать модель для более быстрого шепота: [https://github.com/guillaumekln/faster-whisper#model-conversion .](https://github.com/guillaumekln/faster-whisper#model-conversion)
> 
> После преобразования модели вы можете загрузить ее из пути на диске:
> 
> ```python
> model = WhisperModel("/path/to/converted/model")
> ```

![Screenshot_1](https://github.com/guillaumekln/faster-whisper/assets/90963133/67edcfd8-5976-4f40-a67e-e44d7a54e20a)
Can you help me? Why doesn't whisper see the new model?

**Comment by guillaumekln** [comment]
Please do not post the same question in multiple places. I'm closing this issue since it was answered in https://github.com/guillaumekln/faster-whisper/issues/314#issuecomment-1600517228.
