### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by softlypink** [guillaumekln/faster-whisper#32]
Hi, it's me the tech pleb again

How are you supposed to run this? Looking in Docs didn't help. I'm on Windows 10.

Previously used this https://github.com/ProjectEGU/whisper-for-low-vram
I used CMD with this command:

whisper "C:\Users\Pink\Videos\Whisper\oranges.mp4" --task transcribe --language English --model large-v2 --patience 1.0 --output_dir "C:\Users\Pink\Videos\Whisper"

**Comment by guillaumekln** [comment]
Hi,

This project only contains a Python library. It does not include command line tools. So you would need to create a Python script as shown in the [README](https://github.com/guillaumekln/faster-whisper#usage), and the run this script from the command line.

**Comment by mliradelc** [comment]
If someone makes the files to add command line tools, would you accept that PR or is out of the scope for this project?

**Comment by guillaumekln** [comment]
I think I would like to keep this module simple and only expose a Python library. Command line tools quickly become packed with many options as users have different usage of the software.

Of course I'm open to revisit this if there is a popular demand for a command line utility.

**Comment by dodysw** [comment]
I adjusted open-ai whisper cli to faster-whisper here: https://gist.github.com/dodysw/e0af41d990def8bbeb8934eeabd77688

**Comment by CyberLykan** [comment]
It would be nice to have a command line utility that runs similar to the original whisper.
