### ISSUE TITLE
 Problem with model conversion

### ISSUE THREAD

**Issue by boykan313** [guillaumekln/faster-whisper#321]
The model after the transformation began to work incorrectly. Can this be fixed somehow? Maybe there are more subtle settings when converting?
Whis my command/
ct2-transformers-converter --model mitchelldehaven/whisper-large-v2-ru --output_dir whisper-large-v2-ru-ct2 --quantization float16

**Comment by Purfview** [comment]
Did you checked if that model works correctly before transformation?

**Comment by boykan313** [comment]
> Did you checked if that model works correctly before transformation?

yes, it worked fine in the usual whisper.

**Comment by Purfview** [comment]
Do you mean that transcription is incorrect? 
What if use `compute_type=float32`?

**Comment by boykan313** [comment]
> Вы хотите сказать, что транскрипция неверна? А если использовать `compute_type=float32`?

Yes, the transcription is incorrect, it turns out a mess of a bunch of words where the right word comes across a couple of times. All of this is printed in large sentences when everything is organized in a regular Whisper, just like in a regular large-v2 module.
Your suggestion didn't help either.
![Screenshot_4](https://github.com/guillaumekln/faster-whisper/assets/90963133/91d2c7e6-20bd-4a57-b208-ee978c7df2f0)

**Comment by archive-r** [comment]
I am having the same problem. I have converted 4 models, and the transcribe results are all strange.

https://huggingface.co/arc-r/faster-whisper-large-v2-Ko
https://huggingface.co/arc-r/faster-whisper-large-v2-jp
https://huggingface.co/arc-r/faster-whisper-large-v2-mix-jp
https://huggingface.co/arc-r/faster-whisper-large-zh-cv11

The conversion method and other details are in the link above.

**Comment by guillaumekln** [comment]
How did you execute the model before the conversion?

If you run the model with HF some default parameters are different. For example I think you have to disable timestamps with `without_timestamps=True` and maybe the previous context with `condition_on_previous_text=False`.

It depends how the models were fine-tuning. As far as I know most models are fined-tuned without timestamps.

**Comment by archive-r** [comment]
> How did you execute the model before the conversion?
> 
> If you run the model with HF some default parameters are different. For example I think you have to disable timestamps with `without_timestamps=True` and maybe the previous context with `condition_on_previous_text=False`.
> 
> It depends how the models were fine-tuning. As far as I know most models are fined-tuned without timestamps.

This explanation makes sense, thank you.
