### ISSUE TITLE
Does faster whisper support apple m1 gpu accelerate?

### ISSUE THREAD

**Issue by ILG2021** [guillaumekln/faster-whisper#325]
Hello, I am searching the fast whisper for M1 platform, I don't know if faster whisper support M1 GPU accelerate. If support, is it faster than whisper.cpp?

**Comment by guillaumekln** [comment]
faster-whisper does not use the M1 GPU. It only uses the CPU.

On Apple Silicon, whisper.cpp tends to be faster: https://github.com/guillaumekln/faster-whisper/issues/168#issuecomment-1524542057
