### ISSUE TITLE
Failed to use the prefix parameter for forced decoding

### ISSUE THREAD

**Issue by KennyShang** [guillaumekln/faster-whisper#326]
When using the prefix  parameter  for forced decoding, there may be issues of incomplete decoding, an expamle:

```
medium_model = "medium"
whisper_model = WhisperModel(medium_model, device="cuda", compute_type="float16", device_index=[0])

# without prefix
audio_file = "common_voice_en_18861476.mp3"
prefix = None
segments, info = whisper_model.transcribe(audio_file, beam_size=5, prefix=prefix, language="en")
print(list(segments))

# with prefix
prefix = " This newspaper page is no longer"
segments, info = whisper_model.transcribe(audio_file, beam_size=5, prefix=prefix, language="en")
print(list(segments), info)
```

prompt ids and results:
prompt id list:  [50258, 50259, 50359]
[Segment(id=1, seek=609, start=0.0, end=5.0, text=' This newspaper page is no longer dedicated to Hanson exclusively.', tokens=[50364, 639, 13669, 3028, 307, 572, 2854, 8374, 281, 17926, 266, 20638, 13, 50614], temperature=0.0, avg_logprob=-0.25690104564030963, compression_ratio=0.9420289855072463, no_speech_prob=0.007442474365234375, words=None)]

prompt id list:  [50258, 50259, 50359, 639, 13669, 3028, 307, 572, 2854]
[Segment(id=1, seek=609, start=0.0, end=6.09, text=' This newspaper page is no longer', tokens=[639, 13669, 3028, 307, 572, 2854, 50364], temperature=0.0, avg_logprob=-0.4326171800494194, compression_ratio=0.8421052631578947, no_speech_prob=0.007442474365234375, words=None)]
[common_voice_en_18861476.zip](https://github.com/guillaumekln/faster-whisper/files/11903691/common_voice_en_18861476.zip)

After printing the prompt information, I noticed that there seemed to be a missing initial timestamp. However, even after adding it, the issue still persists.

```
# with prefix and fix the prompt id by adding the start timestamp
prefix = " This newspaper page is no longer"
segments, info = whisper_model.transcribe(audio_file, beam_size=5, prefix=prefix, language="en")
print(list(segments), info)
```
prompt ids and results:
prompt id list:  [50258, 50259, 50359, **50364**, 639, 13669, 3028, 307, 572, 2854]
[Segment(id=1, seek=609, start=0.0, end=1.0, text=' This newspaper page is no longer', tokens=[50364, 639, 13669, 3028, 307, 572, 2854, 50414], temperature=0.0, avg_logprob=-0.3862847222222222, compression_ratio=0.8421052631578947, no_speech_prob=0.007442474365234375, words=None)]

**Comment by guillaumekln** [comment]
At this time, the `prefix` argument requires `without_timestamps=True` to work correctly.

The original Whisper implementation has the same limitation because the initial timestamp is also missing https://github.com/openai/whisper/pull/1358.

However, simply adding the initial timestamp token would not fully solve the issue on our side. We would also need to update the timestamp decoding rules which do not properly handle this case.
