### ISSUE TITLE
Question: word candidates

### ISSUE THREAD

**Issue by exactstat** [guillaumekln/faster-whisper#333]
Hi! 
Is it possible to get word candidates for each word when word_timestamps=True ?
If not, can you add this feature, please?

**Comment by phineas-pta** [comment]
it's more complicated than u think

the words aren't independently output, the probability of (n+1)-th word (more correctly token) depends on n-th word (token)

normally if not in research context u dont need candidate words (tokens)

**Comment by geekodour** [comment]
I think the related code to word candidates is at 

https://github.com/guillaumekln/faster-whisper/blob/e786e26f75f49b7d638412f3bf2b2b75a9c3c9e8/faster_whisper/transcribe.py#L590-L616

But then you'd need to do some custom stuff like @phineas-pta mentioned I guess.

But we always pick the first one. I was wondering if setting best_of > 1 has any effect at all. Maybe @guillaumekln can suggest what are the implications of setting best_of > 1 is here.

**Comment by guillaumekln** [comment]
The default value for `best_of` is 5 which means that 5 sequences will be sampled and the sequence with the highest probability will be selected. These are sequence-level candidates, not word-level.

What OP is asking is generally not possible. It could be possible to get multiple candidates for a single position, but not for all positions. So let me close this issue.
