### ISSUE TITLE
Inputting the audio stream directly will report an error

### ISSUE THREAD

**Issue by lukeewin** [guillaumekln/faster-whisper#335]
When I get the audio from the microphone through speech_recognition and send it directly to faster-whisper for transcription, the following error will be reported.

`Traceback (most recent call last):
  File "D:\Works\PythonProjects\RealTime\main.py", line 19, in listenAudioStream
    whisperHandle(audio)
  File "D:\Works\PythonProjects\RealTime\main.py", line 32, in whisperHandle
    segments, info = model.transcribe(audio, beam_size=5, vad_filter=True,
  File "D:\Software\Anaconda\envs\RealTime\lib\site-packages\faster_whisper\transcribe.py", line 239, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
  File "D:\Software\Anaconda\envs\RealTime\lib\site-packages\faster_whisper\audio.py", line 45, in decode_audio
    with av.open(input_file, metadata_errors="ignore") as container:
  File "av\container\core.pyx", line 401, in av.container.core.open
  File "av\container\core.pyx", line 246, in av.container.core.Container.__cinit__
  File "av\container\pyio.pyx", line 44, in av.container.pyio.PyIOFile.__cinit__
ValueError: File object has no read() method, or readable() returned False.`

What is the reason for this? Does it not support direct audio streaming?
If I want to do real-time transcription, does this project support direct input of audio stream and then transcribe? Just don't save it as a file, just stream it directly to the audio.
I will be very grateful if you can answer my question.

![image](https://github.com/guillaumekln/faster-whisper/assets/41370685/5f13a937-d6b3-42e4-a360-1583c28578bf)
![image](https://github.com/guillaumekln/faster-whisper/assets/41370685/494fb519-40f6-44d3-b469-840dcc577d08)

**Comment by exactstat** [comment]
Hi, seems the type of audio is incorrect. From the documentation: 
'audio: Path to the input file (or a file-like object), or the audio waveform.' 
So, it should be one of: 1) path to the file, 2) BinaryIO obj with the full file inside (see io package) 3) raw samples in a numpy array (with framerate 16000 hz).
I don't know the type of audio that comes from this 'sr. ' but if it does not have a .read() method it can be probably a bytes string. Then it should be converted to samples (with a correct framerate). I use the Pydub package for such kinds of manipulations. 
Also, it's better to initialize the model once and pass it to the function each time you want to transcribe.
