### ISSUE TITLE
without_timestamps significantly changes the result (for the worse).

### ISSUE THREAD

**Issue by jzju** [guillaumekln/faster-whisper#337]
There is 50% more words for without_timestamps=0 compared to without_timestamps=1.

**Comment by phineas-pta** [comment]
consider adding a reproducible example in a bug report to help devs figuring out what happen

**Comment by phineas-pta** [comment]
more likely hallucinations with the speech above

try use large model and/or VAD

**Comment by guillaumekln** [comment]
You could also try with the original openai-whisper but it is generally expected that `without_timestamps` changes the results. The decoding logic is very different.
