### ISSUE TITLE
Exception: Model "openai/whisper-tiny.en" on the Hub doesn't have a tokenizer

### ISSUE THREAD

**Issue by mattaltberg** [guillaumekln/faster-whisper#34]
Currently hitting this exception in this block of code. Looks like huggingface got rid of tiny.

```
tokenizer_file = os.path.join(model_path, "tokenizer.json")
if os.path.isfile(tokenizer_file):
    self.hf_tokenizer = tokenizers.Tokenizer.from_file(tokenizer_file)
else:
    self.hf_tokenizer = tokenizers.Tokenizer.from_pretrained(
        "openai/whisper-tiny" + ("" if self.model.is_multilingual else ".en")
    )
```

**Comment by guillaumekln** [comment]
The tiny.en model is still on the Hub and contains the file `tokenizer.json`:

https://huggingface.co/openai/whisper-tiny.en/tree/main

As a workaround, you could manually download `tokenizer.json` and save it the converted model directory.

**Comment by mattaltberg** [comment]
Yeah, that's exactly what I did. Weird transient issue here.

For anyone else that needs it:

```python3
import tokenizers
tok = tokenizers.Tokenizers.from_pretrained("openai/whisper-<model you want>")
tok.save('tokenizer.json')
```
