### ISSUE TITLE
can vad_max_speech_duration_s still be used if vad_filter=False?

### ISSUE THREAD

**Issue by ClaireCJS** [guillaumekln/faster-whisper#340]
I'm thinking the answer is no, but I would still like my segments to be cut up into smaller chunks than they currently are.

However, I'm in a situation where I'm using --vad_filter False at all times -- (at least, that was how the problem of 95%-missing transcription of song lyrics was solved) so I'm not sure if that option would still work or make sense or do anything.

I'd just like to tighten up the values a bit.  Lower min silence duration from 3000 to 2000, reduce vad_speech_pad_ms from 900 to 400, and set vad_max_speech_duration_s to about 10 seconds or so....

But i'm not sure if adding those options will do anything with the filter set to false.

**Comment by guillaumekln** [comment]
These are parameters of the VAD filter, so they are only relevant when the VAD filter is enabled.

To cut segments into smaller chunks, you could enable `word_timestamps` and then you could rebuild your own segments since you get access to the timing of every words.

**Comment by guillaumekln** [comment]
I think you expect these parameters to somehow change the segments length, but they do not. They only control the application of the VAD filter.

**Comment by archive-r** [comment]
For this problem, demucs can be a very effective alternative. Part of the reason for the longer segments also has to do with the whisper model recognizing non-vocal parts as speech. Try using DEMUCS to separate the vocals from the music and then transcribe them. Chances are you'll get better results.

**Comment by ClaireCJS** [comment]
> 

thanks! i was going to try with Spleeter... is one better than the other?
