### ISSUE TITLE
add wildcard+filelist support?

### ISSUE THREAD

**Issue by ClaireCJS** [guillaumekln/faster-whisper#341]
Hi,

It takes me about 15-20 seconds to do a song with this, and about 8-9 seconds of that is loading the model.

Could we have wildcard and filelist support, so that this can be run on a wildcard (*.wav for example), and filelist support, so this can be run on a list of files (an mp3 playlist, for example)?

Then we could load the model once, saving like 40% of our time when running on multiple files.

Thank you :)

**Comment by ClaireCJS** [comment]
> Hi,
> 
> I'm not sure to understand the issue. Just use a for loop after loading the model? Something like:
> 
> ```python
> import glob
> 
> model = ...
> 
> for filename in glob.glob("*.wav"):
>     segments, info = model.transcribe(filename)
>     # do something with segments
> ```

The issue is that I'm using whisper-faster.exe

**Comment by guillaumekln** [comment]
This repo does not provide `whisper-faster.exe`, so you should open this issue in the correct repo.

**Comment by ClaireCJS** [comment]
> This repo does not provide `whisper-faster.exe`, so you should open this issue in the correct repo.

My bad. I'm dealing with too many different whispers right now.

**Comment by Purfview** [comment]
Is that wildcard script example I showed you not good?  {https://github.com/Purfview/whisper-standalone-win/discussions/29#discussioncomment-6309321)

If you need it so much to work out of the box then I can implement it. It's pretty simple,

**Comment by ClaireCJS** [comment]
I think a lot of people would like it because most lack the know-how to do things with or loops. 

But for me personally, going through all the [existing] files in a filelist would be best, because I want to run this on a large playlist of music.  It's still possible to figure out how to do it with command line trickery though, but only with the infinite command line length of TCC. [one playlist i would do it on is about 4Megs long, a significant size for command line]

My dream feature for an automation of that scale would be if each individual call to whisper could be individually prompted by the contents of a txt file transcription, if one already exists. In this case, it would be lyrics downloaded (i have a bunch of these automatically downloaded by minilyrics)

It's easy enough to do this one at a time, but it would save the time of loading the model (8 seconds) thousands of times over, as it would require a different prompt for each file, and there's not a way to do that on the command line.

(i.e. using whisper on song.mp3, but prompting it with song.txt, an existing transcript of lyrics used as a prompt to give it more accurate results, in order to create song.lrc / song.srt, and automating this logic an entire list of files).

I can do this in python but it would be sooo much slower without the faster EXE file.  By some of my estimates, 2 weeks vs 10 to 50 weeks. My electric bill, haha.

**Comment by Purfview** [comment]
That's what I was afraid of, agree to implement one thing then follows the hundred exotic feature requests. 😅

Here I made a draft code to support wildcards and directories, you can test it in IDLE to check if it works as expected:
```
import sys
import os
import glob

def main():
    batch_recursive = True
    audio_arg = ["D:\Temp\*.aac"]
    audios = []

    # If audio is a directory:
    if os.path.isdir(audio_arg[0]):            
        for root, dirs, files in os.walk(audio_arg[0]):
            for filename in files:
                filepath = root + os.sep + filename
                audios.append(filepath)
            if not batch_recursive:
                break   # prevents descending into subfolders
    # If audio is a wildcard:
    elif '*.' in audio_arg[0]:
        root = os.path.dirname(audio_arg[0])
        filename = os.path.basename(audio_arg[0])
        if root == "":
            root = os.getcwd()
        if batch_recursive:
            filepath = root + os.sep + "**" + os.sep + filename
        else:
            filepath = root + os.sep + filename
        files = glob.glob(filepath, recursive=batch_recursive)
        for i in files:
            audios.append(i)
    # If invalid wildcard:
    elif '*' in audio_arg[0]:
        print("Error: Invalid input for audio. Wildcard examples: \"D:\\Dir\\*.*\", \"D:\\Dir\\*.mp4\". or \"*.mp4\"")
        sys.exit()
    # Continue as usual:
    else:                                        
        audios = audio_arg

    print("\nDo work on these files:")    
    print(audios)

main()
```

I don't want to bother with filelists, if you can edit it in here then maybe I'll incorporate it.

**Comment by ClaireCJS** [comment]
Oh I'm Sorry, didn't mean to open a pandora's box! 😅 I can see how that would be anxiety-inducing to suddenly get a bunch of exotic feature requests!

I did not know what IDLE was, but I figured it out and am trying this out. Thanks for the tip!

I'm taking a crack at it right now...

**Comment by ClaireCJS** [comment]
My comments -

I think directory should recurse, otherwise a wildcard could do the same thing. The point in my mind was to allow mass batch scripting across all folders for people who don't want to construct a super long  command line.    Point it to their music collection, transcribe away!
 
However, that's a moot point with filelist support! Filelist can do anything! :) I feel like commenting out your "if not batch_recursive" if overstepping 😅 I'm new here but not new in general 😅

Also, none of this filters for valid extensions, but I'm assuming that happens downstream somewhere anyway. But I could add filter-by-extension to only the ones whisper supports if you want.

**Comment by ClaireCJS** [comment]
Okay, got it working right I think!

'''

#test results

#"*.flac"    wildcard working: audio_arg = ["c:\\working\\asdf\\*.flac"] == Do work on these files: ['c:\\working\\asdf\\02_Muzzle.flac', 'c:\\working\\asdf\\06_Mother.flac', 'c:\\working\\asdf\\1_Fences.flac', 'c:\\working\\asdf\\2_07_Theme For A Jackal (Reel Platinum 1985).flac']

#"*foo.flac" wildcard working: audio_arg = [r"c:\working\asdf\*le.flac"] == Do work on these files: ['c:\\working\\asdf\\02_Muzzle.flac']

#         directories working: audio_arg = [r"c:\working\asdf"]          == Do work on these files: ['c:\\working\\asdf\\02_Muzzle.flac', 'c:\\working\\asdf\\06_Mother.flac', 'c:\\working\\asdf\\1_Fences.flac', 'c:\\working\\asdf\\1_Fences.txt', 'c:\\working\\asdf\\2_07_Theme For A Jackal (Reel Platinum 1985).flac', 'c:\\working\\asdf\\a', 'c:\\working\\asdf\\clean.bat']
#********************* caveat: this puts ALL the files in the argument. I assume invalid extensions are ignored? If not I can add that

#  "foo.m3u" filelist working: audio_arg = [r"c:\working\asdf\test.m3u"] == Do work on these files:['c:\\working\\asdf\\1_Fences.flac', 'c:\\working\\asdf\\2_07_Theme For A Jackal (Reel Platinum 1985).flac', 'c:\\working\\asdf\\02_Muzzle.flac', 'c:\\working\\asdf\\06_Mother.flac']
#                    includes: compensating for the fact that a filelist might not have the path listed inside the filelist - this goes through and adds it

'''


Here is the code!

```
import sys
import os
import glob

def main():
    batch_recursive = True
    audio_arg = [r"c:\working\asdf\test.m3u"]
    audios = []

    # If audio is a directory:
    if os.path.isdir(audio_arg[0]):            
        for root, dirs, files in os.walk(audio_arg[0]):
            for filename in files:
                filepath = root + os.sep + filename
                audios.append(filepath)
            if not batch_recursive:
                break   # prevents descending into subfolders
    # If audio is a wildcard:
    elif '*' in audio_arg[0]:
        root = os.path.dirname(audio_arg[0])
        filename = os.path.basename(audio_arg[0])
        if root == "":
            root = os.getcwd()
        if batch_recursive:
            filepath = root + os.sep + "**" + os.sep + filename
        else:
            filepath = root + os.sep + filename
        files = glob.glob(filepath, recursive=batch_recursive)
        for i in files:
            audios.append(i)
    # If invalid wildcard:
    #elif '*' in audio_arg[0]:
    #    print("Error: Invalid input for audio. Wildcard examples: \"D:\\Dir\\*.*\", \"D:\\Dir\\*.mp4\". or \"*.mp4\"")
    #    sys.exit()
    # Continue as usual:
    elif len(audio_arg) == 1:
        file_name = audio_arg[0]
        file_directory = os.path.dirname(file_name)
        file_basename, file_extension = os.path.splitext(file_name)

        if file_extension.lower() in [".txt", ".m3u", ".m3u8", ".lst"]:
            with open(file_name, 'r', encoding="utf-8") as file:
                file_list = file.read().splitlines()
            file_list = [os.path.join(file_directory, tmp_file_name) for tmp_file_name in file_list]            # Add directory path to each file name
            audios = file_list
        else:
            audios = audio_arg
    else:                                        
        audios = audio_arg

    print("\nDo work on these files:")    
    print(audios)

main()
```

**Comment by ClaireCJS** [comment]
Also, my apologies if I misunderstood anything!

This really has helped me flush out my own personal pattern for file processors though. And I appreciate getting to learn about idle. I didn't know python before chatgpt...  thank you!

**Comment by Purfview** [comment]
> I think directory should recurse...

It already does that.

> Also, none of this filters for valid extensions, but I'm assuming that happens downstream somewhere anyway. 

Yeah. Happens when you see error in the middle of operation. :)

> But I could add filter-by-extension to only the ones whisper supports if you want.

Be my guest, I think it's down to what ffmpeg supports.

> Okay, got it working right I think!

I tried your filelist code on random m3u8 and it didn't work properly, it added "#EXTINF" stuff to `audios` variable.
I updated my previous post with tweaked version. [your part is cosmetically tweaked too]

**Comment by ClaireCJS** [comment]
Oh shoot i forgot about the comments m3u files have sometimes. But yea, I was thinking, invalid filenames were perhaps caught at a different point in the process and not a concern right then 😅

**Comment by Purfview** [comment]
You should do a check if file exists before adding it to `audios` list.

**Comment by ClaireCJS** [comment]
Good idea, here's the updated code. It also checks if there are quotes around a filename in a filelist, because i'm sure somewhere out there is doing that unnecessarily 🤣

'''
import sys
import os
import glob

def main():
    batch_recursive = True
    audio_arg = [r"c:\working\asdf\test.m3u"]
    audios = []

    audiovideo_extensions = [".mp3", ".wav", ".rm", ".voc", ".au", ".mid", ".stm", ".mod", ".vqf", ".ogg", ".opus", ".mpc", ".ac3", ".wma", ".mp4", ".flac", ".snd", ".aac", ".mkv", ".avi", ".mp4", ".m4a", ".flv", ".mov", ".wmv", ".mpg", ".mpeg", ".vob", ".bdmv", ".ts", ".m2ts", ".rm", ".qt", ".asf", ".asx", ".fli", ".swf", ".m4v", ".webm", ".f4v", ".rm", ".ram", ".3gp"]
    filelist_extensions = [".txt", ".m3u", ".m3u8", ".lst"]

    # If audio is a directory:
    if os.path.isdir(audio_arg[0]):            
        for root, dirs, files in os.walk(audio_arg[0]):
            for filename in files:
                filepath = root + os.sep + filename
                audios.append(filepath)
            if not batch_recursive:
                break   # prevents descending into subfolders
    # If audio is a wildcard:
    elif '*' in audio_arg[0]:
        root = os.path.dirname(audio_arg[0])
        filename = os.path.basename(audio_arg[0])
        if root == "":
            root = os.getcwd()
        if batch_recursive:
            filepath = root + os.sep + "**" + os.sep + filename
        else:
            filepath = root + os.sep + filename
        files = glob.glob(filepath, recursive=batch_recursive)
        for i in files:
            audios.append(i)
    # If invalid wildcard:
    #elif '*' in audio_arg[0]:
    #    print("Error: Invalid input for audio. Wildcard examples: \"D:\\Dir\\*.*\", \"D:\\Dir\\*.mp4\". or \"*.mp4\"")
    #    sys.exit()
    # Continue as usual:
    elif len(audio_arg) == 1:
        file_name = audio_arg[0]
        file_directory = os.path.dirname(file_name)
        file_basename, file_extension = os.path.splitext(file_name)
        if file_extension.lower() in filelist_extensions:
            with open(file_name, 'r', encoding="utf-8") as file:
                file_list = file.read().splitlines()
            stripped_files = [f.strip('"') for f in file_list]
            full_files = [os.path.join(file_directory, f) for f in stripped_files]             # convert filelist's filenames to full paths
            existing_files = [f for f in full_files if os.path.isfile(f)]
            valid_extension_files = [f for f in existing_files if os.path.splitext(f)[1].lower() in audiovideo_extensions] 
            audios = valid_extension_files
            #print(f"stripped_files={stripped_files}\n\nfull_files={full_files}\n\nexisting_files={existing_files}\n\nvalid_extension_files={valid_extension_files}")
        else:
            audios = audio_arg
    else:                                        
        audios = audio_arg

    print("\nDo work on these files:")    
    print(audios)

main()
'''

**Comment by Purfview** [comment]
Now it works. Added to r134.5 exe. Read help about `audio` and `--batch_recursive` arguments.
Added it same same as in https://github.com/guillaumekln/faster-whisper/issues/341#issuecomment-1627285903 post.

If you'll have further issues then open a new issue at the right repository.
