### ISSUE TITLE
How can we get complete transcription without getting segments?

### ISSUE THREAD

**Issue by shahzebali42** [guillaumekln/faster-whisper#342]
There is a parameter 'chunk_length_s' in huggingface open ai whisper model. But this var is not included in the faster_whisper transcribe class. What is the replacement for this var? 
Also could you please let me know how can i get complete transcription instead of getting segments because i witnessed that some of the words are being missed due to segments. Thanks in advance!

**Comment by guillaumekln** [comment]
There is no equivalent to `chunk_length_s` in faster-whisper. The original implementation from OpenAI does not use this parameter.

You can only get the full transcription via the segments, for example:

```python
transcription = "".join(segment.text for segment in segments)
```

So if a word is missing in a segment, it will also be missing in the complete transcription.

**Comment by shahzebali42** [comment]
I see. Thanks for quick response, Can you please let me know the best hyper parameters as per you think to get the best results, not missing any word.

**Comment by guillaumekln** [comment]
I would say that the best parameters are the default ones, because they accurately match the default behavior of the OpenAI implementation.

**Comment by shahzebali42** [comment]
what do we have in replace of these parameters of OPENAI Whisper
 `suppress_silence`, `ts_num`, `lower_quantile`, `lower_threshold`

ref : https://github.com/openai/whisper/discussions/435

**Comment by phineas-pta** [comment]
those parameters aren't in openai whisper

they're from this fork https://github.com/jianfch/stable-ts

pls read that discussion more carefully
