### ISSUE TITLE
Is there a code to add a translation from english to another language?

### ISSUE THREAD

**Issue by joseph2mi** [guillaumekln/faster-whisper#343]
Currently, the only code I have is "task:translate", which assumes that the language is in a non-English language and that I need to translate to English.

**Comment by archive-r** [comment]
It is not included in faster-whisper, but can be implemented using other libraries.

**Comment by archive-r** [comment]
faster-whisper does not support translation from English to other languages. You will need to use other libraries for translation.

**Comment by guillaumekln** [comment]
The Whisper model only supports translation **to** English. You should use a separate translation model to translate in other directions.
