### ISSUE TITLE
semaphore error

### ISSUE THREAD

**Issue by Maxamed** [guillaumekln/faster-whisper#345]
I keep getting error whenever i run the transcribe 

resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

Any faced similar error? 

I'm on mac using python 3.11

**Comment by guillaumekln** [comment]
This warning seems to come from the `multiprocessing` module but faster-whisper does not use this module directly.

Can you post a code snippet to reproduce the warning with faster-whisper?

**Comment by shanky100** [comment]
Hi, I am also facing this same issue on my MAC, I am first diarizing my audio and then for each diarized segment I am trying to diarized the result. But once diarization is done , when the code starts for transcription i get that error and my program gets killed.

/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

Any solution will be helpful.

**Comment by guillaumekln** [comment]
It does not seem to be directly related to faster-whisper. Feel free to reopen if you can provide a code snippet to reproduce the warning when using only faster-whisper.

**Comment by etdapt** [comment]
I have faced similar error and I have turned on logging, here's my logs:

```
2024-04-28 10:29:50,168 - INFO - Processing audio with duration 00:05.100
2024-04-28 10:29:50,491 - INFO - VAD filter removed 00:00.000 of audio
2024-04-28 10:29:50,491 - DEBUG - VAD filter kept the following audio segments: [00:00.000 -> 00:05.100]
2024-04-28 10:30:00,112 - DEBUG - Processing segment at 00:00.000
/opt/anaconda3/envs/SoVITS/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
```

**Comment by yhh1008** [comment]
try to do it directly in terminal instead of in webui.

I did this and it works perfectly:
PYTHONWARNINGS="ignore" "/Users/username/GPT-SoVITS/venv/bin/python" tools/asr/fasterwhisper_asr.py -i "/Users/username/GPT-SoVITS/output/uvr5_opt" -o "/Users/username/GPT-SoVITS/output/asr_opt" -s base -l ja -p float32

also try different shots with different model. its weird but sometimes base and tiny model works for me, sometimes not.
