### ISSUE TITLE
 questions about quantification

### ISSUE THREAD

**Issue by breaddance** [guillaumekln/faster-whisper#350]
Have you tried using int8? I noticed you mentioned float16. What is the reason behind your choice of float16? Also, regarding the command you mentioned: ct2-transformers-converter --model openai/whisper-large-v2 --output_dir faster-whisper-large-v2 --copy_files tokenizer.json --quantization float16, the converted model using float16 seems to perform worse than yours. I hope you could provide some assistance with this.

**Comment by breaddance** [comment]
@phineas-pta speed，gpu，I am using some short audio clips.By the way, I would like to ask if you have any good suggestions for quantization to improve the inference speed. I would be extremely grateful if you could provide me with some answers.

**Comment by phineas-pta** [comment]
consider provide a reproducible example of audio, show how much slower u get

> if you have any good suggestions for quantization

u should ask in discussion, issue is to report bug
