### ISSUE TITLE
How to suppress warnings from ctranslate2?

### ISSUE THREAD

**Issue by Purfview** [guillaumekln/faster-whisper#353]
How to suppress warnings from ctranslate2? This for example:

>  [ctranslate2] [thread 6280] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.

Some users think that warnings are errors.

**Comment by guillaumekln** [comment]
Set the ERROR log level:

```python
import logging
import ctranslate2
ctranslate2.set_log_level(logging.ERROR)
```

**Comment by Purfview** [comment]
Thx.
