### ISSUE TITLE
ValueError: File tokenizer.json does not exist in model ...

### ISSUE THREAD

**Issue by cchen028** [guillaumekln/faster-whisper#355]
I'm trying to convert [https://huggingface.co/vasista22/whisper-hindi-large-v2]
but it gives the following error after downloading the model: 
`ValueError: File tokenizer.json does not exist in model vasista22/whisper-hindi-large-v2`

Is there a way around this or can we only convert existing fine tune models with the tokenizer.json file?
Thanks.

**Comment by archive-r** [comment]
https://github.com/guillaumekln/faster-whisper/discussions/317#discussioncomment-6241502

**Comment by cchen028** [comment]
> [#317 (comment)](https://github.com/guillaumekln/faster-whisper/discussions/317#discussioncomment-6241502)
> 
> You can try: `ct2-transformers-converter --model vasista22/whisper-hindi-large-v2 --output_dir faster-whisper-hindi-large-v2 --quantization float16`

Very appreciate for the link and the response. This works.
