### ISSUE TITLE
If anybody shared the translated models?

### ISSUE THREAD

**Issue by bigbenbird** [guillaumekln/faster-whisper#36]
Will this project support  ".pt" file instead of bin model hold in hugging face?Or this project can storage translated models in some public storage.

Because the bin models in hugging face are very large and my network is pretty slow, it will be a large challenge for me to download this size of model.

**Comment by guillaumekln** [comment]
By ".pt" file do you mean the checkpoints that are downloaded by openai/whisper? If yes, there is currently no converter for these files. We only provide a converter for the models that are coming from Hugging Face.

The larger model is about 6GB in the model Hub. I guess you just have have to be patient and let the download run for some time.

**Comment by Mario03482** [comment]
Hi
Is there a direct link for the large-v2 model already converted?

**Comment by ohmygoobness** [comment]
Sharing converted whisper-v2 ct2 fp16 https://drive.google.com/file/d/13Oq6wlrmzXeP8ciJ9p9R-pE5m1iJb9aq/view?usp=sharing
Put it files inside faster-whisper\whisper-large-v2-ct2

Contain files:
```
config.json	2.2 kB
model.bin	2.9 GB
tokenizer.json	2.1 MB
vocabulary.txt	449 kB
```

**Comment by Mario03482** [comment]
> Sharing converted whisper-v2 ct2 fp16 https://drive.google.com/file/d/13Oq6wlrmzXeP8ciJ9p9R-pE5m1iJb9aq/view?usp=sharing
> 
> Put it files inside faster-whisper\whisper-large-v2-ct2
> 
> 
> 
> Contain files:
> 
> ```
> 
> config.json	2.2 kB
> 
> model.bin	2.9 GB
> 
> tokenizer.json	2.1 MB
> 
> vocabulary.txt	449 kB
> 
> ```

Thanks

**Comment by guillaumekln** [comment]
I pushed converted models to the HuggingFace Hub: https://huggingface.co/guillaumekln

The linked PR is also updating the code to automatically download these model so that the conversion step is no longer needed in most cases.
