### ISSUE TITLE
Normalizer issue

### ISSUE THREAD

**Issue by dipeshhoncho07** [guillaumekln/faster-whisper#360]
Hi, how can we incorporate normalizer.json used by whisper tokenizer while decoding through faster-whisper?

**Comment by guillaumekln** [comment]
Hi,

I’m not sure exactly how you want to use the normalizer. Can you give an example?

**Comment by dipeshhoncho07** [comment]
In whisper normalizer.json contains key value pair, which is inherently the mapping between incorrect word spelling and correct word spelling. 

I want to solve the confusion that whisper does whenever there is vowel sound in a word and generates wrong spelling for certain words.

Link: https://huggingface.co/openai/whisper-large/blob/main/normalizer.json

**Comment by guillaumekln** [comment]
You could simply apply the mapping on the text output as a postprocessing step. The logic is very basic and simply splits the text output on spaces:

https://github.com/huggingface/transformers/blob/129cb6d5239374869beea0e1317641426e8df572/src/transformers/models/whisper/english_normalizer.py#L507
