### ISSUE TITLE
RuntimeError: No SGEMM backend on CPU

### ISSUE THREAD

**Issue by Jeronymous** [guillaumekln/faster-whisper#37]
I am testing the branch `word-level-timestamps` https://github.com/guillaumekln/faster-whisper/commit/dc780dcbe01daf9f3b082c0153c315f683ed829a

I installed your fork of CTranslate2 https://github.com/guillaumekln/CTranslate2.git on branch `whisper-align`.

When I try to run inference with word timestamps, I get: 
```
Traceback (most recent call last):
[...]
    segments, info = model.transcribe(audio)
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 206, in transcribe
    results = self.model.detect_language(input)
RuntimeError: No SGEMM backend on CPU
```

I have seen this issue https://github.com/OpenNMT/CTranslate2/issues/646 but in my case it looks different.
I did the cmake with default options (also tried explicit option `-DWITH_MKL=ON`) and I have MKL
```
-- Found MKL include directory: /opt/intel/oneapi/mkl/latest/include
-- Found MKL library directory: /usr/lib/x86_64-linux-gnu
```
Do you see what I can be missing?

**Comment by guillaumekln** [comment]
Hello,

> `Found MKL library directory: /usr/lib/x86_64-linux-gnu`

This location seems unexpected for MKL libraries. It should be `/opt/intel/oneapi/mkl/latest/lib/intel64/`.

However, note that you don't need to compile the library yourself to test this branch. Python packages are compiled for each new PR on GitHub. The full installation procedure is described here: https://github.com/guillaumekln/faster-whisper/issues/12#issuecomment-1462293115

**Comment by Jeronymous** [comment]
Thank you!

I fixed the MKL librairies folder, but the same runtime error occurs.

With the installation procedure that you describe, it works like a charm.

**Comment by guillaumekln** [comment]
Great! I’m closing this issue since you managed to install everything at the end.

Feel free to reopen if you still want to compile from scratch.
