### ISSUE TITLE
Strange error: "killed?"

### ISSUE THREAD

**Issue by ckcollab** [guillaumekln/faster-whisper#373]
Strangely, on just one particular file (716mb) I get this error/crash:

```
Model loaded, transcribing next
Estimating duration from bitrate, this may be inaccurate
Killed
```

```py
model_size = "medium.en"

# Run on GPU with FP16
model = WhisperModel(model_size, device="cuda", compute_type="float16")

print("Model loaded, transcribing next")

segments, info = model.transcribe(filename, beam_size=5)
```

Everything else works _great_ (thank you so much!) but just this one large particular file gets this strange fail.

I even tried re-reencoding the file as AAC, a lower bitrate so it's only ~400mb (smaller than other successful files). Strange stuff.

EDIT:

Also fails with CPU and other int/fp settings..!

**Comment by guillaumekln** [comment]
Your system is probably running out of memory when decoding the audio. How much system memory do you have?

The file size on disk does not mean much because the decoded audio can use much more memory.

**Comment by ckcollab** [comment]
32gb system memory and I think 10 or 12 gb GPU memory

I tried `small` _and_ `base` models, both failed with the same "Killed" message.. hmm..

thanks for the help attempting to debug here!

**Comment by estresmo** [comment]
Are you trying on a VPS ? Most VPS providers kill the process that uses 100% of the CPU. FFMPEG (whisper dependence) will always use all available CPU until the process is over

**Comment by ckcollab** [comment]
Nah this is on my windows WSL machine with ubuntu, not a VPS

Is "CPULimit" even relevant for a GPU cuda job? I'll maybe have to try that later today, ty for the clue!

**Comment by ckcollab** [comment]
NOTE for anyone else experiencing this: for one MP3 I was able to split it up with ffmpeg, recombine it, and THEN the mp3 processed properly. Very strange! I had some nag about removing MP3 album art, which may be relevant?

On a new failing mp3 this doesn't seem to be working.

I can't provide examples directly as it's for a private podcast.. just giving this information in case it helps someone else!

**Comment by junchen6072** [comment]
I think one part of the library is memory heavy, if the audio is super long it'll oom. In your case it's a 716mb audio, so I guess 10+ hours? I'm not surprised it'll oom, breaking it up into smaller sub-audios will work

**Comment by ckcollab** [comment]
Yeah, I haven't experienced this since I started splitting the audio into 4 hour chunks, ty!
