### ISSUE TITLE
File t does not exist in model openai/whisper-large-v2

### ISSUE THREAD

**Issue by Ibuprofenighty** [guillaumekln/faster-whisper#375]
Hi there,

When trying to do the model conversion via Ctranslate2 API (as same setup following as CLI), the conversion failed and popped the error 'File t does not exist in model openai/whisper-large-v2'. And also, when trying to transcribe the audio in GPU mode, it always failed with the 'Cannot execute code, session has been disposed. Please try restarting the Kernel.
The Kernel crashed while executing code in the the current cell or a previous cell. ' Is there any suggestion please?

**Comment by guillaumekln** [comment]
Hi,

Can you post the code you are using to convert the model?

**Comment by Ibuprofenighty** [comment]
from ctranslate2.converters import TransformersConverter

converter = TransformersConverter(model_name_or_path='openai/whisper-large-v2',copy_files='tokenizer.json')
converter.convert(output_dir='openai/whisper-large-v2-ct2', quantization='float16')

**Comment by Ibuprofenighty** [comment]
> Hi,
> 
> Can you post the code you are using to convert the model?

from ctranslate2.converters import TransformersConverter

converter = TransformersConverter(model_name_or_path='openai/whisper-large-v2',copy_files='tokenizer.json')
converter.convert(output_dir='openai/whisper-large-v2-ct2', quantization='float16')

**Comment by guillaumekln** [comment]
See the documentation https://opennmt.net/CTranslate2/python/ctranslate2.converters.TransformersConverter.html.

`copy_files` is a `List[str]` so you should pass `copy_files=['tokenizer.json']`.

**Comment by Ibuprofenighty** [comment]
> See the documentation https://opennmt.net/CTranslate2/python/ctranslate2.converters.TransformersConverter.html.
> 
> `copy_files` is a `List[str]` so you should pass `copy_files=['tokenizer.json']`.

Great! Thanks a lot. By the way, do you have any idea of my second question that 
"when trying to transcribe the audio in GPU mode, it always failed with the 'Cannot execute code, session has been disposed. Please try restarting the Kernel. The Kernel crashed while executing code in the the current cell or a previous cell. ' 

The CUDA installation is correct as I have double checked. And I can call the APIs on Colab. Just only fail on my local Jupyter..

**Comment by guillaumekln** [comment]
The error message is generic so I don't really know. Try running the code without Jupyter.
