### ISSUE TITLE
Strange performance behaviour

### ISSUE THREAD

**Issue by x86Gr** [guillaumekln/faster-whisper#382]
I'm testing a 1m35s audio on the cpu with int8, model large-v2

model = WhisperModel(model_size, device="cpu", compute_type="int8")

The input file is 16khz 16bit mono. With the string

segments, _ = model.transcribe("test.wav", beam_size=1, best_of=1, vad_filter=True)

the transcription time is 1m40s. However, if i pass the language argument which should skip the language detection, like this

segments, _ = model.transcribe("test.wav", language='it', beam_size=1, best_of=1, vad_filter=True)

the transcription time goes up to 1m59s instead of going down.

**Comment by guillaumekln** [comment]
Can you enable the DEBUG logs and report the output for both runs? See https://github.com/guillaumekln/faster-whisper#logging

**Comment by x86Gr** [comment]
INFO:faster_whisper:Processing audio with duration 01:35.000
INFO:faster_whisper:VAD filter removed 00:00.752 of audio
DEBUG:faster_whisper:VAD filter kept the following audio segments: [00:00.752 -> 01:35.000]
INFO:faster_whisper:Detected language 'it' with probability 0.99
DEBUG:faster_whisper:Processing segment at 00:00.000
(text)
DEBUG:faster_whisper:Processing segment at 00:17.000
(text)
DEBUG:faster_whisper:Processing segment at 00:47.000
(text)
DEBUG:faster_whisper:Processing segment at 01:17.000
(text)
runtime: 01:37.214710

INFO:faster_whisper:Processing audio with duration 01:35.000
INFO:faster_whisper:VAD filter removed 00:00.752 of audio
DEBUG:faster_whisper:VAD filter kept the following audio segments: [00:00.752 -> 01:35.000]
DEBUG:faster_whisper:Processing segment at 00:00.000
(text)
DEBUG:faster_whisper:Processing segment at 00:17.000
(text)
DEBUG:faster_whisper:Processing segment at 00:47.000
(text)
DEBUG:faster_whisper:Processing segment at 01:17.000
(text)
runtime: 01:55.967254

**Comment by x86Gr** [comment]
Good point, but if i time everything like this:

from faster_whisper import WhisperModel
import datetime
model_size = "large-v2"

print(datetime.datetime.now())
model = WhisperModel(model_size, device="cpu", compute_type="int8")#5
print(datetime.datetime.now())

segments, _ = model.transcribe("test.wav", beam_size=1, best_of=1, vad_filter=True)
print(datetime.datetime.now())
for segment in segments:
    print("%s" % (segment.text))
print(datetime.datetime.now())

segments, _ = model.transcribe("test.wav", language='it', beam_size=1, best_of=1, vad_filter=True)
print(datetime.datetime.now())
for segment in segments:
    print("%s" % (segment.text))
print(datetime.datetime.now())

The first "segments, _ = model.transcribe(..)" takes 22s, the second one takes less than 1s, the first for cycle takes 1m38s and the second one takes 1m57s

**Comment by guillaumekln** [comment]
This is expected. The langue setting determines when the first 30 seconds of audio are encoded by the Whisper model.

When the language is not set, the encoding happens in the transcribe method before returning the generator.

When the language is set, the encoding happens in the segment generator.

**Comment by guillaumekln** [comment]
Your current usage seems fine so I don't have other recommendations. Feel free to open another issue or discussion if you have more questions.
