### ISSUE TITLE
Is there a way to work with Whisper models finetuned with transformers?

### ISSUE THREAD

**Issue by Jeronymous** [guillaumekln/faster-whisper#387]
Is it possible to use `faster_whisper` with models like this one https://huggingface.co/bofenghuang/whisper-large-v2-cv11-french
(trained with `transformers` library, without or without PEFT)?

**Comment by phineas-pta** [comment]
see README for model conversion

**Comment by Jeronymous** [comment]
Thanks @phineas-pta
