### ISSUE TITLE
Reduce startup/warmup time

### ISSUE THREAD

**Issue by emcodem** [guillaumekln/faster-whisper#396]
It would be interesting to know what options are there to reduce startup time. 
From my current quick and dirty measurements on a state-of-the-art Laptop (M2 disk, Nvidia A3000, Core i9 etc..), i see the following times using a 15 second wav input and large-v2:

Stage1: 5 seconds until we start loading the model (transcribe.py: self.model = ctranslate2.models.Whisper)
Stage2: 9 seconds until this code line returns (model is loaded into GPU?)
Stage3: 6-8 seconds until the first sentence is transcribed 

Overall usually between 20 and 25 seconds until we get the first output i assume. 

Compared to Const-me version, the model seems to be loaded after about 3 seconds and the whole process from start to end for transcribing the same 15 second file takes around 7-9 seconds overall.

My assumption is that 
Stage1, it is mainly torch that is holding up?
Stage2: it is Ctranslate2, are there options to speed up? does it do a lot of calculations before loading the model e.g. convert the whole thing? if yes, couldn't we cache something at this stage and re-use next time or similar?
Stage3: i have some feeling that the very "first" call to transcribe function takes longer than all others while runtime but i might be totally wrong here.

Here the relevant part of const-me performance analysis:
```
    CPU Tasks
LoadModel       3.18499 seconds
RunComplete     4.56679 seconds
Run     4.41786 seconds
Callbacks       4.6332 milliseconds, 8 calls, 579.15 microseconds average
Spectrogram     53.9497 milliseconds, 3 calls, 17.9832 milliseconds average
Sample  42.1393 milliseconds, 63 calls, 668.878 microseconds average
Encode  1.9418 seconds
Decode  2.47129 seconds
DecodeStep      2.42901 seconds, 63 calls, 38.5557 milliseconds average
    GPU Tasks
LoadModel       2.76151 seconds
Run     4.30291 seconds
Encode  1.83221 seconds
EncodeLayer     1.54756 seconds, 32 calls, 48.3613 milliseconds average
Decode  2.4707 seconds
DecodeStep      2.47058 seconds, 63 calls, 39.2156 milliseconds average
DecodeLayer     2.31594 seconds, 2016 calls, 1.14878 milliseconds average
    Compute Shaders
mulMatTiled     1.71115 seconds, 705 calls, 2.42716 milliseconds average
mulMatByRowTiled        1.35199 seconds, 23870 calls, 56.6395 microseconds average
```

Attached also the file that i used, it is german language (-l de) acutally and it is kind of a stress test because it usually causes the model to output max length results which have then to be mitigated by the code, e.g. by the applying compression ratio triggered workaround.

[oh.zip](https://github.com/guillaumekln/faster-whisper/files/12239685/oh.zip)

**Comment by guillaumekln** [comment]
> Overall usually between 20 and 25 seconds until we get the first output i assume.

This looks high to me. Can you post the code you are running?

---

I tested the code below and the whole thing took 9 seconds for a 13-second MP3 file. This time includes the model quantization to int8 on load, the MP3 decoding, the language detection, the beam search, etc.

```python
from faster_whisper import WhisperModel

model = WhisperModel("large-v2", device="cuda", compute_type="int8")
segments, info = model.transcribe("test.mp3")

for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
```

---

> it is mainly torch that is holding up?

faster-whisper does not use PyTorch.

> does it do a lot of calculations before loading the model e.g. convert the whole thing? if yes, couldn't we cache something at this stage and re-use next time or similar?

Yes the model can be converted to another type when loaded. For example the faster-whisper models are published in float16, but they may be converted to something else when loaded. This step is relatively fast though.

If you know in advance the type to use for computation (e.g. int8), you could [reconvert the original models](https://github.com/guillaumekln/faster-whisper#model-conversion) in this format and then use this newly converted model.

> i have some feeling that the very "first" call to transcribe function takes longer than all others while runtime but i might be totally wrong here.

The first call always takes more time, but we are talking a few hundred milliseconds here.

**Comment by emcodem** [comment]
I am so sorry to have wasted your time on this. I did not check back with another PC/server before i opened this case and i took for granted that we have a slow startup time as another developer said that it is slower than const-me at startup as well.
Now i checked back on some very fast PC, (nvme, A5000...), it takes roughly
4 seconds overall with const-me
6 seconds overall with faster-whisper 

The reason for the slowness on my laptop was that i was too stupid to disable Power management maximum CPU state (min 5%, max 50%) before i did the benchmark. On my laptop the numbers are now:

7 seconds with faster-whisper
6 seconds with const-me

The time between the first and the next segment is now not visibly different anymore.

Here is some example script that i used for benchmarking:
```
import numpy as np
from datetime import datetime

print ("1: " + str(datetime.now()))

from faster_whisper import WhisperModel

print ("2: " + str(datetime.now()))

audiobuffer = np.fromfile("c:\\temp\\oh.wav", 
                          dtype=np.int16, 
                          count=16000*14,
                          sep='', 
                          offset=0).flatten().astype(
            np.float32) / 32768.0 

print ("3: " + str(datetime.now()))

model = WhisperModel("large-v2",local_files_only=True)#,device="cuda", compute_type="int8_float16") #device="cuda", compute_type="int8_float16"

print ("4: " + str(datetime.now()))

segments, info = model.transcribe(audiobuffer, beam_size=5)

segments = list(segments)

print ("5: " + str(datetime.now()))

print ("First Segment: " + str(segments[0].text))

print ("7: " + str(datetime.now()))

```
