### ISSUE TITLE
How to select a GPU?

### ISSUE THREAD

**Issue by EtienneAb3d** [guillaumekln/faster-whisper#4]
Whisper is using `model="cuda:0"` or `model="cuda:1"`
With faster-whisper, I get this error:
`ValueError: unsupported device cuda:1`

**Comment by guillaumekln** [comment]
Hello,

The linked PR is adding a `device_index` argument:

```python
model = WhisperModel(model_path, device="cuda", device_index=1, compute_type="float16")
```
