### ISSUE TITLE
Request for GSM Audio Support

### ISSUE THREAD

**Issue by dorlanpabon** [guillaumekln/faster-whisper#402]
Hello Faster-Whisper Team,

I'm a user of Faster-Whisper and I've been impressed by its capabilities. I'd like to kindly request the addition of GSM audio support to the project. This compression method could optimize bandwidth and storage use without significantly compromising audio quality. It would enhance the project's versatility, making it even more useful in resource-constrained environments.

Thank you for considering this request.

**Comment by guillaumekln** [comment]
Hi,

Have you tried using this audio format already? I think it may already work.

We use the PyAV library to decode the audio, and GSM is included in the list of supported codecs:

```
$ python3 -m av --codecs | grep gsm
 D.AIL. gsm                GSM
 D.AIL. gsm_ms             GSM Microsoft variant
```

**Comment by dorlanpabon** [comment]
Yes, GSM include the list
D:\xampp\htdocs\whisperWebrtc> python -m av --codecs |grep gsm
 D.AIL. gsm                GSM
 D.AIL. gsm_ms             GSM Microsoft variant
 
 Whiper only, work
 
 `import whisper

model = whisper.load_model("tiny", in_memory=True,
                           device="cpu")
result = model.transcribe("audio.gsm")
print(result["text"])`

Fasther-whisper - ERROR
`from faster_whisper import WhisperModel

model_size = "tiny"

model = WhisperModel(model_size)

segments, info = model.transcribe("audio.gsm")

print("Detected language '%s' with probability %f" %
      (info.language, info.language_probability))`
  
Error    
`  Python\Python310\lib\site-packages\faster_whisper\transcribe.py", line 241, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
    ...
   File "av\container\input.pyx", line 186, in decode
  File "av\container\input.pyx", line 146, in demux
  File "av\container\core.pyx", line 292, in av.container.core.Container.err_check
  File "av\error.pyx", line 336, in av.error.err_check
av.error.OSError: [Errno 5] I/O error: 'audio.gs`

thanks in advance for answering

Here I send you a little more information about my use case, thanks in advance for your help

**Comment by dorlanpabon** [comment]
Yes, GSM include the list
D:\xampp\htdocs\whisperWebrtc> python -m av --codecs |grep gsm
 D.AIL. gsm                GSM
 D.AIL. gsm_ms             GSM Microsoft variant
 
 Whiper only, work
 
 `import whisper

model = whisper.load_model("tiny", in_memory=True,
                           device="cpu")
result = model.transcribe("audio.gsm")
print(result["text"])`

Fasther-whisper - ERROR
`from faster_whisper import WhisperModel

model_size = "tiny"

model = WhisperModel(model_size)

segments, info = model.transcribe("audio.gsm")

print("Detected language '%s' with probability %f" %
      (info.language, info.language_probability))`
  
Error    
`  Python\Python310\lib\site-packages\faster_whisper\transcribe.py", line 241, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
    ...
   File "av\container\input.pyx", line 186, in decode
  File "av\container\input.pyx", line 146, in demux
  File "av\container\core.pyx", line 292, in av.container.core.Container.err_check
  File "av\error.pyx", line 336, in av.error.err_check
av.error.OSError: [Errno 5] I/O error: 'audio.gs`

thanks in advance for answering

Here I send you a little more information about my use case, thanks in advance for your help
