### ISSUE TITLE
Is Faster-whisper support --print-colors

### ISSUE THREAD

**Issue by tiennguyen12g** [guillaumekln/faster-whisper#404]
In whisper.cpp, I've used it. But I cannot find on  the document of faster-whisper that how to use "--print-colors".
If you know, please help me to achieve that.
Thank you.

**Comment by guillaumekln** [comment]
faster-whisper is a library and does not print the result in the console.

You could look at whisper-ctranslate2 which is built on top of faster-whisper and provides this option:

https://github.com/Softcatala/whisper-ctranslate2#print-colors

**Comment by tiennguyen12g** [comment]
[guillaumekln](https://github.com/guillaumekln) thank bro. hi
