### ISSUE TITLE
Why is not possible to use this tool offline?

### ISSUE THREAD

**Issue by fatualux** [guillaumekln/faster-whisper#405]
First of all, **thanks for your work**, this is an awesome tool, and in my case it works flawlessly.
It is much faster than _OpenAI's Whisper_, and I use it with _CTranslate2_.
I have a question. I have already downloaded the models, why must I be connected to the Internet while transcribing?
I see there is a request to Huggingface Hub or website... _OpenAI's Whisper_ did not request to have an active connection to the Internet.
Here is my traceback:

```
File "/home/fz/.virtualenv/faster-whisper/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
   
File "/home/fz/.virtualenv/faster-whisper/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/guillaumekln/faster-whisper-small/revision/main (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8aea777410>: Failed to resolve 'huggingface.co' ([Errno -3] Temporary failure in name resolution)"))
Done!
```
Thanks in advance for your support.

**Comment by guillaumekln** [comment]
What version of the library are you using? Since version 0.6 there should be no errors when the model is already downloaded and there is no internet connection.

**Comment by fatualux** [comment]
This is the version of the CLI application I am using 

`(faster-whisper) [fz@fzpc faster-whisper]$ whisper-ctranslate2 --version`
  whisper-ctranslate2 0.2.4

And these are the libraries in my virtual environment

`(faster-whisper) [fz@fzpc faster-whisper]$ cat <(ls lib/python3.11/site-packages)`
av
av-10.0.0.dist-info
av.libs
certifi
certifi-2022.12.7.dist-info
cffi
cffi-1.15.1.dist-info
_cffi_backend.cpython-311-x86_64-linux-gnu.so
charset_normalizer
charset_normalizer-3.1.0.dist-info
ctranslate2
ctranslate2-3.13.0.dist-info
ctranslate2.libs
_distutils_hack
distutils-precedence.pth
**faster_whisper
faster_whisper-0.5.1.dist-info**
filelock
filelock-3.12.0.dist-info
fsspec
fsspec-2023.4.0.dist-info
huggingface_hub
huggingface_hub-0.14.1.dist-info
idna
idna-3.4.dist-info
numpy
numpy-1.24.3.dist-info
numpy.libs
nvidia
nvidia_cublas_cu11-11.11.3.6.dist-info
nvidia_cudnn_cu11-8.9.0.131.dist-info
packaging
packaging-23.1.dist-info
pip
pip-23.1.2.dist-info
pkg_resources
__pycache__
pycparser
pycparser-2.21.dist-info
PyYAML-6.0.dist-info
requests
requests-2.30.0.dist-info
setuptools
setuptools-67.4.0.dist-info
setuptools-67.4.0.virtualenv
sounddevice-0.4.6.dist-info
_sounddevice.py
sounddevice.py
src
tokenizers
tokenizers-0.13.3.dist-info
tokenizers.libs
tqdm
tqdm-4.65.0.dist-info
typing_extensions-4.5.0.dist-info
typing_extensions.py
urllib3
urllib3-2.0.2.dist-info
_virtualenv.pth
_virtualenv.py
wheel
wheel-0.38.4.dist-info
wheel-0.38.4.virtualenv
whisper_ctranslate2-0.2.4.dist-info
_yaml
yaml

faster-whisper seems is version 0.5... maybe this is the problem then... I will try to update then I will let you know.

**Comment by fatualux** [comment]
It works, thank you.
I just activated my virtual environment and gave python -m pip install --upgrade faster-whisper; this solved the issue... I did not realize I was using an outdated version... this packages are not managed by my system's package manager, so I must remember to update them.
Thank you so much for your support!
