### ISSUE TITLE
Some of the improvements in Improve timestamp heuristics don't seem to be applying

### ISSUE THREAD

**Issue by archive-r** [guillaumekln/faster-whisper#410]
https://github.com/guillaumekln/faster-whisper/blob/1562b02345c8587eff1c6694b28c7f91f5c20ec2/faster_whisper/transcribe.py#L897

After `restore_speech_timestamps()`, some of the improvements made in https://github.com/guillaumekln/faster-whisper/pull/336 seem to be missing. 

https://github.com/guillaumekln/faster-whisper/blob/1562b02345c8587eff1c6694b28c7f91f5c20ec2/faster_whisper/transcribe.py#L817

Some of the improvements in this part change after `restore_speech_timestamps()`.  
When I checked before that function, the improvements were in place.
This function re-times the words, and it seems to lose some of the improvements in the process. It seems to be related to the speech chunk index, but I'm not sure.

I worked around this temporarily by applying the heuristic again in the final output, but I think there's a better way to do it. Please help.

**Comment by guillaumekln** [comment]
Don't we need to fix something in the code for this issue? Maybe the heuristics should be moved in a function that is called again after `restore_speech_timestamps`?

**Comment by archive-r** [comment]
Yes, you're right. I'll test it enough and then submit a PR.
Also, it seems that `restore_speech_timestamps` is causing the time interval between words to be so long in some cases that it would be better to separate the segments.
