### ISSUE TITLE
Compression ratio threshold is not met

### ISSUE THREAD

**Issue by vadi2** [guillaumekln/faster-whisper#413]
I'm seeing a few messages like this in the debug output - what do they mean?

```
DEBUG:faster_whisper:Processing segment at 07:27.560
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.0 (15.086957 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.2 (14.200000 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.4 (23.578947 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.6 (12.464286 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.8 (16.148148 > 2.400000)
DEBUG:faster_whisper:Log probability threshold is not met with temperature 1.0 (-1.898323 < -1.000000)
```

This occurs with the `large-v2` model and it causes text to repeat. It does not occur with the `medium` model.

**Comment by archive-r** [comment]
That message is output when the compression ratio exceeds the compression_ratio_threshold (the generated segment is too repetitive), which triggers the fallback. It's not an error message, so don't worry about it.

Also note that the output can vary depending on the model, so the debug message for the medium and large-v2 models will be different.

**Comment by emcodem** [comment]
Yeah it did not "cause" repetition but it means that it invested high efforts but still was not able to mitigate repetition :D

prompt_reset_on_temperature message is missing, did you disable this option?

**Comment by vadi2** [comment]
I didn't no, this is using the default code from the readme. 

There's not enough context to understand what the problem is about - for example, what does a temperature mean in this context? I'm familiar with it in the LLM world but it seems to be different here. Could someone help with a thorough explanation of what is going wrong, or some resources to read on this?

**Comment by archive-r** [comment]
The "[temperature](https://platform.openai.com/docs/api-reference/audio/createTranscription#audio/createTranscription-temperature)" here is, as far as I know, no different from that in LLM.

If the result of the model's first decoding attempt does not satisfy either the `log_prob_threshold` or the `compression_ratio_threshold`, the model will decode again, increasing the temperature by 0.2, and look for a satisfactory alternative. If this process is repeated and the temperature reaches 1 and no result is found that satisfies the above two conditions, the model returns the segment that it considers to be the best of the results.

This paper may give you more information.
https://arxiv.org/pdf/2212.04356.pdf

**Comment by emcodem** [comment]
> https://arxiv.org/pdf/2212.04356.pdf

Table 7 actually shows that temp fallback does not add any value if i interpret that right.
As far as i understood by now, in a GPT like model, it is useful to get a more colorful output if i might say so but as far as i understood, in the context of Whisper it is only for re-trying decode if the model returned complete garbage. 

I did little research on that yet, but i saw stuff like about 200 spaces returned in a single sequence (especially when non speec audio is being fed, so VAD is a good idea usually) - This is where compression ratio applies and triggers using the next temperature and therefore retry decoding. Once temperature is > 0, beam search is disabled and greedy is used.

Unfortunately i needed to learn by now only from testing and reading code and papers, i did not yet find any whisper or even inference specific advanced documentation.

**Comment by guillaumekln** [comment]
Note that faster-whisper implements the same logic as openai-whisper, which uses this fallback mechanism by default.
