### ISSUE TITLE
Unexpected behavior if a real language differs from the parameter.

### ISSUE THREAD

**Issue by exactstat** [guillaumekln/faster-whisper#418]
If an audio record has language that differs from the parameter, then I get transcription translated to the parameter language. 
**For example:** if I set English for a Dutch record, I get Dutch speech translated into English. 
It can be useful, but also it's better to parametrize that behavior. Some additional parameter is required to prevent transcribing if the language parameter differs from the detected language.

**Comment by guillaumekln** [comment]
> if I set English for a Dutch record

The Whisper models were not trained for this configuration so the behavior is undefined.

The language parameter should only be set when the audio language is known sure. In your case it seems better to keep the default behavior where the language is automatically detected.
