### ISSUE TITLE
Faster-whisper model not working with torchserve inside docker container

### ISSUE THREAD

**Issue by suryansh-noice** [guillaumekln/faster-whisper#426]
I am trying to create a docker image using faster-whisper which can be served using torchserve in production. 
have installed all the requirement inside docker - 
- openai-whisper 
- faster-whisper
- force-reinstall "faster-whisper @ https://github.com/guillaumekln/faster-whisper/archive/a4f1cc8f11433e454c3934442b5e1a4ed5e865c3.tar.gz"
- ffmpeg
have used "torch-model-archiver" to convert the faster-whisper model into archives for serving, also created custom_handler.py for inference, but when calling the docker container its unable to load the model. 
Code is failing at line while loading the model - **self.model = WhisperModel(model_dir)**
model_dir = path where .bin and .json files are present

**Comment by guillaumekln** [comment]
> Code is failing at line while loading the model 

What is the error?

**Comment by suryansh-noice** [comment]
there is no error, not any logs. I am logging the progress, so I can see its failing while loading model **WhisperModel(path)**

**Comment by suryansh-noice** [comment]
later on I have tried with flask, its able to load the model but while calling transcribe method, I am giving file path as URL (tried with public URL and gsutil URI) both are giving error under script 'faster_whisper/audio.py' - >
Error :
line 45, in decode_audio
    with av.open(input_file, metadata_errors="ignore") as container:
    line 401, in av.container.core.open
    line 272, in av.container.core.Container.__cinit__
    line 292, in av.container.core.Container.err_check
   in av.error.err_check
av.error.ProtocolNotFoundError: [Errno 1330794744] Protocol not found: 'gs://bucket-name/folder/file.wav'

**Comment by guillaumekln** [comment]
The transcribe method does not accept URL directly. See the docstring of the first argument:

> Path to the input file (or a file-like object), or the audio waveform.

**Comment by guillaumekln** [comment]
You need to use CUDA 11, not CUDA 12. Try this image: `nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04`.
