### ISSUE TITLE
ProxyError SSLError SSLEOFError: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by Purfview** [guillaumekln/faster-whisper#429]
It's not my issue,  reposing it from there -> https://github.com/Purfview/whisper-standalone-win/issues/59

![image](https://github.com/Purfview/whisper-standalone-win/assets/47836815/14335dbb-3d63-42ca-85da-96f61687f38d)

"Our region requires vpn to access the extranet, which prevents the software from accessing huggingface properly. can you add options to support proxies?"

**Comment by phineas-pta** [comment]
i think it's `huggingface_hub` problem

on other hand maybe he can ask someone to upload checkpoints to other clouds he has access ?

**Comment by Purfview** [comment]
It's `huggingface_hub` or `urllib3` or the user's proxy configuration.

Maybe  `huggingface_hub`  could retry http instead of https on ProxyError when all retries failed, something like [this PR](https://github.com/huggingface/huggingface_hub/pull/1022).

**Comment by Purfview** [comment]
Looks like the user is not interested in solving this.

**Comment by Purfview** [comment]
Actually bug was in std lib urllib.
There you can find info how to fix it: https://github.com/Purfview/whisper-standalone-win/issues/59
