### ISSUE TITLE
Install Faster Whisper off line

### ISSUE THREAD

**Issue by Dvk2002** [guillaumekln/faster-whisper#437]
Good day. I try to use Faster Whisper in Kaggle competition, but I can't install it off line.
I've downloaded archive with last version, but get mistakes like that 
Could not find a version that satisfies the requirement av==10.*
Is there anyway to resolve it ?

**Comment by Purfview** [comment]
You need to download all requirements, and the requirements of the requirements. ;)

If you are on Windows then you can use [Standalone Faster-Whisper](https://github.com/Purfview/whisper-standalone-win).

**Comment by Dvk2002** [comment]
No Kaggle on linux. It looks like unreal task.

**Comment by Dvk2002** [comment]
Yes, I've done it. Some manipulations with version and names. Thank you.

**Comment by etlweather** [comment]
Are you trying to use it offline, or install it on a computer that isn't online?

For the later, you could use an online computer, create a virtual environment, install all the requirements and then copy the virtual environment to the offline computer.

**Comment by guillaumekln** [comment]
This is not specific to faster-whisper but here's the correct way to do it.

1. Download all dependencies in a directory:

```
pip wheel -w wheelhouse/ faster-whisper
```

2. Install faster-whisper from this local directory:

```
pip install --no-index --find-links wheelhouse/ faster-whisper
```
