### ISSUE TITLE
Inference on long files

### ISSUE THREAD

**Issue by databill86** [guillaumekln/faster-whisper#44]
Hello, 

Thank you for this great library! 
Is there any way we can chunk the initial audio into shorter samples, let's say 50 seconds each, run inference on those, and end up with a final reconstruction. 
I came across this [article](https://huggingface.co/blog/asr-chunking#simple-chunking) and I wonder if it's possible to get it working here. 
Any ideas if this is possible ?

**Comment by guillaumekln** [comment]
Hi,

The Whisper transcription loop already handles long files using a sliding 30-second window while keeping the context. So you don't need to do anything to transcribe long files.

**Comment by databill86** [comment]
Thank you. So is it normal that the transcription time is long for long files ?

**Comment by guillaumekln** [comment]
Yes, the transcription time depends on the audio file duration. Long files will take longer.

**Comment by databill86** [comment]
Sorry I closed and reopened the issue. I just have one last thing about the longer files. 
If we use the "gpu" as a device, is there any way we can avoid OOM for these longer files ?

**Comment by databill86** [comment]
It's a NVIDIA GeForce GTX 1070 Ti 8Go, I was running the large-v2 model on a 18min file. But even with 4min file I have OOM.

**Comment by guillaumekln** [comment]
Try running the model with 8-bit quantization:

```python
model = WhisperModel(model_path, device="cuda", compute_type="int8")
```
