### ISSUE TITLE
inference slowed down with `word_timestamps=True`

### ISSUE THREAD

**Issue by eschmidbauer** [guillaumekln/faster-whisper#45]
Hi,
I have a simple script to run inference on a wav file. I noticed when `word_timestamps=True`, the processing time is much longer. 
I'm using the same wav file in each of these cases, you can see duration below for each:

```
model = WhisperModel(model_path, "cpu", compute_type="int8", cpu_threads=4)
segments, info = model.transcribe(input, word_timestamps=True, beam_size=1)
```
```
OMP_NUM_THREADS=4 python inference.py
duration: 310.73524594306946s
```

```
model = WhisperModel(model_path, "cpu", compute_type="int8", cpu_threads=4)
segments, info = model.transcribe(input, word_timestamps=False, beam_size=1)
```
```
OMP_NUM_THREADS=4 python inference.py
duration: 225.86893439292908s
```

Is this expected? Or is there some optimization that could be done for word-level timestamps.

**Comment by guillaumekln** [comment]
Hi,

Yes this is expected. The model is run a second time to resolve the alignment between the text and the audio. The same approach is implemented in openai/whisper.

**Comment by eschmidbauer** [comment]
Makes sense, thank you for the quick response!

**Comment by guillaumekln** [comment]
The processing time with `word_timestamps=True` should be reduced in the latest version 0.3.0. The encoder output is reused and only the decoder is run a second time.
