### ISSUE TITLE
Bug since today (0.8.0 ?) with load_model

### ISSUE THREAD

**Issue by dwidoo** [guillaumekln/faster-whisper#455]
`[/usr/local/lib/python3.10/dist-packages/whisperx/asr.py](https://zodbzjljtq-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20230831-060138_RC00_561609135#) in load_model(whisper_arch, device, device_index, compute_type, asr_options, language, vad_options, model, task, download_root)
     87     del default_asr_options["suppress_numerals"]
     88 
---> 89     default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options)
     90 
     91     default_vad_options = {

TypeError: TranscriptionOptions.__new__() missing 3 required positional arguments: 'repetition_penalty', 'no_repeat_ngram_size', and 'prompt_reset_on_temperature'`

**Comment by guillaumekln** [comment]
The error is coming from WhisperX and you should open the issue there. There are new options in the structure `TranscriptionOptions`. They should probably implement this function directly or it will break each time there is a new option.

**Comment by dwidoo** [comment]
thank you Guillaume
and congrats for this fantastic work!
