### ISSUE TITLE
Incompatible with CUDA v12.1

### ISSUE THREAD

**Issue by pandruszkow** [guillaumekln/faster-whisper#47]
OS: Arch Linux x86_64, python-numpy-1.24.2, CUDA v12.1, all other system packages at latest versions.
Using a GPU for transcription

## Steps to reproduce
1. Install `cuda-12.1.0-1-x86_64.pkg.tar.zst` via `pacman`
2. Attempt to run transcription using the sample Python snippet provided

## Expected behaviour

Transcription begins as with CUDA v11.8 installed

## Actual behaviour

An error message is shown in the output:
```
Traceback (most recent call last):
  File "faster-whisper/faster.py", line 15, in <module>
    segments, info = model.transcribe(sys.argv[1], beam_size=5)
  File "faster_whisper/transcribe.py", line 207, in transcribe
    results = self.model.detect_language(input)
RuntimeError: Library libcublas.so.11 is not found or cannot be loaded
```

## Workaround
```sh
cd /var/cache/pacman/pkg
# downgrade CUDA and dependecies to CUDA v11.8, using older package files
sudo pacman -U cuda-11.8.0-1-x86_64.pkg.tar.zst cudnn-8.6.0.163-1-x86_64.pkg.tar.zst
```

**Comment by guillaumekln** [comment]
[As mentioned in the README](https://github.com/guillaumekln/faster-whisper#installation), the Python module `ctranslate2` requires the library cuBLAS 11.x which is installed with CUDA 11.x.

Support for CUDA 12.x is not planned at the moment.

**Comment by pandruszkow** [comment]
Makes sense. Would you accept a README change that makes this information more prominent? I know it'd have saved me some time if I hadn't missed this info.

**Comment by guillaumekln** [comment]
Sure, feel free to send a PR to improve the README.

**Comment by Geremia** [comment]
@guillaumekln Why isn't CUDA 12.x support planned?

**Comment by guillaumekln** [comment]
If we update the CTranslate2 binaries to use CUDA 12, it will break all existing users so this is a change we would like to avoid for now. A possible solution is to release 2 versions of the binaries, one for CUDA 11 and another for CUDA 12. However, we don't have the resources to set that up and maintain it.

Given CUDA 11 applications still work on newer graphic cards, CUDA 12 support for the released binaries is not a priority.

**Comment by Geremia** [comment]
@guillaumekln Are there instructions how I can build it myself for CUDA 12?

**Comment by Geremia** [comment]
@Geremia  https://github.com/OpenNMT/CTranslate2/blob/master/docs/installation.md#install-from-sources

**Comment by guillaumekln** [comment]
You can also check out the [Dockerfile](https://github.com/OpenNMT/CTranslate2/blob/master/docker/Dockerfile) which acts as a complete build example.
