### ISSUE TITLE
Support Baichuan2?

### ISSUE THREAD

**Issue by lx0126z** [guillaumekln/faster-whisper#472]
Baichuan2 is a generative model similar to llama, I find the following two differences:
- 1. qkv merge as W_pack, so i change the file  /ctranslate2/converters/transformers.py
![image](https://github.com/guillaumekln/faster-whisper/assets/122880585/f48aa58b-cc8a-4472-a27e-46ffd887afeb)
- 2. rotary changes to alibi, so i change the file  /ctranslate2/converters/transformers.py
![image](https://github.com/guillaumekln/faster-whisper/assets/122880585/4949291e-f817-44f3-a1d3-a847008452d7)

But I found that the conversion only worked on simple sentences, complex sentences would not work.

Could you help me or is there a plan to support Baichuan2?

- link
https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat
https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/blob/main/modeling_baichuan.py

**Comment by guillaumekln** [comment]
You should create this issue in https://github.com/OpenNMT/CTranslate2/.
