### ISSUE TITLE
How to run faster_whisper on multiple GPUs？

### ISSUE THREAD

**Issue by lazyseacow** [guillaumekln/faster-whisper#473]
thanks for your answers. In the previous issues, I saw the answer about CPU multithreadings running, but I wanted to see how to run faster on multiple gpus? Can you give me some examples? @guillaumekln

**Comment by guillaumekln** [comment]
Read #100 again. It is explained how to transcribe multiple files using multiple GPUs.

If you want to use multiple GPU for a single file, this is not supported out of the box. But you could always split the file into multiple parts and transcribe the parts on multiple GPUs as shown in #100.
