### ISSUE TITLE
why faster-whiser vad default parameters are much different from silero-vad

### ISSUE THREAD

**Issue by iorilu** [guillaumekln/faster-whisper#477]
follwing are code I find for comparation 

https://github.com/snakers4/silero-vad/blob/563106ef8cfac329c8be5f9c5051cd365195aff9/utils_vad.py#L164

```
def get_speech_timestamps(audio: torch.Tensor,
                          model,
                          threshold: float = 0.5,
                          sampling_rate: int = 16000,
                          min_speech_duration_ms: int = 250,
                          max_speech_duration_s: float = float('inf'),
                          min_silence_duration_ms: int = 100,
                          window_size_samples: int = 512,
                          speech_pad_ms: int = 30,
                          return_seconds: bool = False,
                          visualize_probs: bool = False,
                          progress_tracking_callback: Callable[[float], None] = None):

```

https://github.com/guillaumekln/faster-whisper/blob/e94711bb5cee175d8165a22fd9ce03ef295c7170/faster_whisper/vad.py#L34
```
    threshold: float = 0.5
    min_speech_duration_ms: int = 250
    max_speech_duration_s: float = float("inf")
    min_silence_duration_ms: int = 2000
    window_size_samples: int = 1024
    speech_pad_ms: int = 400
```

from above code , I see some big difference

```
in silero-vad
speech_pad_ms = 30
min_silence_duration_ms = 100
window_size_samples = 512

in faster-whisper vad
speech_pad_ms = 400
min_silence_duration_ms = 2000
window_size_samples = 1024
```

is there any reason to choose these values ? 

as I am trying to find best combination of parameters  to avoid some issue like repeation , hallucination .etc

**Comment by guillaumekln** [comment]
The default value for `min_silence_duration_ms` in Silero VAD is very small, so many small pauses would be removed from the audio. The issue is that Whisper was not trained on such "compressed" audio so this may impact the transcription accuracy. The default parameters in faster-whisper are more conservative and try to remove longer silences (at least 2 seconds).

Same reason for `speech_pad_ms`. Whisper was not trained on speech ending abruptly or speech that immediately follow each other. So we try to keep some samples before and after each speech section.

**Comment by iorilu** [comment]
> The default value for `min_silence_duration_ms` in Silero VAD is very small, so many small pauses would be removed from the audio. The issue is that Whisper was not trained on such "compressed" audio so this may impact the transcription accuracy. The default parameters in faster-whisper are more conservative and try to remove longer silences (at least 2 seconds).
> 
> Same reason for `speech_pad_ms`. Whisper was not trained on speech ending abruptly or speech that immediately follow each other. So we try to keep some samples before and after each speech section.

thanks for the explaination 

if I want to use vad to help solve issues like  repeation , hallucination , do you have any suggestions about the parameters of vad?

**Comment by guillaumekln** [comment]
> if I want to use vad to help solve issues like repeation , hallucination , do you have any suggestions about the parameters of vad?

No idea. If I knew the best parameters to solve the repetition and hallucination issue, they would already be used as default parameters.

**Comment by guilhermehge** [comment]
@guillaumekln what about the window_size_samples? That one I couldn't figure out why you increased the value..

**Comment by guillaumekln** [comment]
Since we are not looking to detect with very high precision the speech boundaries, we can increase `window_size_samples` to increase the execution speed.

**Comment by guilhermehge** [comment]
Thanks for your reply, @guillaumekln. It does make sense.
