### ISSUE TITLE
usage of new added parameters (repetition_penalty  and no_repeat_ngram_size)

### ISSUE THREAD

**Issue by iorilu** [guillaumekln/faster-whisper#478]
about the two new added parameters  in v0.8.0

I assume these are used to handle the repetition issue , I am glad to see it

the question is what are the suitable values for it

`repetition_penalty to penalize the score of previously generated tokens (set > 1 to penalize)`
for this one , it's float value type ,  I want to know the possible magnitude of it , i mean should I try small step like 1.1, 1.2, 1.3 or 
something bigger like 1.0 , 2.0 , 3.0

`no_repeat_ngram_size`
for this , since it's int value , I assume it should be some value like 1,2 ,3

and any reccomendation of these values ?

**Comment by guillaumekln** [comment]
* `repetition_penalty` should be a small value like 1.1, 1.2, etc.
* `no_repeat_ngram_size` is an integer value: 2 for 2-gram, 3 for 3-gram, etc.

The general recommendation is to not change these parameters. They are not used in the reference implementation from OpenAI. But the parameters are available for experimentation.

**Comment by andrealorenzon** [comment]
I also have an issue since the last week. I'm using faster-whisper in a container, and I get this error:
```
whisper           |   File "/app/.venv/lib/python3.10/site-packages/whisperx/asr.py", line 92, in load_model
whisper           |     default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options)
whisper           | TypeError: TranscriptionOptions.__new__() got an unexpected keyword argument 'repetition_penalty'
```

**Comment by guillaumekln** [comment]
Update faster-whisper to the latest version.

**Comment by andrealorenzon** [comment]
> Update faster-whisper to the latest version.

Problem solved. Thank you!
