### ISSUE TITLE
I have a problem with the timing of the subtitles

### ISSUE THREAD

**Issue by ctimict** [guillaumekln/faster-whisper#482]
Hi everybody
I'm a new user, I'm having problems with my movie subtitles.
Previously I used whisper my file output format would be .srt and the time would be, for example:
```
1
00:00:00,000 --> 00:00:02,580
新娘手中的捧花,她会送给谁呢?

2
00:00:02,720 --> 00:00:05,160
我想把捧花送给我的好朋友,龙龙!
```

but when I use fast-whisper I only get the command lines, and the time format is, for example:
```
[0.00s -> 2.00s] 快快快,趁他们人还没来,别动!
[2.00s -> 3.00s] 不要动!
[3.00s -> 6.00s] 这个炸弹有水平装置,一动就炸了
```
and in this format I cannot make movie subtitles
Is there a way to format the time similar to whisper
first
```
00:00:00,000 --> 00:00:02,580
2
00:00:02,720 --> 00:00:05,160
3
00:00:05,460 --> 00:00:14,520
4
00:00:17,460 --> 00:00:18,500
```

If so please let me know, I am using the command as shown in your instructions.

`from faster_whisper import WhisperModel

model_size = "large-v2"

# Run on GPU with FP16
model = WhisperModel(model_size, device="cuda", compute_type="float16")

# or run on GPU with INT8
# model = WhisperModel(model_size, device="cuda", compute_type="int8_float16")
# or run on CPU with INT8
# model = WhisperModel(model_size, device="cpu", compute_type="int8")

segments, info = model.transcribe("audio.mp3", beam_size=5)

print("Detected language '%s' with probability %f" % (info.language, info.language_probability))

for segment in segments:
     print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))`
     
    Thank You !

**Comment by guillaumekln** [comment]
faster-whisper does not have a command line that can write SRT files.

See the following projects that are built on top of faster-whisper and provide a command line similar to openai-whisper:

* https://github.com/Softcatala/whisper-ctranslate2
* https://github.com/Purfview/whisper-standalone-win

**Comment by ctimict** [comment]
My friend helped solve this problem with the following method, I share it here so that anyone who has the same problem as me can use this code to solve the problem.

`import os
import time
from faster_whisper import WhisperModel

#Path to input video
video_directory = r"E:\Youtube\Hai_Trung_Quoc\@cxldb"

# Path to output file .srt
output_directory = r"E:\Youtube\Hai_Trung_Quoc\@cxldb"

# Đường dẫn đến model và các cài đặt khác
model_size = "large"
device = "cuda"
compute_type = "float16"
beam_size = 5

# Set language (ex: Chinese)
language = "zh"

# Lấy danh sách tất cả các tệp trong thư mục video_directory
video_files = [f for f in os.listdir(video_directory) if os.path.isfile(os.path.join(video_directory, f)) and f.lower().endswith((".mp4", ".mkv", ".avi", ".mp3", ".ts"))]

# Tổng số video đầu vào
total_videos = len(video_files)

# Số video đã xử lý và số video chưa xử lý
processed_videos = 0
unprocessed_videos = 0

# Tạo và cấu hình model
model = WhisperModel(model_size, device=device, compute_type=compute_type)

# Thực hiện xử lý cho từng tệp video lần lượt
for video_file in video_files:
    # Xác định đường dẫn đầy đủ đến tệp video
    video_path = os.path.join(video_directory, video_file)
    
    # Tạo tên tệp đầu ra dựa trên tên tệp video đầu vào
    output_file = os.path.splitext(video_file)[0] + ".srt"
    output_path = os.path.join(output_directory, output_file)

    # Bắt đầu tính thời gian xử lý
    start_time = time.time()

    # Thực hiện chuyển đổi và ghi kết quả vào tệp đầu ra dưới định dạng SRT
    segments, _ = model.transcribe(video_path, beam_size=beam_size, language=language, word_timestamps=True)
    with open(output_path, "w", encoding="utf-8") as file:
        counter = 1
        for segment in segments:
            start_minutes = int(segment.start // 60)
            start_seconds = int(segment.start % 60)
            start_milliseconds = int((segment.start - int(segment.start)) * 1000)
            end_minutes = int(segment.end // 60)
            end_seconds = int(segment.end % 60)
            end_milliseconds = int((segment.end - int(segment.end)) * 1000)
            formatted_start = f"{start_minutes:02d}:{start_seconds:02d}.{start_milliseconds:03d}"
            formatted_end = f"{end_minutes:02d}:{end_seconds:02d}.{end_milliseconds:03d}"

            file.write(f"{counter}\n")
            file.write(f"{formatted_start} --> {formatted_end}\n")
            file.write(f"{segment.text}\n\n")
            counter += 1

    # Tính thời gian xử lý cho video này
    end_time = time.time()
    processing_time = end_time - start_time

    # In thông báo khi hoàn thành xử lý cho một video và cập nhật số video đã xử lý và chưa xử lý
    processed_videos += 1
    unprocessed_videos = total_videos - processed_videos
    print(f"Xử lý xong video {processed_videos}/{total_videos}: {video_file}")
    print(f"Thời gian xử lý: {processing_time:.2f} giây")
    print(f"Số video chưa xử lý còn lại: {unprocessed_videos}\n")
`
