### ISSUE TITLE
TypeError: WhisperModel.transcribe() got an unexpected keyword argument 'word_timestamps'

### ISSUE THREAD

**Issue by benjamin-nguyen** [guillaumekln/faster-whisper#49]
**Description:** 
While running the code, I encountered an error with the following message: "TypeError: WhisperModel.transcribe() got an unexpected keyword argument 'word_timestamps'". The error occurs when trying to transcribe an audio file with the 'word_timestamps' argument set to True.

**Steps to Reproduce:**
1. Install the required dependencies for the code snippet: faster_whisper and torch.
2. Download the pre-trained WhisperModel from the given model_path.
3. Run the code snippet with an audio file named "audio.mp3".

**Expected Result:**
The code should transcribe the audio file and print the start and end times of each word in the audio file.

**Actual Result:**
The code throws a TypeError with the message "WhisperModel.transcribe() got an unexpected keyword argument 'word_timestamps'".

**Error Message:**
TypeError: WhisperModel.transcribe() got an unexpected keyword argument 'word_timestamps'

**Code Snippet:**
```
from faster_whisper import WhisperModel
import torch

model_path = "whisper-large-v2-ct2/"

# Use GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"
compute_type = "float16" if torch.cuda.is_available() else "int8"

model = WhisperModel(model_path, device=device, compute_type=compute_type)   

# Transcribe video and translate to English
with torch.no_grad():
    segments, _ = model.transcribe("audio.mp3", word_timestamps=True)

for segment in segments:
    for word in segment.words:
        print("[%.2fs -> %.2fs] %s" % (word.start, word.end, word.word))
```

**Comment by guillaumekln** [comment]
How did you install faster-whisper? It seems you don't have the latest version installed.

**Comment by guillaumekln** [comment]
Closing this issue. You just need to update the module to fix the error.

**Comment by anirudhpk** [comment]
i am getting the same error. which version do we need to install?

**Comment by trungkienbkhn** [comment]
@anirudhpk , Have you tried with the latest version 1.0.2 yet?

**Comment by anirudhpk** [comment]
no but i am using API to translate and getting this error.
