### ISSUE TITLE
Run with onnxruntime-gpu not working for faster_whisper

### ISSUE THREAD

**Issue by guilhermehge** [guillaumekln/faster-whisper#493]
I am trying to use faster_whisper with pyannote for speech overlap detection and speaker diarization, but the pyannote's new update 3.0.0, it will need onnxruntime-gpu to run the diarization pipeline with the new embedding model.

Installing both onnxruntime (from faster_whisper) and onnxruntime-gpu (from pyannote), causes a conflict and onnx redirects to CPU only.

I tried uninstalling onnxruntime and forcing the reinstall of onnxruntime-gpu and faster_whisper is no longer working.

Is it possible to use onnxruntime-gpu for faster_whisper?

**Comment by phineas-pta** [comment]
u should not have both `onnxruntime` and `onnxruntime-gpu`, it always default to cpu

installing `onnxruntime-gpu` alone should be enough, `faster_whisper` uses it for silero VAD but always cpu https://github.com/guillaumekln/faster-whisper/blob/master/faster_whisper/vad.py#L260

the caveat with `onnxruntime-gpu` is u must properly install cuda + cudnn at system level

**Comment by guilhermehge** [comment]
But can silero vad run with onnxruntime-gpu? To do that I believe I might need to change the requirements of faster whisper so it does not install onnxruntime, right?

**Comment by phineas-pta** [comment]
it's possible to run silero vad with `onnxruntime-gpu`, see my comment https://github.com/guillaumekln/faster-whisper/issues/364#issuecomment-1645272083

idk u using what version of `onnxruntime` but for latest version better use cuda 11.8 https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

**Comment by guilhermehge** [comment]
Thanks for that, phineas!

Let me ask you something else. Faster_whisper's transcribe is already taking up 99% of my GPU, if I run VAD on GPU as well, would it be a problem or would it take longer due to that? I read through transcribe.py and I see that SileroVAD is only used within the transcribe function and the segments are a generator, so it should not overload the GPU. Am I correct?

**Comment by phineas-pta** [comment]
hmm seem like i misread your previous comment, silero vad should work with `onnxruntime-gpu`, default to cpu, my code is just a tweak to make it work on gpu but not absolute necessity

it always create new onnx session no matter gpu or cpu, but take more time to load to gpu i guess (loading time > processing time), maybe need a longer audio to test for actual speed up

**Comment by guilhermehge** [comment]
Yes, at first I did want to run it with the onnxruntime-gpu library but using the Silero VAD on CPU, but since you posted the code, I tried running it on the GPU, but session time increases the time too much for small audios, so it's not worth it in most cases, better to use CPU with more threads active.

I'm trying to run this code along with pyannote's 3.0 diarization pipeline, which requires onnxruntime-gpu, so faster_whisper's requirements were causing a conflict.

I'm using a docker container in a pod with GPU orchestrated by kubernetes, there I'm building an image based on `nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04`. I created this issue because I was testing the onnxruntime-gpu in this environment inside a jupyter-notebook but the kernel kept dying when trying to run inference with whisper, and I couldn't figure out why, but then, later, I ran a .py complete code outside jupyter and it worked fine. I still don't know why the jupyter notebook kernel keeps dying with this library.

**Comment by phineas-pta** [comment]
should had shared the config info since the beginning to avoid talking to nowhere 😅

so the actual problem is jupyter kernel crash, u have logs ?

**Comment by guilhermehge** [comment]
I'll be running some tests and I'll comeback here with the results. For now, I don't have any logs, I killed the pod before accessing them.

**Comment by thomasmol** [comment]
Hi, I am having the same issue: I need to run `onnxruntime-gpu` but I can't easily uninstall the cpu version since I am using Cog and pushing it to Replicate. Meaning I can't change the code as per https://github.com/guillaumekln/faster-whisper/issues/364#issuecomment-1645272083 , or I don't know how at least. Any ideas how to force my build to use `onnxruntime-gpu` and remove `onnxruntime`?

**Comment by thomasmol** [comment]
I created a pull request that fixes this issue: https://github.com/guillaumekln/faster-whisper/pull/499. You can try it by importing `git+https://github.com/thomasmol/faster-whisper.git@master`.

**Comment by phineas-pta** [comment]
your PR is very likely to be rejected, it only works with nvidia gpu, meanwhile `faster-whisper` is cross-platform, that's why my code snippet just stay as it is instead of send PR

**Comment by thomasmol** [comment]
Thanks for the heads up

**Comment by guilhermehge** [comment]
I don't recommend running silero vad on GPU either, since it takes longer to instantiate a session than the CPU version. For shorter audios, it increases the overall time significantly. I've had had 2s on CPU versus 7s on GPU for certain audios.

**Comment by thomasmol** [comment]
@guilhermehge yes I did the same at works! Maybe we could create a fork `faster_whisper_gpu` and have a gpu only version?

**Comment by remic33** [comment]
It seems that the current pyannote version (3.0.1) is not working with the current faster_whisper version. Any idea solution on that?

**Comment by guilhermehge** [comment]
It is. I am using it atm. How are you implementing it? Docker? Colab? Locally w/o docker?

**Comment by guilhermehge** [comment]
Did you create a virtual environment to do that?

Can you further explain your problem so we can debug it?

**Comment by remic33** [comment]
It worked previously, i know it because I was using it and I was part of thoses discussions. You just needed to add some packages. But maybe with onnx gpu it do not anymore. 
Thanks for your help !

**Comment by guilhermehge** [comment]
> Hello was this solved as of today 11th of August 2025?

Yes, pyannote fixed it, so no need to use onnxruntime-gpu anymore

**Comment by guilhermehge** [comment]
> Could you please explain on how to merry onnxruntime-gpu and onnxruntime? Need to run faster-whisper on GPU and Silero VAD on CPU.

You basically cannot have both installed in your environment. If you need onnxruntime-gpu in any other library, you should only have onnxruntime-gpu. What I did back then was change the requirements of faster-whisper (I cloned it and made my own version of it in a private azure artifacts environment) and install pyannote 3.0.0 that required onnxruntime-gpu. If you're trying to use pyannote, the latest version does not require onnxruntime anymore, I believe changed the code to some pytorch stuff.

In faster-whisper, onnxruntime is ONLY USED for silero VAD, you don't need the onnxruntime-gpu for whisper, so install only onnxruntime and you should be good to go.
