### ISSUE TITLE
Apple Neural Engine on M1 Macs? 

### ISSUE THREAD

**Issue by maxcribe** [guillaumekln/faster-whisper#51]
First of all, this is amazing work. It mops the floor with vanilla Whisper on Apple M1 chips. 

However, I noticed that it only supports float32 types on Apple M1. All types seem to fallback to that due to ctranslate2 presumably. I read that Apple Neural Engine supports fp16, int16 and int8 types. Any chance we can support those via ANE? That might take the performance to an even higher level 

thanks!

**Comment by guillaumekln** [comment]
As far as I know, the ANE can only be used via high-level tools like CoreML. This would require re-implementing the model with CoreML which I don't plan to do.

It would be great if Apple provides an API to use the ANE directly (e.g. run a matrix multiplication on the ANE), but I don't know if it will ever happen.

**Comment by maxcribe** [comment]
True, fasterwhisper is amazing even without it! 

Can I ask if there are any expected differences in the output and/or performance while using int8 vs int16 vs float32?

**Comment by guillaumekln** [comment]
In the [benchmark results](https://github.com/guillaumekln/faster-whisper#benchmark) you can see the performance improvement when using int8 quantization on an Intel CPU.

In terms of transcription quality, we previously measured a 0.1 drop in WER when using int8 instead of float32.
