### ISSUE TITLE
amd and/or apple metal/mps acceleration

### ISSUE THREAD

**Issue by BBC-Esq** [guillaumekln/faster-whisper#515]
Does faster-whisper support either AMD or metal/mps acceleration out of the box?  I noticed on the ctranslate2 instruction page it states that it can be built with Apple's Acceleration, but faster-whisper is a separate repository and so it's not clear from the readme whether faster-whisper supports apple's metal/mps and/or "Accelerate?"  I'm presuming from the ctranslate2 instructions that faster-whisper also doesn't support AMD GPU acceleration?

Editing this response to also ask about oneDNN, Openblas, and Ruy, which are all indicated as "off" in the instructions to compile Ctranslate2, but not mentioned on the faster-whisper respository.

Thanks!

**Comment by phineas-pta** [comment]
"off" is default value but u can change to your need when compiling

**Comment by BBC-Esq** [comment]
"off" pertains to which of my multiple questions??

**Comment by BBC-Esq** [comment]
I might be misunderstanding, but...The only instructions I'm aware of regarding "compiling" pertain to Ctranslate2, not faster-whisper.  If I use ```pip install faster-whisper``` does it come with the certain backends enabled or not?  Faster-whisper uses Ctranslate2, but it is itself a separate library.  So my questions are whether faster-whisper has the backends enabled, and if not, how can i enable them?

**Comment by BBC-Esq** [comment]
Thank you!  That answers my questions.  Now, faster-whisper automatically installs ctranslate2 as part of its dependencies in ```requirements.txt``.  Do I need to modify installation ```requirements.txt``` to NOT install ctranslate2 since I already compiled it manually?  In other words, I don't want my ```pip install faster-whisper``` to accidentally override my manually-compiled version of ctranslate2?

**Comment by phineas-pta** [comment]
if u already got latest ctranslate2 compiled and installed as python package then no overwrite to worry about

**Comment by BBC-Esq** [comment]
Thanks again sir!  Will close this issue out.

**Comment by phineas-pta** [comment]
i don't use mac so I don't have hands-on experience 

but it should be able to work fine
