### ISSUE TITLE
Word confidence scores

### ISSUE THREAD

**Issue by David-Pye** [guillaumekln/faster-whisper#52]
Thanks for the excellent work on this package. A quick query, I've been looking at the following suggestions as to how to get word confidence from vanilla Whisper in grey mode. Could you provide some pointers as to how to implement this in the faster whisper / ctranslate2 implementation? 
As the code here deviates significantly.  github.com/openai/whisper/discussions/284

**Comment by guillaumekln** [comment]
When enabling word-level timestamps, the returned `Word` structure contains the attribute `probability`.

```python
segments, _ = model.transcribe("audio.mp3", word_timestamps=True)

for segment in segments:
    for word in segment.words:
        print(word.word, word.probability)
```

Is it what you are looking for?

**Comment by David-Pye** [comment]
Kind of, though I was winding if it's possible to extract this information without the time overhead of word level timings

**Comment by guillaumekln** [comment]
Currently this is not possible from Python. The method `Whisper.generate` from CTranslate2 only returns the global sequence score. There is an open issue to also return the token scores: https://github.com/OpenNMT/CTranslate2/issues/1077
