### ISSUE TITLE
Support for variable size chunks

### ISSUE THREAD

**Issue by vackosar** [guillaumekln/faster-whisper#54]
I can see that now only 30 second chunks are supported by the CTranslate2 model.  Shorter chunks are padded to 30s such that `model.generate` can accept exclusively `[batch_size, 80, 3000]` inputs.

In some real-time applications like shorter chunks may be used and the original Whisper model supports shorter chunks despite being trained on 30s. Would it be possible to allow shorter chunks for faster inference in contrast to when always padding to 30s?

**Comment by guillaumekln** [comment]
As far as I know, all Whisper implementations pad the input to 30 seconds. Do you know an implementation that does differently?

**Comment by vackosar** [comment]
You are right the original implmentation is using padding. It is not clear to me why. Convnet and transformer can take any sequence length. Perhaps the presence of positional embeddings on the otherwise empty padded inputs helps? Or perhaps it was just easier? Language model mostly don't care about the size of input.
[The paper](https://arxiv.org/pdf/2212.04356.pdf) does not mention the padding.

**Comment by guillaumekln** [comment]
Probably it was just easier and there is no need to do any masking on the encoder side.
