### ISSUE TITLE
long files are leading to memory crashes (on gpu)

### ISSUE THREAD

**Issue by westhecool** [guillaumekln/faster-whisper#550]
I am trying to transcribe long files. When it gets to about an hour or so, there's about a 50% chance that it will crash with the error `CUDA failed with error out of memory`. I have a Nvidia RTX 3070 which has eight gigabytes of VRAM which should be sufficient, right? When I am transcribing, VRAM usage stays below 65%. It is very odd that it says that it is running out. I have tried both int8 and float16 but it doesn't seem to change anything. I'm using the large-v2 model. (Sorry if something like this already exists I couldn't find anything.)

Update: It is very random, it appears that the time does not matter. Sometimes it'll transcribe a two-hour file completely fine and other times it will fail on a 20-minute file.

**Comment by Purfview** [comment]
Try `--best_of=1`.

**Comment by blackpolarz** [comment]
The fact that the error _CUDA failed with error out of memory_ happens randomly makes me suspect there might be some other programs running on the background that happen to use the gpu. There are too many possibilities that can lead to that. 
What I can propose is perhaps splitting the audio manually into smaller files so that each time it crashes you don't lose as much?
Alternatively, perhaps you can attempt to do the transcription with a smaller model? 
Note that VRAM usage do spikes at times.

**Comment by westhecool** [comment]
> Try `best_of=1`.

Thanks for the suggestion but it didn't seem to help.

**Comment by westhecool** [comment]
> The fact that the error _CUDA failed with error out of memory_ happens randomly makes me suspect there might be some other programs running on the background that happen to use the gpu. There are too many possibilities that can lead to that. What I can propose is perhaps splitting the audio manually into smaller files so that each time it crashes you don't lose as much? Alternatively, perhaps you can attempt to do the transcription with a smaller model? Note that VRAM usage do spikes at times.

I have thought of that and I've tried closing all other apps on my PC to no avail. The spike seems to be undetectable by task manager so I have no idea what could be causing it.

**Comment by Purfview** [comment]
Where and how do you run it?

**Comment by Purfview** [comment]
You could say that from the start...
Try to update wsl to latest, run this in console: `wsl --update --pre-release`

**Comment by westhecool** [comment]
> You could say that from the start... Try to update wsl to latest, run this in console: `wsl --update --pre-release`

That actually worked, thanks. Such as silly issue though, probably should have checked before I made a report.
