### ISSUE TITLE
Implementation with Large-v3 but with Batching

### ISSUE THREAD

**Issue by souvikqb** [guillaumekln/faster-whisper#553]
I saw a large-v3 implementation with faster_whisper (https://github.com/guillaumekln/faster-whisper/issues/547) but it's quite slow. 

Large-v3 is very fast with batching as shown here --- https://huggingface.co/openai/whisper-large-v3

Batching speeds up the transcription process by a lot. The only reason I wish to use faster_whisper is cause it provides things like srt, verbose, word level transcription

**Comment by phineas-pta** [comment]
> srt, verbose, word level transcription

u can write code to do those things with `transformers` interface

**Comment by souvikqb** [comment]
> > srt, verbose, word level transcription
> 
> u can write code to do those things with `transformers` interface

Do you have any resource.that I can use

**Comment by phineas-pta** [comment]
word timestamp is an option when u call the pipeline

fort srt just retrieve timestamp and format properly

**Comment by souvikqb** [comment]
> word timestamp is an option when u call the pipeline
> 
> fort srt just retrieve timestamp and format properly

No I meant do you have a dedicated function that I can use to convert it? For srt and verbose

**Comment by phineas-pta** [comment]
see my comment in openai/whisper#654

**Comment by souvikqb** [comment]
> see my comment in [openai/whisper#654](https://github.com/openai/whisper/discussions/654)

Hey thanks! That sorts out my srt requirement. Now just looking for verbose and word

**Comment by phineas-pta** [comment]
as i said, word timestamp is an option when call the pipeline

**Comment by souvikqb** [comment]
> as i said, word timestamp is an option when call the pipeline

I actually got an error on running this --

**Comment by phineas-pta** [comment]
ask in `transformers` github repo
