### ISSUE TITLE
beam_size default setting

### ISSUE THREAD

**Issue by kristopher-smith** [guillaumekln/faster-whisper#6]
Hey great job on this package. Already enjoying the improvements.

I found in your README the following: 

***Verify that the same transcription options are used, especially the same beam size. For example in openai/whisper, model.transcribe uses a default beam size of 1 but here we use a default beam size of 5.***

A link below shows the default beam size from openAI to be 5 as well.

https://github.com/openai/whisper/blob/a6b36ede1f060860d5676a543176a6439d91eae6/whisper/transcribe.py#L272

**Comment by guillaumekln** [comment]
Hello,

The default beam size is 5 when using the `whisper` command line, but not when calling the `model.transcribe` method. Here the beam size [defaults to `None`](https://github.com/openai/whisper/blob/7858aa9c08d98f75575035ecd6481f462d66ca27/whisper/decoding.py#L80) which means that [greedy decoding is used](https://github.com/openai/whisper/blob/7858aa9c08d98f75575035ecd6481f462d66ca27/whisper/decoding.py#L482-L487).

I added the note in the README precisely for this reason.
