### ISSUE TITLE
how can I use this repo? The instructions are not so clear for me

### ISSUE THREAD

**Issue by search620** [guillaumekln/faster-whisper#63]
How do I use this fast model or method? 
I really want to gain 80% more speed because I need to translate a large library of video.

I downloaded this model from one of the threads here.
https://drive.google.com/u/0/uc?id=13Oq6wlrmzXeP8ciJ9p9R-pE5m1iJb9aq&export=download

Any help would be appreciated! :) Thanks!

**Comment by guillaumekln** [comment]
To use this Python library, you would need to define a small Python script as shown in the [README](https://github.com/guillaumekln/faster-whisper#usage) and then run this Python script from the command line.

Alternatively, some people shared small command line utillities build on top of this library. See for example:
* https://github.com/guillaumekln/faster-whisper/issues/32#issuecomment-1478826979
* https://github.com/jordimas/whisper-ctranslate2

**Comment by search620** [comment]
@guillaumekln 
Thank you for the reply. Would it be possible to also create a graphical user interface (GUI) for it? something simple like...
*input browsing
*output browsing
*choose model
How complicated is it to do something like this?

**Comment by guillaumekln** [comment]
Sure it's possible, but it is not in the scope of this repository.

Maybe someone will build this kind of application and share it here.
