### ISSUE TITLE
This is very cool, but push to even higher gpu usage?

### ISSUE THREAD

**Issue by junchen6072** [guillaumekln/faster-whisper#66]
First, thank you for this awesome work and it indeed improves the transcribe time a lot!
But I'm wondering if it's possible to push to even higher gpu usage so it can be even faster?
From my testing to transcribe a few audios whose length is between 2mins to 15mins, gpu usage is jumping between 70-90%, and occasionally drop to quite low. Tried to instantiate WhisperModel with higher cpu_threads and num_workers, but it doesn't seem to help?
I guess there're some non trivial blocking cpu computation so gpu is not fully utilized. Tried to use a thread pool in python to submit jobs for audios, it has a bit improvement, the peak gpu usage can go higher, but I think on average it didn't increase too much.

Any ideas? Thanks!

**Comment by guillaumekln** [comment]
> Tried to use a thread pool in python to submit jobs for audios,

That's a good approach. Did you also increase `num_workers` when doing that? Normally this should overlap kernel executions on the GPU and increase the usage.

**Comment by junchen6072** [comment]
> > Tried to use a thread pool in python to submit jobs for audios,
> 
> That's a good approach. Did you also increase `num_workers` when doing that? Normally this should overlap kernel executions on the GPU and increase the usage.

Yes I did. I think the bottleneck may be more in the python code, we're blocking wait on self.model.generate

**Comment by junchen6072** [comment]
Another observation is, using 2 threads in the pool seems better than more

**Comment by guillaumekln** [comment]
Are you using `word_timestamps=True`?

**Comment by guillaumekln** [comment]
Yes, it's slower than the default transcription mode (see #45).

And some operations are indeed running on the CPU in this mode which explains the lower GPU usage. There could be further improvements in the future.

**Comment by junchen6072** [comment]
I see, thanks! Is the cpu part mostly on faster-whisper, or CTranslate2?

**Comment by guillaumekln** [comment]
Higher GPU usage would probably come from some form of batch execution. This is discussed in #59.
