### ISSUE TITLE
Cannot produce the same result 

### ISSUE THREAD

**Issue by zara0m** [guillaumekln/faster-whisper#69]
Hello,

I tried to produce same result of the reported table, 
I used a whisper small, cpu_threads=8, on 13 min audio, Intel(R) Xeon(R) Gold 6242 CPU 2.8 GHz 16 cores,

And it took:
openai/whisper fp 32: 6min 19s 
faster whisper fp 32 : 5min 1s
faster whisper int 8: 4min 17s

Could you please guide me?

Thanks.

**Comment by guillaumekln** [comment]
Hi,

Can you post the script or code you used to run openai/whisper and faster-whisper?

**Comment by zara0m** [comment]
Faster-whisper:

!pip install "faster-whisper @ git+https://github.com/guillaumekln/faster-whisper@master#faster-whisper[conversion]"
!ct2-transformers-converter --model openai/whisper-small --output_dir small-int8 --copy_files tokenizer.json --quantization int8

from faster_whisper import WhisperModel
model_path = "small-int8/"
model = WhisperModel(model_path, device="cpu", compute_type="int8", cpu_threads=8)
import librosa
y, sr = librosa.load(audiofile, duration = 780)

segments, info = model.transcribe(y, beam_size=5)
segments = list(segments)


For whisper:
import whisper
model = whisper.load_model("small")
import librosa
y, sr = librosa.load(audiofile, duration = 780)
segments = model.transcribe(y)

**Comment by guillaumekln** [comment]
You are not comparing with the same beam size. You should add `beam_size=5` for openai/whisper.

See the note about this in [README](https://github.com/guillaumekln/faster-whisper#comparing-performance-against-other-implementations).

**Comment by zara0m** [comment]
Thanks for your help!

**Comment by junchen6072** [comment]
> You are not comparing with the same beam size. You should add `beam_size=5` for openai/whisper.
> 
> See the note about this in [README](https://github.com/guillaumekln/faster-whisper#comparing-performance-against-other-implementations).

I'm wondering why faster-whipser use default beam_size=5. It didn't work well for one of my audios where the first 20ish seconds was waiting on phone pickup(dududu), and the whole transcribe is 'hello..hello..'

**Comment by guillaumekln** [comment]
5 is the default value when using the `whisper` command in the original implementation. It is also the value reported in the research paper.
