### ISSUE TITLE
av audio library can not determine audio format

### ISSUE THREAD

**Issue by xanguera** [guillaumekln/faster-whisper#74]
On some wav audio files the av library crashes when trying to open the file in [here](https://github.com/guillaumekln/faster-whisper/blob/master/faster_whisper/audio.py#L37).
After some debugging I decided to pass an extra parameter to the open function: format="wav" which gets past this point, but then crashes in the next line with "AttributeError: 'av.container.output.OutputContainer' object has no attribute 'decode'".
Any idea on how to proceed? this seems to be an av library problem, but I checked that my system had the latest version installed (10.0.0) and there is no report on this error since more than 2 years ago.

**Comment by guillaumekln** [comment]
What is the exact error message before changing the code?

Is there a similar error if you use FFmpeg directly?

```
ffmpeg -i input.wav -ar 16000 -ac 1 -c:a pcm_s16le output.wav
```

**Comment by xanguera** [comment]
Here are the last few lines of the error traceback:

>       segments, info = model.transcribe(audio_file.file, language="en", beam_size=5)
>     File "/code/fasterWhisper/faster_whisper/transcribe.py", line 200, in transcribe
>       audio = decode_audio(
>     File "/code/fasterWhisper/faster_whisper/audio.py", line 37, in decode_audio
>       with av.open(input_file, metadata_errors="ignore") as container:
>     File "av/container/core.pyx", line 411, in av.container.core.open
>     File "av/container/core.pyx", line 219, in av.container.core.Container.__cinit__
>       ValueError: Could not determine output format

**Comment by guillaumekln** [comment]
If I understand correctly the PyAV code raising the error, it tries to guess the audio format based on the file extension.

What is the file extension of these audio files?

**Comment by xanguera** [comment]
It is a wav file. I am uploading it here (I had to zip it for github not to complain, sorry).

[audio.wav.zip](https://github.com/guillaumekln/faster-whisper/files/11066147/audio.wav.zip)

**Comment by xanguera** [comment]
Thanks for such quick response.
I believe I found the culprit of the problem, though not yet the solution. It does not have to do with faster-whisper directly. 
I have built a FastAPI-based server and I am receiving the audio files via multi-part upload using [this fastAPI method](https://fastapi.tiangolo.com/tutorial/request-files/#import-file).
According to the documentation, for short files, they are kept in memory, while for longer files they are stored temporarily on disk. In both cases they claim that a file-like interface is provided to other functions like faster-whisper.
The problem comes here: if the file is large, it works, if the file is short (and kept in memory) it does not work.
I a trying to find out why, and then a solution. I will post here whenever I do as most probably other people might face the same issue.
The fastAPI receiving endpoint is defined as follows:

    @app.post("/asr")
    def transcribe(
                audio_file: UploadFile = File(...),
                ):

    segments, info = model.transcribe(audio_file.file, language="en", beam_size=5)

    # output
    result = []
    for segment in segments:
        result.append({"start":segment.start, "end":segment.end, "utt":segment.text})
    return {"success":True, "result":result}
`

**Comment by xanguera** [comment]
Ok, mistery solved. As I mentioned above, the problem ended not being faster-whisper, but hos fastAPI deals with the audio being sent to it. If the file stays in memory, the av library is not happy with it.
I forced the SpooledTemporaryFile to store contents in memory by adding `audio_file.file.fileno()` right before the call to transcribe.
Thank you for your support!

**Comment by winstxnhdw** [comment]
Shouldn't be a FastAPI issue. Frankly, Whisper should be able to handle in-memory files..
