### ISSUE TITLE
Support speaker marker output 

### ISSUE THREAD

**Issue by taf2** [guillaumekln/faster-whisper#78]
Whisper.cpp has an option to output speaker markers when feeding multi channel audio files. Is this possible with faster whisper?

**Comment by guillaumekln** [comment]
Can you check this discussion? https://github.com/openai/whisper/discussions/937#discussioncomment-5165620

It provides an example on how to decode stereo audio into left and right channels. Each channel can then be transcribed separately.

From a brief research, I think whisper.cpp is doing the same thing?

**Comment by taf2** [comment]
Thank you!
