### ISSUE TITLE
Sync existing transcript

### ISSUE THREAD

**Issue by Ryan5453** [guillaumekln/faster-whisper#84]
Hello,

I was wondering if it would be possible to somehow use Whisper to be able to time sync existing transcripts. I have many very accurate transcriptions of audio but they are not line and/or word synced, so it would be great if somehow I would feed that transcript to Whisper so it can sync it.

**Comment by EtienneAb3d** [comment]
You may try this:
https://github.com/EtienneAb3d/WhisperTimeSync
