### ISSUE TITLE
Error code 126

### ISSUE THREAD

**Issue by git-eternal** [guillaumekln/faster-whisper#85]
OUTPUT:

Could not load library cudnn_ops_infer64_8.dll. Error code 126
Please make sure cudnn_ops_infer64_8.dll is in your library path!

OS: Windows 10

Even after installing the CUDA toolkit from https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64, and the CUDNN library and extracting it and putting it into my PATH system enviroment variable, i still get this issue.

**Comment by guillaumekln** [comment]
Just to make sure, did you install CUDA 11.x? (CUDA 12.x is not supported for now.)

When I tried the installation on Windows I had the same error because I missed the step "Installing Zlib" from the [official installation guide](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows). Can you check that?

**Comment by git-eternal** [comment]
> 
Still get the exact same issue sadly. Would you mind giving me the download link you used for both CUDANN and the CUDA dev toolkit?

**Comment by guillaumekln** [comment]
The cuDNN paths looks correct to me. Did you also restart to terminal before testing again?

> Would you mind giving me the download link you used for both CUDANN and the CUDA dev toolkit?

* CUDA: https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_network
* cuDNN: https://developer.nvidia.com/downloads/compute/cudnn/secure/8.8.1/local_installers/11.8/cudnn-windows-x86_64-8.8.1.3_cuda11-archive.zip/

**Comment by git-eternal** [comment]
Thank you. It was the cuDNN version I had that was breaking it. Using the one you linked now makes the program work totally fine!

**Comment by athu16** [comment]
Unfortunately I'm having the same issue. I've installed both CUDA and cuDNN from the links provided above (CUDA 11.8 & cuDNN for CUDA 11.x), added it to the system path, and installed zlib. Is there anything else I need to do?

**Comment by git-eternal** [comment]
I just restarted my pc and it worked fine

**Comment by athu16** [comment]
After a day of trial and error, I finally solved the issue!

For anyone having a problem, copy all DLLs from CUDNN, as well as `cublasLt64_11.dll` from the GPU Computing Toolkit into your ctranslate2 package directory. Since I'm using a venv, it was `\faster-whisper\venv\Lib\site-packages\ctranslate2"`, but if you use Conda or just regular Python without virtual environments, it'll be different.

**Comment by ycyy** [comment]
> After a day of trial and error, I finally solved the issue!经过一天的反复试验，我终于解决了这个问题！
> 
> For anyone having a problem, copy all DLLs from CUDNN, as well as `cublasLt64_11.dll` from the GPU Computing Toolkit into your ctranslate2 package directory. Since I'm using a venv, it was `\faster-whisper\venv\Lib\site-packages\ctranslate2"`, but if you use Conda or just regular Python without virtual environments, it'll be different.对于遇到问题的任何人，请将 CUDNN 中的所有 DLL 以及 GPU Computing Toolkit 中的 `cublasLt64_11.dll` 复制到您的 ctranslate2 包目录中。由于我使用的是 venv，它是 `\faster-whisper\venv\Lib\site-packages\ctranslate2"` ，但如果你使用 Conda 或只是没有虚拟环境的常规 Python，它会有所不同。

i use conda,copy all dll from `faster-whisper\Lib\site-packages\torch\lib` to `faster-whisper\venv\Lib\site-packages\ctranslate2` solve this problem.

**Comment by ILG2021** [comment]
https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_522.06_windows.exe
https://drive.google.com/file/d/1Hf2nb38Fj6yYEQjVGw2AQ9BXcdj4vJ9O/view?usp=share_link
The second link is a execute which I made by Inno Setup that packages cudnn folder, zip dll and when it is installed it will automatically add path to environment. To make life easier.

**Comment by abdulnim** [comment]
I had the same issue downloading Zlib and adding zlibwapi.dll to the environment variable PATH fixed the issue.

**Comment by opink** [comment]
I replace *.dll path code in __init__.py (path in my conda env "D:\Anaconda3\envs\whisper\Lib\site-packages\ctranslate2\__init__.py" ), and it works.

"""
# Origin code on 18 line
    # for library in glob.glob(os.path.join(package_dir, "*.dll")):
    #     ctypes.CDLL(library)

# after changed，work!
    all_dllfile_list = glob.glob(os.path.join("/".join(package_dir.split('\\')[0:-1]) + "/torch/lib/", "*.dll"))
    all_dllfile_list.append(r"D:\Anaconda3\envs\whisper\Lib\site-packages\ctranslate2\ctranslate2.dll")
    for library in all_dllfile_list:
        ctypes.CDLL(library)
"""

**Comment by opink** [comment]
> > After a day of trial and error, I finally solved the issue!经过一天的反复试验，我终于解决了这个问题！
> > For anyone having a problem, copy all DLLs from CUDNN, as well as `cublasLt64_11.dll` from the GPU Computing Toolkit into your ctranslate2 package directory. Since I'm using a venv, it was `\faster-whisper\venv\Lib\site-packages\ctranslate2"`, but if you use Conda or just regular Python without virtual environments, it'll be different.对于遇到问题的任何人，请将 CUDNN 中的所有 DLL 以及 GPU Computing Toolkit 中的 `cublasLt64_11.dll` 复制到您的 ctranslate2 包目录中。由于我使用的是 venv，它是 `\faster-whisper\venv\Lib\site-packages\ctranslate2"` ，但如果你使用 Conda 或只是没有虚拟环境的常规 Python，它会有所不同。
> 
> i use conda,copy all dll from `faster-whisper\Lib\site-packages\torch\lib` to `faster-whisper\venv\Lib\site-packages\ctranslate2` solve this problem.

Thx a lot.

I replace '*.dll path' code in  __ init __ .py ( my conda env  "D:\Anaconda3\envs\whisper\Lib\site-packages\ctranslate2 \  __ init __ .py" ), and it works.


# Original code on 18 line
    # for library in glob.glob(os.path.join(package_dir, "*.dll")):
    #     ctypes.CDLL(library)

# after changed，work!
    all_dllfile_list = glob.glob(os.path.join("/".join(package_dir.split('\\')[0:-1]) + "/torch/lib/", "*.dll"))
    all_dllfile_list.append(r"D:\Anaconda3\envs\whisper\Lib\site-packages\ctranslate2\ctranslate2.dll")
    for library in all_dllfile_list:
        ctypes.CDLL(library)

**Comment by AngryBacteria** [comment]
I have this exact same bug. Weirdly enough it does not happen on an isolated python project with just a venv and this pip package. But if I try to run it in a fastapi application it does not work. The versions are exactly the same. What could be the reason for this? This behavior seems weird to me. I already tried to delete the venv folder and create a new one with the same result

**Comment by realcoloride** [comment]
For those who need it, check your cuda version and run the appropriate commands: (along with installing cuda and cudnn)
https://pytorch.org/get-started/previous-versions/#linux-and-windows-2

if that doesnt work, try a venv and reinstall everything and run those commands.
