### ISSUE TITLE
How do I get the avg_logprob , compression_ratio and no_speech_prob of the output? 

### ISSUE THREAD

**Issue by palladium123** [guillaumekln/faster-whisper#87]
Thank you for porting this to cTranslate2, really helps running the large model on my 3060 laptop (not possible with OpenAI's implementation)

Is there a way to get the properties of the model output? In OpenAI's implementation a dictionary is returned when model.transcribe is called, something like this:

This is Python.
{'text': ' This is Python.', 'segments': [{'id': 0, 'seek': 0, 'start': 0.0, 'end': 4.0, 'text': ' This is Python.', 'tokens': [50364, 639, 307, 15329, 13, 50564], 'temperature': 0.0, 'avg_logprob': -0.6939573287963867, 'compression_ratio': 0.7142857142857143, 'no_speech_prob': 0.13947993516921997}], 'language': 'en'}

I looked at the source code, seems like generate_with_fallback() returns avg_logprob but not the rest...?

TIA

**Comment by guillaumekln** [comment]
On a related note, are these information actually useful? Because the values are obtained from the 30-second window, but a window can contain multiple segments. In this case the values are just copied to each segment.

**Comment by palladium123** [comment]
In my use case (a semi live dictation scenario) I find these properties( esp. no_speech_prob) useful in rejecting unintelligible speech or speech that is too quiet. In my use case I don't suppress any tokens as I need whisper (or faster-whisper) to dictate punctuations for me on demand (like brackets and colons). Without rejecting quiet speech sometimes Whisper will transcribe things like [SILENT]. I use it in conjunction with a (modified) lightweight dictation script by Nikorasu:

https://github.com/Nikorasu/LiveWhisper

I am still working on the PR. My primary trade is not IT/programming so please bear with  my relative lack of skill/experience

**Comment by guillaumekln** [comment]
Resolved by #103.
