### ISSUE TITLE
Understanding multiple languages makes unwanted Translations

### ISSUE THREAD

**Issue by MustafaCQN** [guillaumekln/faster-whisper#98]
I was using the model (large-v2) for transcribing our meetings. But we were using 2 languages with the speaker 1. native language (Turkish) and the 2. part for checking the level of English we are switching to the English.

The problem is, if model first understands the Turkish is the language, then it will transcribe the whole meeting in Turkish. Even the English parts are translated to Turkish. But we don't want to use the automatic translation.

How I can solve this or is it an unwanted outcome?

**Comment by thet0ast3r** [comment]
This should have nothing to do with faster-whisper. more like just whisper.

**Comment by guillaumekln** [comment]
Yes, this is how the Whisper model is currently working. See for example this discussion https://github.com/openai/whisper/discussions/49

There are multiple solutions, but I don't know which one is more effective. You could first identity the speaker and transcribe each segment separately. Or if the speakers are clearly separated in the audio you could apply VAD and then again transcribe each segment separately.
